### ISSUE TITLE
react-test-renderer does not mock React Native Animated

### ISSUE THREAD

**Issue by sospedra** [facebook/react#10542]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Animated is not mocked

Using 
`react-native` 0.47
`jest` 20
`react` 16
`react-test-renderer` 16

Implement any `Animated` component. With the `new Animated.value` and so on. And make a snapshot test.

It'll return:

<details>
  <summary>Log error</summary>
  
  ```
   const wrapper = this._environment.runScript(transformedFile.script)[
                                                                       ^

TypeError: Cannot read property 'Object.<anonymous>' of null
    at Runtime._execModule (/Users/rigel/labs/mobile-apps/node_modules/jest-runtime/build/index.js:510:72)
    at Runtime.requireModule (/Users/rigel/labs/mobile-apps/node_modules/jest-runtime/build/index.js:329:14)
    at Runtime.requireModuleOrMock (/Users/rigel/labs/mobile-apps/node_modules/jest-runtime/build/index.js:405:19)
    at Function.bezier (/Users/rigel/labs/mobile-apps/node_modules/react-native/Libraries/Animated/src/Easing.js:228:13)
    at ease (/Users/rigel/labs/mobile-apps/node_modules/react-native/Libraries/Animated/src/Easing.js:94:14)
    at TimingAnimation._easing (/Users/rigel/labs/mobile-apps/node_modules/react-native/Libraries/Animated/src/Easing.js:262:10)
    at TimingAnimation.onUpdate (/Users/rigel/labs/mobile-apps/node_modules/react-native/Libraries/Animated/src/AnimatedImplementation.js:338:22)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
  ```
</details>

<br/>
**What is the expected behavior?**
Should mock properly `Animated`, like the other `react-native` components so it doesn't break.

**Comment by aweary** [comment]
Hey, @sospedra! The test renderer does not mock any components for React or React Native. According to the Jest docs, [React Native provides some default mocks for Jest](https://facebook.github.io/jest/docs/en/tutorial-react-native.html#mock-native-modules-using-jestmock). I would recommend referring to the React Native [support resources](http://facebook.github.io/react-native/support.html) or issue tracker for help with this.

Thanks!
