### ISSUE TITLE
Errors. Guys, help me, pls

### ISSUE THREAD

**Issue by kroobeet** [facebook/react#11407]
```
Error: Cannot find module 'process-nextick-args'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ubuntu/.nvm/versions/node/v6.11.2/lib/node_modules/npm/node_modules/readable-stream/lib/_stream_readable.js:26:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

I want to set yarn, but the terminal shows this error after entering the command
`npm install yarn`
package.json
```
{
  "name": "workspace",
  "private": true,
  "scripts": {
    "start": "meteor --port $IP:$PORT"
  },
  "dependencies": {
    "babel-runtime": "^6.26.0",
    "bcrypt": "^1.0.3",
    "classnames": "^2.2.5",
    "history": "^4.7.2",
    "meteor-node-stubs": "^0.2.11",
    "moment": "^2.19.1",
    "prop-types": "^15.6.0",
    "react": "^16.0.0",
    "react-addons-pure-render-mixin": "^15.6.2",
    "react-dom": "^16.0.0",
    "react-router": "^4.2.0"
  }
}

```

HELP PLS!!

**Comment by jquense** [comment]
Hey there, it looks like you have an issue with your build or environment setup. We want to keep the issue tracker is for bugs and feature requests in React. I would suggest trying one of the many support resources for help: https://reactjs.org/community/support.html
