### ISSUE TITLE
scripts/jest/matchers/toWarnDev: "Unexpected warning recorded: null" when there's no null, caused by jest-diff returning null

### ISSUE THREAD

**Issue by sompylasar** [facebook/react#12284]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Example:
```js
      // getTestDocument() has an extra <meta> that we didn't render.
      expect(() =>
        ReactDOM.hydrate(<Component text="Hello world" />, testDocument),
      ).toWarnDev('Did not expect server HTML to contain a <meta> in <head>.');
```

If the actual warning is multiline:
```
"Warning: Did not expect server HTML to contain a <meta charset="utf-8"> in <head>.
    in title (at **)
    in head (at **)
    in html (at **)
    in Component (at **)"
```

The output message received from the `toWarnDev` matcher is confusing:
```
  ● rendering React components at document › with new explicit hydration API › should render w/ no markup to full document

    Error: Unexpected warning recorded: null

      60 |         // We don't throw an Error here though,
      61 |         // Because it might be suppressed by ReactFiberScheduler.
    > 62 |         unexpectedWarnings.push(new Error(errorMessage));
      63 |       };
      64 | 
      65 |       // TODO Decide whether we need to support nested toWarn* expectations.
      
      at CustomConsole.consoleSpy (scripts/jest/matchers/toWarnDev.js:62:35)
      at printWarning (node_modules/fbjs/lib/warning.js:33:15)
      at warning (node_modules/fbjs/lib/warning.js:57:20)
      at warnForDeletedHydratableElement (packages/react-dom/src/client/ReactDOMFiberComponent.js:1424:473)
      at didNotHydrateInstance (packages/react-dom/src/client/ReactDOM.js:938:11)
      at deleteHydratableInstance (packages/react-reconciler/src/ReactFiberHydrationContext.js:106:11)
```

**What is the expected behavior?**

Expected `toWarnDev` to at least show the original and the expected messages without a fancy `jest-diff`, but not `null`.

Upstream bug in `jest-diff`: https://github.com/facebook/jest/issues/5657

**Comment by gaearon** [comment]
Seems like this got fixed?
