### ISSUE TITLE
React.createElement: type is invalid

### ISSUE THREAD

**Issue by dkfiresky** [facebook/react#12329]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
import React from 'react';
import { renderToString } from 'react-dom/server';
import { StaticRouter, Route, IndexRoute, Link } from 'react-router';

class Dashboard extends React.Component {
  render() {
    return (
      <div>
        <h1>Dashboard</h1>
      </div>
    );
  }
}

class App extends React.Component {
  render() {
    return (
      <div>
        <Link to="/">Dashboard</Link>

        <Route path="/">
          <IndexRoute component={Dashboard} />
        </Route>
      </div>
    );
  }
}

const html = renderToString(
  <StaticRouter location={request.url} context={context}>
    <App />
  </StaticRouter>
);
```

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
    in App
    in Router
    in StaticRouter

TypeError: Cannot read property 'toLowerCase' of undefined
    at ReactDOMServerRenderer.renderDOM (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2304:28)
    at ReactDOMServerRenderer.render (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2298:21)
    at ReactDOMServerRenderer.read (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2234:19)
    at renderToString (/node_modules/react-dom/cjs/react-dom-server.node.development.js:2501:25)
    at <anonymous>
```

**What is the expected behavior?**

Rendered Dashboard component.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

react: **16.2.0**
react-dom: **16.2.0**
react-router: **4.2.0**

**Comment by TrySound** [comment]
@dkfiresky The bug is in your code. react-router does not export `IndexRoute`.

**Comment by dkfiresky** [comment]
@TrySound thanks, but even if I use `Route` instead of `IndexRoute`, I have the same error.

**Comment by dkfiresky** [comment]
@TrySound thanks for help, it seems I've used old `react-router` tutorial, and the `Link` is not exported as well.
