### ISSUE TITLE
Invariant Violation: setEnabled(), was asked to report immediately.

### ISSUE THREAD

**Issue by yoshuawuyts** [facebook/react#1287]
I'm trying out the testUtils and some things are breaking. On node `0.11.12`:
**STDOUT:**

```
~/Code/tests   
❯ mocha test

  ․․

  1 passing (125ms)
  1 failing

  1) test our tests should render a label:
     Error: Invariant Violation: setEnabled(...): Cannot toggle event listening in a Worker thread. This is likely a bug in the framework. Please report immediately.
      at invariant (/home/yoshua/Code/tests/node_modules/react/lib/invariant.js:52:19)
      at Object.merge.setEnabled (/home/yoshua/Code/tests/node_modules/react/lib/ReactEventEmitter.js:206:46)
      at ReactReconcileTransaction.EVENT_SUPPRESSION.initialize (/home/yoshua/Code/tests/node_modules/react/lib/ReactReconcileTransaction.js:58:23)
      at ReactReconcileTransaction.Mixin.initializeAll (/home/yoshua/Code/tests/node_modules/react/lib/Transaction.js:197:30)
      at ReactReconcileTransaction.Mixin.perform (/home/yoshua/Code/tests/node_modules/react/lib/Transaction.js:158:12)
      at ReactComponent.Mixin.mountComponentIntoNode (/home/yoshua/Code/tests/node_modules/react/lib/ReactComponent.js:537:19)
      at Object.<anonymous> (/home/yoshua/Code/tests/node_modules/react/lib/ReactMount.js:309:25)
      at Object._renderNewRootComponent (/home/yoshua/Code/tests/node_modules/react/lib/ReactPerf.js:57:21)
      at Object.ReactMount.renderComponent (/home/yoshua/Code/tests/node_modules/react/lib/ReactMount.js:359:32)
      at Object.renderComponent (/home/yoshua/Code/tests/node_modules/react/lib/ReactPerf.js:57:21)
      at Object.ReactTestUtils.renderIntoDocument (/home/yoshua/Code/tests/node_modules/react/lib/ReactTestUtils.js:57:18)
      at Context.<anonymous> (/home/yoshua/Code/tests/test.js:38:23)
      at callFn (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runnable.js:223:21)
      at Test.Runnable.run (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runnable.js:216:7)
      at Runner.runTest (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:374:10)
      at /home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:452:12
      at next (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:299:14)
      at /home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:309:7
      at next (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:247:23)
      at Immediate._onImmediate (/home/yoshua/.nvm/v0.11.12/lib/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:374:17)
```

**test.js:**

``` js
/**
 * Module dependencies
 */

var React = require('react/addons');
var should = require('should');
var mocha = require('mocha');
var jsdom = require('jsdom');
var utils = React.addons.TestUtils;

/**
 * Initialize variables
 */

var document;
var window;

/**
 * Initialize jsdom
 */

beforeEach(function() {
  global.window = jsdom.jsdom().createWindow('<html><body></body></html>');
  global.document = global.window.document;
});

/**
 * Tests
 */

describe('test our tests', function() {
  it('should display the window objects', function () {
    global.window.should.exist;
    global.document.should.exist;
  });

  it('should render a label', function () {
    var label = utils.renderIntoDocument(React.DOM.label(null, 'hi'));
  })
})
```

**package.json:**

``` js
{
  "name": "tests",
  "version": "0.0.0",
  "description": "",
  "main": "test.js",
  "dependencies": {
    "react": "^0.10.0"
  },
  "devDependencies": {
    "mocha": "^1.18.2",
    "jsdom": "^0.10.3",
    "should": "^3.2.0-beta1"
  },
  "scripts": {
    "test": "mocha"
  },
  "author": "Yoshua Wuyts",
  "license": "MIT"
}
```

**Comment by silvenon** [comment]
Sorry for resurrecting this thread, but this is still a mystery to me. If I have to require React when I have a document already available, how come this Mocha test works? Was this fixed in the meantime?

```js
import React from 'react/addons';
import jsdomify from 'jsdomify';
import assert from 'assert';

describe.only('Example', () => {
  before(() => {
    jsdomify.create();
  });

  it('works if React is required before a document was available', () => {
    const div = React.addons.TestUtils.renderIntoDocument(<div exists={true} />);
    assert(div.props.exists);
  });

  after(() => {
    jsdomify.destroy();
  });
});
```

I required it **before** I initialized jsdom. ([jsdomify](https://github.com/podio/jsdomify/blob/master/lib/jsdomify.js) is just a convenience wrapper around jsdom.)

**Comment by silvenon** [comment]
Nevermind, it breaks as soon as I call `setState`, simulate an event etc.

**Comment by stenrap** [comment]
I'm also sorry for resurrecting this old thread, but I'm running into this exact problem and none of the suggestions above have worked:

```javascript
var sinon = require('sinon');
var expect = require('chai').expect;
var jsdom = require('jsdom');
var React;
var TestUtils;
var view;

describe('The student name view', function() {
    
    var nameChangedStub = sinon.stub();
    var nameSubmittedStub = sinon.stub();
    
    before(function() {
        global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
        global.window = document.defaultView;
        global.navigator = {
            userAgent: 'node.js'
        };
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;
        view = require('../student-name-view.js');
        this.renderedComponent = TestUtils.renderIntoDocument(
            view({
                nameChanged:   nameChangedStub,
                nameSubmitted: nameSubmittedStub
            })
        );
        this.nameInput = TestUtils.findRenderedDOMComponentWithTag(this.renderedComponent, 'input').getDOMNode();
    });
    
    describe('should notify the controller', function() {
        
        it('when the name field changes', function() {
            TestUtils.Simulate.change(this.nameInput);
            expect(nameChangedStub.called).to.be.true;
        });
        
    });
    
});
```

I'm running the following:

React 0.10.0 (very old I know)
jsdom 6.5.1
mocha 2.3.3

Any ideas what I'm doing wrong?

**Comment by yoshuawuyts** [comment]
@stenrap can you please open a new issue about this? Thanks.
