### ISSUE TITLE
Returning an empty fragment throws a confusing error

### ISSUE THREAD

**Issue by aweary** [facebook/react#12964]
https://codesandbox.io/s/40j50607y0

Rendering a component like:

```js
const Foo = () => <React.Fragment />
```

Throws the error:

> Foo(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.

The error is confusing because clearly `Foo` _is_ returning a value. I don't know if we want to support rendering empty fragments, but in any case this error is confusing.

If this isn't allowed it should explicitly call out that a component cannot return a fragment with no children.

cc @gaearon

**Comment by aweary** [comment]
This also doesn't throw when using `renderToString`: https://codesandbox.io/s/7113m08k0

**Comment by gaearon** [comment]
I think that's just a bug.

**Comment by aweary** [comment]
So rendering empty fragments should be allowed?

**Comment by gaearon** [comment]
Fixed in React 16.4.1.

**Comment by ljharb** [comment]
This still seems to be an issue - on React 16.4.1, we're doing this:
```jsx
          const EmptyFragmentComponent = () => {
            <div className="container">
              <React.Fragment>
                <React.Fragment />
              </React.Fragment>
            </div>
          };

          const wrapper = mount(<EmptyFragmentComponent />);

          expect(wrapper.find('.container > span')).to.have.lengthOf(0);
          expect(wrapper.find('.container span')).to.have.lengthOf(0);
```

```sh
 Invariant Violation: EmptyFragmentComponent(...): Nothing was returned from render. This usually means a return statement is missing. Or, to render nothing, return null.
      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at reconcileChildFibers (node_modules/react-dom/cjs/react-dom.development.js:12692:13)
      at reconcileChildrenAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:13015:28)
      at reconcileChildren (node_modules/react-dom/cjs/react-dom.development.js:13006:3)
      at mountIndeterminateComponent (node_modules/react-dom/cjs/react-dom.development.js:13441:5)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:13820:14)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:15863:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:15902:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:15942:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16560:22)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16482:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16454:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16354:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16218:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16785:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16812:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16839:10)
      at ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17122:3)
      at node_modules/react-dom/cjs/react-dom.development.js:17262:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16679:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17258:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17317:12)
      at Object.render (packages/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:251:114)
      at new ReactWrapper (packages/enzyme/build/ReactWrapper.js:110:16)
      at mount (packages/enzyme/build/mount.js:19:10)
      at Context.<anonymous> (packages/enzyme-test-suite/test/ReactWrapper-spec.jsx:1157:27)
```

I would expect either a clear error message that empty Fragments are disallowed, or I would expect it to work the same as `[]`.

**Comment by gaearon** [comment]
For posterity, https://github.com/facebook/react/issues/12964#issuecomment-410399266 was caused by `{` rather than `(` in the function definition (so the invariant was correct).
