### ISSUE TITLE
react-dom throws "ReferenceError: requestAnimationFrame is not defined" in SSR environment since #12931

### ISSUE THREAD

**Issue by sompylasar** [facebook/react#13000]
**Do you want to request a *feature* or report a *bug*?**

bug 

**What is the current behavior?**

The https://github.com/facebook/react/pull/12931 change seems to have broken the server-side rendering on `master`: I'm attempting to `yarn start` the `fixtures/ssr` to test https://github.com/facebook/react/pull/12063 and getting the following error from the server-side when I load the `localhost:3000` page:
```
ReferenceError: requestAnimationFrame is not defined
    at /__CENSORED__/react/build/node_modules/react-dom/cjs/react-dom.development.js:5232:34
    at Object.<anonymous> (/__CENSORED__/react/build/node_modules/react-dom/cjs/react-dom.development.js:17632:5)
    at Module._compile (module.js:624:30)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .js] (/__CENSORED__/react/fixtures/ssr/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
```
It points to this line:
```js
// We capture a local reference to any global, in case it gets polyfilled after
// this module is initially evaluated.
// We want to be using a consistent implementation.
const localRequestAnimationFrame = requestAnimationFrame;
```

**What is the expected behavior?**

No ReferenceError in server-side environment.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

https://github.com/facebook/react/commit/79a740c6e32ca300d4e7ff55ab06de172d4237fd (not published at the time of writing)

Node environment: `fixtures/ssr` during server-side rendering in response to a browser request.

**Comment by sompylasar** [comment]
👉 fixed in https://github.com/facebook/react/pull/13001
