### ISSUE TITLE
cannot uninstall lodash from project

### ISSUE THREAD

**Issue by CraigMeng** [facebook/react#13095]
Hi Guys,

I use create-react-app to create a project and run eject after. I noticed that if I install lodash, and I uninstall it then, npm start will failed with following message (note that I don`t use any lodash or import lodash in my codes):

Error: Cannot find module 'lodash'
         at Function.Module._resolveFilename (module.js:476:15)
         at Function.Module._load (module.js:424:25)
         at Module.require (module.js:504:17)
         at require (internal/module.js:20:19)
         at Object.<anonymous> (C:/ (my home path)/testweb/node_modules/http-proxy-middleware/lib/index.js:1:84)
         at Module._compile (module.js:577:32)
         at Object.Module._extensions..js (module.js:586:10)
         at Module.load (module.js:494:32)
         at tryModuleLoad (module.js:454:12)
         at Function.Module._load (module.js:445:3)

React version: 15.6.2
lodash: 4.17.10

**Comment by gaearon** [comment]
This is not an issue with React. It’s probably an issue with the package manager you’re using (make sure not to mix them). If you find a minimal way to reproduce please feel free to file a bug with Yarn or npm (depending on which one you were using). There’s nothing actionable for us so I’m closing. For future reference, we’re using the React issue tracker for bugs in React itself (the library).

**Comment by CraigMeng** [comment]
@gaearon Sorry, I went to the wrong place

**Comment by gaearon** [comment]
No problem! Sorry we weren’t able to help.
