### ISSUE TITLE
React 16.5.0 causes all Jest unit tests to fail

### ISSUE THREAD

**Issue by aiden-carnegie** [facebook/react#13653]
I'm using Jest/ Enzyme to do unit tests in a project I'm working on, but recently upgrading to 16.5.0 has caused errors to appear in almost all of my unit tests.  The error occurs when use enzyme in a unit test to mount a component.  I've given an example of this code below:

```
const wrapper = mount(<ComponentName value='test' />);
```

However, since upgrading to 16.5.0, this always fails with the following error:

```
Invariant Violation: Unable to find node on an unmounted component.    
      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at findCurrentFiberUsingSlowPath (node_modules/react-reconciler/cjs/react-reconciler-reflection.development.js:155:30)
      at toTree (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:96:60)
      at Object.getNode (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:239:33)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:100:33)
      at mount (node_modules/enzyme/build/mount.js:19:10)
```
I've since downgraded to React 16.4.0 since it was not causing issues, but I think this should be looked at further.

Thanks!

**Comment by wyze** [comment]
You'll want to put together a reproducable example and also open this issue on the appropriate repo. I don't see this being a Jest issue but more of an Enzyme/React issue.

**Comment by jquense** [comment]
The error isn't descriptive of the actual problem. What's happening is **you haven't upgraded enzyme-adapter-react-16** to a version that is compatible with react 16.5. The result is you are getting  multiple instances of react/react-dom in the bundle and it's confusing React.
