### ISSUE TITLE
Error: Cannot find module 'binary-extensions'

### ISSUE THREAD

**Issue by vishakha7-4** [facebook/react#13771]
I am trying to use reactjs on local system. I followed the official documentation of reactjs and was trying its tutorial on tic tac toe.

For local development environment I followed all the steps but when I try to run npm start I am getting below error

module.js:549
    throw err;
    ^

Error: Cannot find module 'binary-extensions'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/locusrags/Documents/my-app/node_modules/is-binary-path/index.js:3:24)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I am using Node v8.11.3 and npm v5.6.0

FYI I have installed binary-extensions using npm i binary-extensions but I am still getting same error.

**Comment by gaearon** [comment]
You don’t need to install it directly. (To be honest I have no idea what it is.)

I’d recommend removing `node_modules` and `package-lock.json`, then running `npm install`. If this doesn’t help you can try using Yarn instead of npm.

Now that I think of it, it probably makes more sense to switch the Tutorial to use a plain HTML instead of a Node setup. I’ll do that later.

**Comment by vishakha7-4** [comment]
it worked with yarn..... Thanks so much....
