### ISSUE TITLE
Production build failing using yarn build on node 8.4

### ISSUE THREAD

**Issue by anomalyjane** [facebook/react#13910]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The development build is compiling correctly, but the production build is failing with an error related to rollup. This is the first time I've tried building react on my machine. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Clone project, run yarn install, run yarn build. I'm using node 8.4.0 and yarn 1.2.1. 

**What is the expected behavior?**
Builds without error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
OS is High Sierra 10.13.3, React Version 16.6.0

Output of error is here: 
```
-- BAD_BUNDLE_TRANSFORMER (scripts/rollup/plugins/closure-plugin) --
Error: Error transforming bundle with 'scripts/rollup/plugins/closure-plugin' plugin: java -jar /Users/emilyrobinson/projects/react/node_modules/google-closure-compiler/compiler.jar --compilation_level=SIMPLE --language_in=ECMASCRIPT5_STRICT --language_out=ECMASCRIPT5_STRICT --env=CUSTOM --warning_level=QUIET --apply_input_source_maps=false --use_types_for_optimization=false --process_common_js_modules=false --rewrite_polyfills=false --assume_function_wrapper=false --renaming=true --js=/var/folders/93/p2jzkfss6w74ypdxbfzfj5g40000gp/T/tmp-66094vSwydp7c3nLB.tmp

Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/javascript/jscomp/CommandLineRunner : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
    
at error (/Users/xxxxx/projects/react/node_modules/rollup/dist/rollup.js:189:14)
    at Promise.resolve.then.then.catch.err (/Users/xxxxx/projects/react/node_modules/rollup/dist/rollup.js:17630:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Command failed with exit code 1.
```

**Comment by gaearon** [comment]
Try reinstalling Java (not Node). This sounds like a corrupted setup to me. Thanks!

**Comment by anomalyjane** [comment]
Ah, figured it out--an out of date JDK on my machine was overruling an up to date JRE. Thanks!
