### ISSUE TITLE
"Invariant Violation: Unable to find node on an unmounted component" on `react-test-renderer`'s `renderer.create` when react package versions don't match

### ISSUE THREAD

**Issue by thisismydesign** [facebook/react#14641]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

```
import renderer from 'react-test-renderer';

const tree = renderer.create(<MyComponent />);
// => Invariant Violation: Unable to find node on an unmounted component
```

There're many people complaining about this issue in many different contexts. It seems to be coming from `findDOMNode`. The discussions are very vague and varied, e.g.
- https://stackoverflow.com/questions/52734483/reactdom-render-unable-to-find-node-on-an-unmounted-component-after-react-upgra
- https://github.com/Pomax/react-onclickoutside/issues/231
- https://github.com/airbnb/enzyme/issues/1411
- and the many more refernced issues

I'm not sure if all has the same root cause but many advise to upgrade/downgrade seemingly randomly. Also seemingly randomly it works for some and doesn't for others. Would be great to get a general recommendation / fix.

My use case:

`MyComponent` above is a simple `styled-component` (`styled.ul`).

The issue seem to be related to versions or version mismatches between `react`, `react-dom` and `react-test-renderer`. In my case, the error disappears locally by having `v16.5.0` install of all. However, the issue still occurs in GitLab CI. The only obvious difference is that the CI uses `yarn` and I use `npm`. **I was finally able to solve it in both environments by upgrading all three to the latest, `v16.7.0`.** Having any minor version mismatches seemed to reproduce the error locally.

Complete trace of error:
```
      at invariant (node_modules/react-dom/cjs/react-dom.development.js:55:15)
      at findCurrentFiberUsingSlowPath (node_modules/react-dom/cjs/react-dom.development.js:4125:30)
      at findCurrentHostFiber (node_modules/react-dom/cjs/react-dom.development.js:4233:23)
      at findHostInstanceWithWarning (node_modules/react-dom/cjs/react-dom.development.js:19454:21)
      at Object.findDOMNode (node_modules/react-dom/cjs/react-dom.development.js:19962:14)
      at StyledComponent.componentDidMount (node_modules/styled-components/dist/styled-components.cjs.js:1927:25)
      at commitLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:7019:22)
      at commitAllLifeCycles (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8234:7)
      at HTMLUnknownElement.callCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2312:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2362:16)
      at invokeGuardedCallback (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2411:31)
      at commitRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:8404:7)
      at completeRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9769:3)
      at performWorkOnRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9697:9)
      at performWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9601:7)
      at performSyncWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9573:3)
      at requestWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9461:5)
      at scheduleWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9256:5)
      at scheduleRootUpdate (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9865:3)
      at updateContainerAtExpirationTime (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9892:10)
      at updateContainer (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:9903:10)
      at Object.create (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:10428:5)
      at Object.<anonymous> (src/components/Selectors/DownShiftSelector/DownShiftSelector.test.js:45:44)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

**What is the expected behavior?**

no error

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

as described above

**Comment by thisismydesign** [comment]
@gaearon 

The usage in the issue comes from the seemingly widely used `jest-styled-components` package's most basic example: https://github.com/styled-components/jest-styled-components#usage

I'm not sure how would I use `ReactDOM.findDOMNode`. Can you give me an example? Tried the following:

```
import ReactDOM from 'react-dom';

ReactDOM.findDOMNode(<SelectorUl />);
// => Invariant Violation: Argument appears to not be a ReactComponent. Keys: $$typeof,type,key,ref,props,_owner,_store
```

**Comment by thisismydesign** [comment]
So I should take this to them I suppose. Thanks. For the record, as mentioned in the issue, it works with the right combination of dependencies.
