### ISSUE TITLE
[react-reconciler] schedulePassiveEffects is not a function when used with 16.8.1

### ISSUE THREAD

**Issue by natew** [facebook/react#14814]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

```
schedulePassiveEffects is not a function
 TypeError: schedulePassiveEffects is not a function
    at commitRoot (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:10543:35)
    at completeRoot (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11987:3)
    at performWorkOnRoot (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11916:9)
    at performWork (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11824:7)
    at performSyncWork (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11798:3)
    at requestWork (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11667:5)
    at scheduleWork (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:11462:5)
    at scheduleRootUpdate (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:12144:3)
    at updateContainerAtExpirationTime (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:12172:10)
    at Object.updateContainer (/Users/nw/projects/motion/orbit/packages/reactron/node_modules/react-reconciler/cjs/react-reconciler.development.js:12229:10)
    at Object.<anonymous> (/Users/nw/projects/motion/orbit/packages/reactron/src/renderer/render.js:14:12)
    at Generator.next (<anonymous>)
    at /Users/nw/projects/motion/orbit/packages/reactron/_/renderer/render.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/nw/projects/motion/orbit/packages/reactron/_/renderer/render.js:3:12)
    at Object.render (/Users/nw/projects/motion/orbit/packages/reactron/_/renderer/render.js:18:12)
    at Object.<anonymous> (/Users/nw/projects/motion/orbit/app/orbit-electron/src/main.tsx:65:7)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/nw/projects/motion/orbit/app/orbit-electron/_/main.js:4:58)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

I'm using react/react-dom 16.8.1 and react-reconciler 0.19.1. I have a custom renderer which then throw this error, which used to work with previous 16.7 and 16.8 alpha.

When I log out the $$hostConfig to see why schedulePassiveEffects isn't there, I see:

```
$$$hostConfig { now: [Function: now],
  supportsMutation: true,
  appendInitialChild: [Function: appendInitialChild],
  createInstance: [Function: createInstance],
  createTextInstance: [Function: createTextInstance],
  finalizeInitialChildren: [Function: finalizeInitialChildren],
  getPublicInstance: [Function: getPublicInstance],
  prepareUpdate: [Function: prepareUpdate],
  prepareForCommit: [Function: noop],
  resetAfterCommit: [Function: noop],
  resetTextContent: [Function: noop],
  getRootHostContext: [Function: getRootHostContext],
  getChildHostContext: [Function: getChildHostContext],
  shouldSetTextContent: [Function: shouldSetTextContent],
  appendChild: [Function: appendChild],
  appendChildToContainer: [Function: appendChildToContainer],
  removeChild: [Function: removeChild],
  removeChildFromContainer: [Function: removeChildFromContainer],
  commitUpdate: [Function: commitUpdate],
  commitTextUpdate: [Function: commitTextUpdate] }
```

I did a few sanity checks to be sure I didn't have a bad version, and cleaned node_modules re-installed.

---

I understand the config seems to have changed, and am updating it now. Just wanted to open this both for google-ability, and to sanity check in case I missed something.

**Comment by sophiebits** [comment]
That sounds correct. Looks like schedulePassiveEffects was introduced in 0.19.0 which (like all 0.x.0 releases) may contain breaking changes.

**Comment by natew** [comment]
For the record just adding this worked:

```
// above config
let scheduledCallback = null
let scheduledCallbackTimeout = -1
let scheduledPassiveCallback = null
let elapsedTimeInMs = 0

// inside config
  schedulePassiveEffects(callback) {
    if (scheduledCallback) {
      throw new Error(
        'Scheduling a callback twice is excessive. Instead, keep track of ' +
          'whether the callback has already been scheduled.',
      )
    }
    scheduledPassiveCallback = callback
  },

  cancelPassiveEffects() {
    if (scheduledPassiveCallback === null) {
      throw new Error('No passive effects callback is scheduled.')
    }
    scheduledPassiveCallback = null
  },

  scheduleDeferredCallback(callback, options) {
    if (scheduledCallback) {
      throw new Error(
        'Scheduling a callback twice is excessive. Instead, keep track of ' +
          'whether the callback has already been scheduled.',
      )
    }
    scheduledCallback = callback
    if (typeof options === 'object' && options !== null && typeof options.timeout === 'number') {
      const newTimeout = options.timeout
      if (scheduledCallbackTimeout === -1 || scheduledCallbackTimeout > newTimeout) {
        scheduledCallbackTimeout = elapsedTimeInMs + newTimeout
      }
    }
    return 0
  },
```

**Comment by sophiebits** [comment]
You'll likely want to call scheduledPassiveCallback sometime (looks like you're just storing it) or else useEffect won't get called when you expect.

**Comment by stormslowly** [comment]
> You'll likely want to call scheduledPassiveCallback sometime (looks like you're just storing it) or else useEffect won't get called when you expect.

is there any recommended implementation for `scheduledPassiveCallback`
I am stuck at the same problem.

**Comment by ntower** [comment]
The fix for me was to use `unstable_scheduleCallback` and `unstable_cancelCallback` from the scheduler package:

```
import * as scheduler form 'scheduler';

// in the host config...
{
  scheduleDeferredCallback: scheduler.unstable_scheduleCallback,
  cancelDeferredCallback: scheduler.unstable_cancelCallback,
  schedulePassiveEffects: scheduler.unstable_scheduleCallback,
  cancelPassiveEffects: scheduler.unstable_cancelCallback,
 // etc
}
```
It appears that in React 16.9 the schedulePassiveEffects and cancelPassive effects will no longer be a part of host config, so expect to remove these properties eventually. See the commit message on this: https://github.com/facebook/react/commit/1e3b6192b54df20ac117a2af56afbe00ac9487b7
