### ISSUE TITLE
eslint-plugin-react-hooks - breaks build

### ISSUE THREAD

**Issue by Mykybo** [facebook/react#15149]
After adding `eslint-plugin-react-hooks` eslint plugin to my project, it broke builds of the application in openshift. The app builds fine on local. Could it be caused by different node versions or something like that?

The error:

```
Module build failed (from ./node_modules/eslint-loader/index.js):
--
  | TypeError: Object.entries is not a function
  | at fastFindReferenceWithParent (/opt/app-root/src/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:1885:36)
  | at gatherDependenciesRecursively (/opt/app-root/src/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:1007:33)
  | at visitFunctionExpression (/opt/app-root/src/node_modules/eslint-plugin-react-hooks/cjs/eslint-plugin-react-hooks.development.js:985:7)
```

**Comment by gaearon** [comment]
`Object.entries` is supported since Node 7.
This ESLint plugin doesn't support earlier Node versions.
