### ISSUE TITLE
Trying to render react native component using context in jest test environment fails

### ISSUE THREAD

**Issue by yaizudamashii** [facebook/react#15422]
**Do you want to request a *feature* or report a *bug*?**
Report a bug

**What is the current behavior?**
```
renderer.create( //Invariant Violation: Element type
            <ThemeContext.Provider>
                <ThemeContext.Provider>
                    {(theme) => <MyText>abc</MyText>}
                </ThemeContext.Provider>
            </ThemeContext.Provider>
        );
```
produces Invariant Violation

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**

```
// ThemeContext.js
import React from 'react';

export const ThemeContext = React.createContext(
    { color: 'white' }
);
```

```
// MyText.js
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { Text } from 'react-native';

export class MyText extends PureComponent {
    static propTypes = {
        children: PropTypes.node.isRequired
    };

    static defaultProps = {};

    render() {
        let text = this.props.children;
        return (
            <Text>
                {text}
            </Text>
        );
    }
};
```

```
// MyText.test.js
import React from 'react';
import { MyText } from "../MyText";
import { ThemeContext } from '../ThemeContext';

describe('MyText', () => {

    it('should render component', () => {
        const wrapper = renderer.create(
            <ThemeContext.Provider value={mobileColorThemes.standard}>
                <ThemeContext.Consumer>
                    {(theme) => <MyText>abc</MyText>}
                </ThemeContext.Consumer>
            </ThemeContext.Provider>
        );
        expect(wrapper).toMatchSnapshot();
    });
});
```

But when I run the test file with jest,
`jest text/__tests__/MyText.test.js`

I get the following error
```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

      at invariant (node_modules/fbjs/lib/invariant.js:42:15)
      at createFiberFromElementType (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1933:5)
      at createFiberFromElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:1878:15)
      at reconcileSingleElement (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3334:19)
      at reconcileChildFibers (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:3433:35)
      at reconcileChildrenAtPriority (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4091:30)
      at reconcileChildren (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4074:5)
      at updateHostRoot (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4268:9)
      at beginWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:4563:16)
      at performUnitOfWork (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:6529:16)...
```

**What is the expected behavior?**
The component is rendered, having provided context and then consuming context

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using jest 24.1.0, react-native 0.56, react-test-renderer 16.0.0, react 16.4.1

**Comment by yaizudamashii** [comment]
Ok I was just told on SO that react and react-test-renderer must have the same version, and context support was introduced in react-test-renderer in 16.3.0.  Closing
