### ISSUE TITLE
Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.

### ISSUE THREAD

**Issue by TidyIQ** [facebook/react#15441]
**NOT A DUPLICATE**

**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

package.json dependencies:
```
"dependencies": {
    "@material-ui/core": "^4.0.0-alpha.8",
    "@material-ui/icons": "^4.0.0-alpha.8",
    "@material-ui/styles": "^4.0.0-alpha.8",
    "@zeit/next-typescript": "^1.1.1",
    "next": "^8.1.0",
    "react": "^16.8.6",
    "react-dom": "^16.8.6"
  },
  "devDependencies": {
    "@types/next": "^8.0.3",
    "@types/react": "^16.8.13",
    "@types/react-dom": "^16.8.4",
    "@types/styled-jsx": "^2.2.8",
    "typescript": "^3.4.3"
  }
```
index.tsx: 

```
import React, { useContext } from "react";
import { Store } from "../state/store";
import { initialState } from "../state/reducers";
import { toggleDrawer } from "../state/actions";

export default function Index() {
  // Get state contexts
  const { state, dispatch } = useContext(Store);
  const onClick = () => {
    const drawerState: boolean = state.drawers.navmenu;
    dispatch(toggleDrawer("navmenu", !drawerState));
  };
  const navmenu: string = initialState.drawers.navmenu.toString();
  return (
    <div>
      <p>Value: {navmenu}</p>
      <button onClick={onClick}>Change</button>
    </div>
  );
}
```

Error output:
```
[ error ] { Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component.
```

**What is the expected behavior?**

useContext is being called within the body of a function component. There should be no error. This is literally the only component in the entire app. I am not breaking any of:

1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app

**Comment by eps1lon** [comment]
Do you have a full stack trace?

**Comment by TidyIQ** [comment]
```
{ Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at invariant (C:\...\Website\node_modules\react\cjs\react.development.js:88:15)
    at resolveDispatcher (C:\...\Website\node_modules\react\cjs\react.development.js:1436:28)
    at useReducer (C:\...\Website\node_modules\react\cjs\react.development.js:1466:20)
    at createStore (C:\...\Website\.next\server\static\development\pages\_app.js:4244:77)
    at Module../state/store.tsx (C:\...\Website\.next\server\static\development\pages\_app.js:4270:73)
    at __webpack_require__ (C:\...\Website\.next\server\static\development\pages\_app.js:23:31)
    at Module../pages/_app.tsx (C:\...\Website\.next\server\static\development\pages\_app.js:4049:71)
    at __webpack_require__ (C:\...\Website\.next\server\static\development\pages\_app.js:23:31)
    at Object.0 (C:\...\Website\.next\server\static\development\pages\_app.js:4282:18)
    at __webpack_require__ (C:\...\Website\.next\server\static\development\pages\_app.js:23:31)
    at C:\...\Website\.next\server\static\development\pages\_app.js:91:18
    at Object.<anonymous> (C:\...\Website\.next\server\static\development\pages\_app.js:94:10)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12) name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by Soontorn2499** [comment]
_Sent from my Nokia 6 using [FastHub](https://play.google.com/store/apps/details?id=co
# 
## m.fastaccess.github)_

**Comment by eps1lon** [comment]
@TidyIQ Looks like you're calling a hook inside `createStore`. I suspect you're doing something like `export default createStore();` from `state/store.tsx`.

Could you include the source for `state/store.tsx`

**Comment by TidyIQ** [comment]
```
import React, { useReducer, createContext } from "react";
import reducer, { IF_State, initialState } from "./reducers";

// Create store
const createStore = (reducer: any, initialState: IF_State) => {
  const [state, dispatch]: any = useReducer(reducer, initialState);
  return { state, dispatch };
};

// Create provider
const Provider = ({ children }: any) => {
  const store = createStore(reducer, initialState);
  return <Store.Provider value={store}>{children}</Store.Provider>;
};

// Create context
const Store = createContext(createStore(reducer, initialState));

export { Store, Provider };
```

**Comment by TidyIQ** [comment]
OK so I changed const Store to:

```
// Create context
const defaultContext: any = {};
const Store = createContext(defaultContext);
```

And now it works. I don't need a default context as my entire app is wrapped in a provider (I'm basically mimicking Redux but using react hooks) however I can't leave it blank as I get typescript errors. I guess I'll just leave it as an empty object since the default value will never be used anyway.

**Comment by eps1lon** [comment]
@TidyIQ Guess we can close this?

**Comment by TidyIQ** [comment]
Yep, thanks for your help
