### ISSUE TITLE
Invariant violation: it is not supported to run the profiling version of a renderer

### ISSUE THREAD

**Issue by Arjanvanmaren** [facebook/react#16263]
I have an issue with husky pre push. I have a react-native application. When I run the tests via a commandline the tests all succeed. I also have gitkraken which gives me this error when I trigger the pre push event of husky which runs my tests. 

How can I fix this?
                                                                      
`FAIL src/domains/dashboard/screens/index.spec.tsx
  b   Test suite failed to run

 Invariant Violation: It is not supported to run the profiling version of a renderer (for example, `react-dom/profiling`) without also replacing the `scheduler/tracing` module with `scheduler/tracing-profiling`. Your bundler might have a setting for aliasing both modules. Learn more at http://fb.me/react-profiling

      15 | import styled from '@app/theme'
      16 | 
         |                           ^
      18 |   flex: 1;
      19 |   justify-content: center;
      20 |   align-items: center;

      at ReactError (node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:38:15)
      at ReactError (node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:5444:13)
      at node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:5437:3
      at Object.<anonymous> (node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:16:3)
      at Object.require (node_modules/react-native/Libraries/Renderer/shims/ReactNative.js:18:17)
      at Object.requireActual [as user:/Users/arjan.vanmaren/Workspaces/KNLTB-app/node_modules/react-native/Libraries/Renderer/shims/ReactNative.js:] (node_modules/react-native/jest/setup.js:86:30)
      at Object.require (node_modules/react-native/Libraries/Components/View/ViewNativeComponent.js:13:21)
      at Object.require (node_modules/react-native/Libraries/Components/View/View.js:14:29)
      at requireActual (node_modules/react-native/jest/mockComponent.js:13:30)
      at Object.mockComponent [as user:/Users/arjan.vanmaren/Workspaces/KNLTB-app/node_modules/react-native/Libraries/Components/View/View.js:] (node_modules/react-native/jest/setup.js:53:5)
      at Object.require [as View] (node_modules/react-native/Libraries/react-native/react-native-implementation.js:159:12)
      at Function.get [as View] (node_modules/styled-components/native/dist/styled-components.native.cjs.js:6512:41)
      at Object.View (src/domains/dashboard/screens/index.tsx:17:27)
      at Object.<anonymous> (src/domains/dashboard/screens/index.spec.tsx:2:1)
`

**Comment by gaearon** [comment]
Sorry, this doesn't have enough details to help. You probably want to ask this in some RN channel.

**Comment by tobiaseisenschenk** [comment]
This seems to be a GitKraken issue since I could bypass the exact problem described above by simply using the command line instead.

**Comment by serzmerz** [comment]
Any ideas on how to fix it in gitkraken?

**Comment by jscostaBR** [comment]
I have solved this problem by doing the commit through VSCode source code control
