### ISSUE TITLE
[dev-experience] 16.9.0 exception text if loading multiple versions of react-dom is misleading

### ISSUE THREAD

**Issue by wizzard0** [facebook/react#16360]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
after updating 16.8.6>16.9.0 root functional component throws exception "Invariant Violation: Invalid hook call".

In fact, exception was caused by loading multiple versions of react-dom in child components.

The exception text is misleading, would be great to crash earlier (eg at the import stage) with appropriate message

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Your bug will get fixed much faster if we can run your code and it doesn't have dependencies other than React. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
Add multiple versions of react-dom as deps from multiple referenced npm packages; not easily reproduceable w/fiddle

**What is the expected behavior?**
Error on import, not on render, ideally including version numbers

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
react-dom 16.9.0+16.8.4 in this case; all browsers

**Comment by wizzard0** [comment]
upd: reduced to
```
export default function App(): JSX.Element {
    useEffect(() => {
        console.log('started', new Date());
    }, []);

    return (<div />);
}
```
->
```
The above error occurred in the <App> component:
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20266
    throw error;
    ^

Invariant Violation: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
    at C:\dev\multi\instance-tdev\node_modules\engine\node_modules\react\cjs\react.development.js:1533:26
    at resolveDispatcher (C:\dev\multi\instance-tdev\node_modules\engine\node_modules\react\cjs\react.development.js:1536:5)
    at Object.useEffect (C:\dev\multi\instance-tdev\node_modules\engine\node_modules\react\cjs\react.development.js:1576:20)
    at App (C:\dev\multi\instance-tdev\node_modules\engine\components\App.js:16:13)
    at renderWithHooks (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:12892:18)
    at mountIndeterminateComponent (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:14974:13)
    at beginWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:15579:16)
    at performUnitOfWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:19266:12)
    at workLoop (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:19306:24)
    at renderRoot (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:19389:7)
    at performWorkOnRoot (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20296:7)
    at performWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20208:7)
    at performSyncWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20182:3)
    at requestWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20051:5)
    at scheduleWork (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:19865:5)
    at scheduleRootUpdate (C:\dev\multi\instance-tdev\node_modules\react-dom\cjs\react-dom.development.js:20526:3)
```

**Comment by threepointone** [comment]
The exception text says “You might have mismatching versions of React and the renderer (such as React DOM)” which is what the actual issue was, could you explain how that was misleading?

If you’d like the error on import/bundling, this is an issue you should file with the bundler you’re using. It appears you’d like webpack/parcel to error when this happens.

**Comment by wizzard0** [comment]
> could you explain how that was misleading?
1) my app specified react 16.9 & react-dom 16.9 in package.json, these are definitely matching versions :) and the offending component was a part of another component we were using, so it took time to diagnose that another version of react-dom was loaded *in addition* to the version I specified. 

2) I remember React was advertised to be compatible with another frameworks, like being embedded in another app, or embedding non-React components; is this no longer the case?

We're wrapping a non-React component that ships already bundled & minified, I didn't even knew they had parts written in React under the hood too.

**Comment by gaearon** [comment]
There are two ways you can fix this:

1. Make sure you have just one copy of `react` and `react-dom` on the page. That's the best solution for your users.

2. If you for some reason can't avoid duplicating them (very bad for your users!), then you need to ensure these two copies are fully isolated from each other.

The particular broken case (as described [here](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react)) is when `react-dom` is "seeing" different `react` than the components rendered with that `react-dom` copy. If you can't avoid the duplication, you need to make sure that in one app you use only one `react-dom` + `react`, and in another app, you use the other `react-dom` + `react`, and that you don't try to `ReactDOM.render` one app's components with another app's `ReactDOM`. Instead, the inner component could export a vanilla JS API that contains its own `ReactDOM.render` call inside.

Hope this helps.

**Comment by wizzard0** [comment]
oh, so the issue is with mismatched *instances* of module, not *versions*! thanks, now it all makes sense.
