### ISSUE TITLE
Error: "Could not find commit data for root "34" and commit 21"

### ISSUE THREAD

**Issue by fozcodes** [facebook/react#16427]
I tried to select a different component from the dropdown

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16552)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:292537)
    at ml (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:292772)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in ml
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by bvaughn** [comment]
Can you be a little more detailed? What dropdown?

**Comment by bvaughn** [comment]
Dup of #16414 so closing, but please do share more repro info if you can
