### ISSUE TITLE
Error: "Could not find commit data for root "1" and commit null"

### ISSUE THREAD

**Issue by raibima** [facebook/react#16441]
**Repro:** https://codesandbox.io/s/xenodochial-lamarr-q71wt

**Steps:**
1. Profile
2. Select a component from the flame graph (important)
3. Click settings
4. Toggle "hide commits below ms" (In my case, it's 100ms)

**Demo:**
![repro-2](https://user-images.githubusercontent.com/4465644/63220458-49529880-c1b2-11e9-9bd4-aeb059af8b9b.gif)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.2-2bcc6c6

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16552)
    at pl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:293513)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)
    at kt (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25092)

Component stack: in pl
    in div
    in ml
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ua
    in le
    in ve
    in ko
    in Fl

**Comment by bvaughn** [comment]
Thanks for the detailed repro steps!

**Comment by bvaughn** [comment]
Fixed via https://github.com/bvaughn/react-devtools-experimental/commit/4697f5b37967b85b2c844044aeebb5b1a740875d
