### ISSUE TITLE
Error: "Could not find commit data for root "1896" and commit 16"

### ISSUE THREAD

**Issue by grazlucinskas** [facebook/react#16506]
PLEASE INCLUDE REPRO INSTRUCTIONS AND EXAMPLE CODE

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.0.4-3c6a219

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:11:16721)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:293207)
    at pl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:293442)
    at Ha (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:55890)
    at bi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:62939)
    at Xl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:99535)
    at Hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:84255)
    at Fl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:81285)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43:25363
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56:4368)

Component stack: in pl
    in div
    in div
    in Or
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Ha
    in le
    in ve
    in ko
    in Ul

**Comment by bvaughn** [comment]
Repro instructions would be helpful! 😄 🙇
