### ISSUE TITLE
React DevTools downgrade not working for Chrome.

### ISSUE THREAD

**Issue by ztasre** [facebook/react#16677]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
The following command fails
```
yarn run test:chrome 
```
error message:
```                                                                                
yarn run v1.17.3
$ node ./shells/chrome/test
internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:112:11)
    at normalizeSpawnArguments (child_process.js:398:3)
    at spawn (child_process.js:534:16)
    at launchChrome (/home/andrei/src/react-devtools/node_modules/chrome-launch/index.js:27:12)
    at Object.<anonymous> (/home/andrei/src/react-devtools/shells/chrome/test.js:9:1)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
error Command failed with exit code 1.
```

**What is the expected behavior?**
Launch a new browser window. The following command works
```
yarn run test:firefox 
```

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**
Using Version 76.0.3809.100 (Official Build) (64-bit), /usr/bin/google-chrome-stable is aliased to chrome.

Any help is appreciated, we're running a old version of React at work and upgrading it would be nontrivial. Hence I need the old version of the React DevTools.

**Comment by bvaughn** [comment]
You aren't really meant to use the `yarn test:chrome` command to install the previous extension version. It's meant to enable you to quickly test a local build.

If you want to "downgrade" the old extension:
1. Run the build script
2. Open `about:extensions`
3. Click "Load Unpacked"
4. Navigate to `react-devtools/shells/chrome/build/unpacked`

**Comment by ztasre** [comment]
Thanks! Looks like it works.
