### ISSUE TITLE
Compile error `react-refresh/babel` 0.4.0

### ISSUE THREAD

**Issue by natew** [facebook/react#16686]
Using `react-refresh/babel` 0.4.0 is giving me this error on a large number of files:

```
ERROR in ../orbit-app/src/hooks/useStores.ts
Module build failed (from ../node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property '0' of undefined
    at Function.get (/Users/nw/projects/motion/orbit/node_modules/@babel/traverse/lib/path/index.js:115:33)
    at NodePath.unshiftContainer (/Users/nw/projects/motion/orbit/node_modules/@babel/traverse/lib/path/modification.js:191:31)
    at PluginPass.exit (/Users/nw/projects/motion/orbit/node_modules/react-refresh/cjs/react-refresh-babel.development.js:546:28)
```

I narrowed down that file to the simplest thing that causes it:

```
import { useContext } from 'react'

export default () => useContext()
```

_Originally posted by @natew in https://github.com/facebook/react/issues/16604#issuecomment-528708174_

**Comment by gaearon** [comment]
Fixed in 0.4.1
