### ISSUE TITLE
Eclipse running js : Uncaught SyntaxError: Unexpected identifier 

### ISSUE THREAD

**Issue by reynoldsliu** [facebook/react#16729]
D:\javaworkspace\APP_TEST\main.js:1
import Vue from 'vue'
       ^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

Newbie in the js. Someone tell me to put in the availablr .jar, but I dont understand how to adjust the environment of my code.
By the way, it's the code that I copy from net . I try to learn a simple app but after copy it confuse me.

**Comment by gaearon** [comment]
Hi! We use the issue tracker for bug reports and feature requests in React.

If you have a question, please check our community support resources:
https://facebook.github.io/react/community/support.html
