### ISSUE TITLE
Error: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by wix-fed-exam** [facebook/react#17403]
Describe what you were doing when the bug occurred:
1. removed a filter for <Suspense /> compponents
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.2.0-a8b8ffb89

Call stack: at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:155183)
    at e.getFlamegraphChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:155590)
    at dl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:312205)
    at fi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59263)
    at Hi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:66573)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104884)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89467)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89392)
    at pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:86341)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45721

Component stack: in dl
    in div
    in div
    in div
    in _o
    in Unknown
    in n
    in Unknown
    in div
    in div
    in zi
    in Ge
    in un
    in ba
    in Rc

**Comment by embeddedt** [comment]
There is not much information for anyone to work with here.

* What is the exact issue? Give a detailed description - saying that there was an error is not enough information.
* What have you tried already/what have you diagnosed so far?
* A code sample is usually extremely helpful.

**Comment by bvaughn** [comment]
This issue is not actionable. Given no response for a week, I'm closing it.
