### ISSUE TITLE
Error: "Could not find node with id "57" in commit tree"

### ISSUE THREAD

**Issue by ngoxuanhien** [facebook/react#17749]
I'm tried to use *Profilter tool on Chrome browser, but i got this error when i review the rank of list Elements.  I don't know what is that ?

DevTools version: 4.2.1-3816ae7c3

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157108
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157054)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:157577)
    at vl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:314907)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59907)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:107381)
    at Lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92715)
    at Pc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:92640)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:89544)

Component stack: in vl
    in div
    in div
    in div
    in wo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Li
    in $e
    in dn
    in Ca
    in Pc

**Comment by bvaughn** [comment]
Sorry for the inconvenience here. This is a known issue (#16446) but I don't yet know the underlying cause or fix.

I'm going to close this as a duplicate. If you'd be interested in lending a hand on #16446, I'd welcome the help. Otherwise I'll hopefully fix it eventually :smile:

**Comment by ngoxuanhien** [comment]
> Sorry for the inconvenience here. This is a known issue (#16446) but I don't yet know the underlying cause or fix.
> 
> I'm going to close this as a duplicate. If you'd be interested in lending a hand on #16446, I'd welcome the help. Otherwise I'll hopefully fix it eventually 😄

ok thank you :D
