### ISSUE TITLE
Error: "Could not find node with id "2153" in commit tree"

### ISSUE THREAD

**Issue by cristinamarin22** [facebook/react#17872]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.4.0-f749045a5

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159909
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:159855)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:160378)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:323092)
    at ei (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58864)
    at yl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:106932)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99474)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99399)
    at fc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96173)

Component stack: in Sl
    in div
    in div
    in div
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by ecreeth** [comment]
https://github.com/facebook/react/issues/17802#issuecomment-572681518

**Comment by bvaughn** [comment]
4.4.0-f749045a5 should have the fix mentioned in that comment. So it seems like this bug is still around, just firing less frequently.

@cristinamarin22 Can you fill in the details on this part of the issue template?

> Describe what you were doing when the bug occurred:
> 1.
> 2.
> 3.

**Comment by bvaughn** [comment]
I landed PR #18378 this morning. It fixes a source of problem that I think might be responsible for this, and some of the other infrequent Profiler errors. I'll release an update to the Chrome/Firefox/Edge stores today.
