### ISSUE TITLE
Error: "Object.entries is not a function"

### ISSUE THREAD

**Issue by kml1326** [facebook/react#17986]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.4.0-f749045a5

Call stack: at Ka (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:281424)
    at ei (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58864)
    at yl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:106932)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99474)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99399)
    at fc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96173)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45937
    at n.unstable_runWithPriority (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:3676)
    at qo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45647)
    at Xo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45883)

Component stack: in Ka
    in div
    in bi
    in div
    in Ai
    in Suspense
    in ei
    in div
    in div
    in la
    in Ur
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by M-Izadmehr** [comment]
What is the version of your browser?
Because I think `object.entries` is supported from quite some time (Chrome v54/ Firefox 47).

Also, @bvaughn, I am curious about [/packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js#L209](https://github.com/facebook/react/blob/master/packages/react-devtools-shared/src/devtools/views/Components/KeyValue.js#L209), why is it important to use `object.entries`, because I think `Object.keys/Object.values/Object.entries` neglect the the symbolic properties?

**Comment by bvaughn** [comment]
This is a confusing error report, without any context.

Chrome stable is currently v79, and `Object.entries` has been supported since v54. Similarly, Firefox stable is v72 and has had support since v47. Those are the only two browsers we officially support at the moment. 

@kml1326 Please provide a little more context on this! :smile:

**Comment by threepointone** [comment]
Closing this since it's likely it wasn't a devtools issue.
