### ISSUE TITLE
Error: "Could not find commit data for root "1069" and commit 4"

### ISSUE THREAD

**Issue by khanhhua** [facebook/react#17980]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.4.0-f749045a5

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166027)
    at m (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:340715)
    at Cc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:340932)
    at ei (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58864)
    at Mi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:67500)
    at yl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108161)
    at kc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99474)
    at wc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99399)
    at fc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96173)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45937

Component stack: in Cc
    in div
    in div
    in vo
    in Unknown
    in n
    in Unknown
    in div
    in div
    in Qi
    in Ve
    in nn
    in Da
    in Yc

**Comment by bvaughn** [comment]
> Describe what you were doing when the bug occurred

Can you provide a little more info on this than the default template? Are you able to reproduce it? If so, can you share how?

**Comment by bvaughn** [comment]
No response here so I'm closing this.

Future info about this bug can be added to #18010
