### ISSUE TITLE
Error: "Cannot read property '2' of undefined"

### ISSUE THREAD

**Issue by lmajowka** [facebook/react#18246]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.5.0-355970aa4

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:160295)
    at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:160015)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162825)
    at ec (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:337472)
    at ti (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58696)
    at qi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:67715)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108833)
    at jc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:100072)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99997)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99862)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment]
Without any description or context, this isn't really actionable. I'm going to close it, but I'll re-open it if you fill in the "*Describe what you were doing when the bug occurred*" section.
