### ISSUE TITLE
`npm install` fails on the react repo on PowerPC

### ISSUE THREAD

**Issue by sarveshtamba** [facebook/react#18275]
Facing the following error while running npm test on the react repo v0.10.0 on PowerPC using node v12:-
```
bash-4.2# npm install
npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code ETARGET
npm ERR! notarget No matching version found for esprima-six@0.0.3.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-03-11T11_59_22_496Z-debug.log
```

I tried using lower node versions, however it does not help much. Any inputs on resolving this would be highly appreciated.

**Comment by bvaughn** [comment]
This repository uses a Yarn lockfile. Installation of dependencies should be done using Yarn, rather than NPM:

```
yarn install
```

**Comment by sarveshtamba** [comment]
@bvaughn Used `yarn install` command to build. However the build has dependency on phantomjs.

```
bash-4.2# yarn install
yarn install v1.22.0
info No lockfile found.
warning npm-shrinkwrap.json found. This will not be updated or respected. See https://yarnpkg.com/en/docs/migrating-from-npm for more information.
[1/5] Validating package.json...
[2/5] Resolving packages...
...
...
...
[3/5] Fetching packages...
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[1/2] ⢀ microtime
error /home/tester/react/node_modules/phantomjs: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /home/tester/react/node_modules/phantomjs
Output:
Considering PhantomJS found at /home/tester/phantomjs
Found PhantomJS at /home/tester/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.1 @ /home/tester/phantomjs.
Unexpected platform or architecture: linux/ppc64
It seems there is no binary available for your platform/architecture
Try to install PhantomJS globally

bash-4.2# echo $?
1
```
Is it possible to use PhantomJS v2.1.1 for this repo?

**Comment by bvaughn** [comment]
Nothing in the React repo references `phantomjs` (not even in the Yarn lockfile as an indirect dependency).

**Comment by sarveshtamba** [comment]
@bvaughn I switched to node v10.19.0 (earlier, I was using node v12.16.1, not sure if this could be the problem) and now the build looks out for `electron`:
```
[4/4] Building fresh packages...
[-/12] ⠂ waiting...
[-/12] ⠂ waiting...
[3/12] ⠂ dtrace-provider
[-/12] ⠂ waiting...
error /root/react/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /root/react/node_modules/electron
Output:
Downloading tmp-1026-0-electron-v5.0.9-linux-ppc64.zip
Error: GET https://github.com/electron/electron/releases/download/v5.0.9/electron-v5.0.9-linux-ppc64.zip returned 404
/root/react/node_modules/electron/install.js:49
  throw err
  ^

Error: Failed to find Electron v5.0.9 for linux-ppc64 at https://github.com/electron/electron/releases/download/v5.0.9/electron-v5.0.9-linux-ppc64.zip
    at Request.<anonymous> (/root/react/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:198:13)
    at Request.onRequestResponse (/root/react/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:198:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)




bash-4.2# yarn why electron
yarn why v1.22.0
[1/4] Why do we have the module "electron"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "electron@5.0.9"
info Reasons this module exists
   - "_project_#react-devtools" depends on it
   - Hoisted from "_project_#react-devtools#electron"
info Disk size without dependencies: "4.38MB"
info Disk size with unique dependencies: "10.94MB"
info Disk size with transitive dependencies: "112.75MB"
info Number of shared dependencies: 84
Done in 2.32s.
bash-4.2# yarn why phantomjs
yarn why v1.22.0
[1/4] Why do we have the module "phantomjs"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
error We couldn't find a match!
Done in 2.01s.
bash-4.2# node -v
v10.19.0
```

**Comment by bvaughn** [comment]
This looks like a network error:
```
Downloading tmp-1026-0-electron-v5.0.9-linux-ppc64.zip
Error: GET https://github.com/electron/electron/releases/download/v5.0.9/electron-v5.0.9-linux-ppc64.zip returned 404
/root/react/node_modules/electron/install.js:49
  throw err
  ^
```
Nothing we can help with. Try again? Maybe GitHub servers were down.

**Comment by sarveshtamba** [comment]
@bvaughn I checked on the electron release page and found that electron v5.0.9 is not supported for ppc64/PowerPC - https://github.com/electron/electron/releases/tag/v5.0.9

Any workaround possible?

**Comment by bvaughn** [comment]
I guess you could edit [this `package.json`](https://github.com/facebook/react/blob/355970aa4b7f96ec487e29083ee8fbc87bc99fdc/packages/react-devtools/package.json) to move electron from `dependencies` into an `optionalDependencies` block to avoid the failed download from blocking the install.

Updating our build scripts to support older CPU makes like PowerPC isn't a big priority for us at the moment though, sorry. :frown:

**Comment by sarveshtamba** [comment]
> I guess you could edit [this `package.json`](https://github.com/facebook/react/blob/355970aa4b7f96ec487e29083ee8fbc87bc99fdc/packages/react-devtools/package.json) to move electron from `dependencies` into an `optionalDependencies` block to avoid the failed download from blocking the install.
> 
> Updating our build scripts to support older CPU makes like PowerPC isn't a big priority for us at the moment though, sorry. :frown:

Facing the same electron related 404 download error if I edit [this package.json](https://github.com/facebook/react/blob/355970aa4b7f96ec487e29083ee8fbc87bc99fdc/packages/react-devtools/package.json) to move electron from `dependencies` into an `optionalDependencies`

**Comment by bvaughn** [comment]
@sarveshtamba Just remove the dependency entirely then?

Sorry. I can't really help much here.

**Comment by sarveshtamba** [comment]
@bvaughn I just removed the dependency entirely and ran yarn && yarn test and looks like it passed successfully. Can you please check below output and confirm so that I can raise a PR for the changes and merge the same in the master? TIA.
```
bash-4.2# git diff
diff --git a/packages/react-devtools/package.json b/packages/react-devtools/package.json
index c6839c5..808f6ea 100644
--- a/packages/react-devtools/package.json
+++ b/packages/react-devtools/package.json
@@ -24,7 +24,6 @@
   },
   "dependencies": {
     "cross-spawn": "^5.0.1",
-    "electron": "^5.0.0",
     "ip": "^1.1.4",
     "minimist": "^1.2.0",
     "react-devtools-core": "4.5.0",

bash-4.2# yarn
yarn install v1.22.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-linux@20200112.0.0: The CPU architecture "ppc64" is incompatible with this module.
info "google-closure-compiler-linux@20200112.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-osx@20200112.0.0: The platform "linux" is incompatible with this module.
info "google-closure-compiler-osx@20200112.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-osx@20200112.0.0: The CPU architecture "ppc64" is incompatible with this module.
info google-closure-compiler-windows@20200112.0.0: The platform "linux" is incompatible with this module.
info "google-closure-compiler-windows@20200112.0.0" is an optional dependency and failed compatibility check. Excluding it from installation.
info google-closure-compiler-windows@20200112.0.0: The CPU architecture "ppc64" is incompatible with this module.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.0.7: The platform "linux" is incompatible with this module.
info "fsevents@2.0.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "babel-eslint@^6.1.2".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint@^3.0.0".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint-plugin-babel@^3.3.0".
warning " > eslint-config-fbjs@1.1.1" has incorrect peer dependency "eslint-plugin-react@^5.2.2".
warning " > eslint-plugin-react@6.10.3" has incorrect peer dependency "eslint@^2.0.0 || ^3.0.0".
warning " > jest-mock-scheduler@0.1.0" has incorrect peer dependency "scheduler@^0.15.0".
warning "workspace-aggregator-3ff9205f-d122-45cb-b735-6a7a71916815 > react-devtools-shared > react-dom-15@15.6.2" has incorrect peer dependency "react@^15.6.2".
[4/4] Building fresh packages...
success Saved lockfile.
$ node node_modules/fbjs-scripts/node/check-dev-engines.js package.json && node ./scripts/flow/createFlowConfigs.js && node ./scripts/yarn/downloadReactIsForPrettyFormat.js
Wrote a Flow config to /home/tester/react/scripts/flow/dom/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/dom-browser/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/native/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/fabric/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/test/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/dom-relay/.flowconfig
Wrote a Flow config to /home/tester/react/scripts/flow/custom/.flowconfig
Done in 31.05s.

bash-4.2# yarn test
yarn run v1.22.0
$ cross-env NODE_ENV=development jest --config ./scripts/jest/config.source.js
 PASS  packages/react-reconciler/src/__tests__/ReactIncremental-test.internal.js
...
...
...
 PASS  scripts/babel/__tests__/transform-prevent-infinite-loops-test.js

Test Suites: 246 passed, 246 total
Tests:       27 skipped, 5831 passed, 5858 total
Snapshots:   161 passed, 161 total
Time:        82.895s, estimated 107s
Ran all test suites.
Done in 86.59s.
bash-4.2#
```

**Comment by bvaughn** [comment]
We won't be able to merge that change. `electron` **is** a **required** dependency for that package.

I only suggested you remove it so you could get `yarn install` working for your unusual CPU. PowerPC is not something I think we will try to support in this repo.

**Comment by sarveshtamba** [comment]
@bvaughn any side effects if electron dependency is removed entirely, will it affect any other react component?
Also the CPU is Linux PowerPC i.e linux based ppc64le architecture.
