### ISSUE TITLE
Error: "Could not find commit data for root "220" and commit 65"

### ISSUE THREAD

**Issue by georeith** [facebook/react#18398]
Describe what you were doing when the bug occurred:

1. Changing root of Flamegraph from a React one to https://github.com/michalochman/react-pixi-fiber

![image](https://user-images.githubusercontent.com/3090066/77679090-03e91b80-6f8a-11ea-8637-dd162f96a675.png)

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.5.0-355970aa4

Call stack: at n.value (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:171903)
    at p (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:358164)
    at Zc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:358379)
    at ti (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58696)
    at qi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:67715)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:108833)
    at jc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:100072)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99997)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99862)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96528)

Component stack: in Zc
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment]
Thanks for the report, but this issue is already been tracked as #18010 :smile:
