### ISSUE TITLE
Error: "Cannot read property 'duration' of undefined"

### ISSUE THREAD

**Issue by psytonik** [facebook/react#18440]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.5.0-355970aa4

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342553
    at Array.map (<anonymous>)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342359
    at ti (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:58696)
    at Sl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:107566)
    at jc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:100072)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99997)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99862)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:96528)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:45860

Component stack: in Unknown
    in Unknown
    in div
    in div
    in n
    in div
    in bc
    in div
    in n
    in div
    in vc
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by gaearon** [comment]
Hi @pystonik,

You forgot to fill in:

> Describe what you were doing when the bug occurred:

**Comment by psytonik** [comment]
i don't remember it's something in new UI

**Comment by bvaughn** [comment]
Closing due to lack of repro info
