### ISSUE TITLE
Bug:  Invariant failed on production Env on SSR

### ISSUE THREAD

**Issue by krishnaTORQUE** [facebook/react#18506]
No issue in development Env
but as soon as I change NODE_ENV to production on SSR
below error is showing 

`
/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44
x="";try{x+=this.render(l,e.context,e.domNamespace)}catch(t){if(null!=t&&"function"===typeof t.then)throw Error(r(294));throw t;}finally{}h.length<=this.suspenseDepth&&h.push("");h[this.suspenseDepth]+=x}}return h[0]}finally{Ra.current=c,X=b}};b.render=function(a,b,f){if("string"===typeof a||"number"===typeof a){f=""+a;if(""===f)return"";if(this.makeStaticMarkup)return N(f);if(this.previousWasTextNode)return"\x3c!-- --\x3e"+N(f);this.previousWasTextNode=!0;return N(f)}b=$a(a,b,this.threadID);a=b.child;
                                                                                                                        ^

Error: Invariant failed
    at invariant (/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/tiny-invariant/dist/tiny-invariant.cjs.js:11:15)
    at Object.children (/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/react-router/modules/withRouter.js:18:11)
    at a.b.render (/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:47:125)
    at a.b.read (/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
    at renderToString (/mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
    at /mnt/KrishnaTorque/Projects/NodeJS/02/dxtrez/src/srcServer/lib/renderHandler.js:52:26
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:61:3)

`

**Comment by CreateBerend** [comment]
Hello @krishnaTORQUE,

Have you managed to solve this problem? I also encounter this bug, and it is really annoying.

**Comment by CreateBerend** [comment]
> > Hello @krishnaTORQUE,
> > Have you managed to solve this problem? I also encounter this bug, and it is really annoying.
> 
> Its more than a year now. I am not sure what I have done to resolve this but as far I can remember there was a regex issue in my code.

Thank you so much for you very quick response, I'll look into it!

**Comment by krishnaTORQUE** [comment]
> > > Hello @krishnaTORQUE,
> > > Have you managed to solve this problem? I also encounter this bug, and it is really annoying.
> > 
> > 
> > Its more than a year now. I am not sure what I have done to resolve this but as far I can remember there was a regex issue in my code.
> 
> Thank you so much for you very quick response, I'll look into it!

Welcome
