### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by gasi** [facebook/react#1866]
After upgrading from React 0.10 to 0.11 our `componentWillMount` handler fires during server-side rendering and ends up in `getActiveElement` which requires access to the DOM, i.e. `document`:

Redacted stack trace:

```
ReferenceError: document is not defined
    |     <<< async stack >>>
    |   at getActiveElement (~/workspace/project/node_modules/react/lib/getActiveElement.js:30:12)
    |   at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (~/workspace/project/node_modules/react/lib/ReactInputSelection.js:48:23)
    |   at ReactReconcileTransaction.Mixin.initializeAll (~/workspace/project/node_modules/react/lib/Transaction.js:175:30)
    |   at ReactReconcileTransaction.Mixin.perform (~/workspace/project/node_modules/react/lib/Transaction.js:140:12)
    |   at ReactUpdatesFlushTransaction.Mixin.perform (~/workspace/project/node_modules/react/lib/Transaction.js:141:20)
    |   at ReactUpdatesFlushTransaction.mixInto.perform (~/workspace/project/node_modules/react/lib/ReactUpdates.js:98:38)
    |   at Object.<anonymous> (~/workspace/project/node_modules/react/lib/ReactUpdates.js:176:19)
    |   at Object.flushBatchedUpdates (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (~/workspace/project/node_modules/react/lib/Transaction.js:214:42)
    |   at ReactDefaultBatchingStrategyTransaction.Mixin.perform (~/workspace/project/node_modules/react/lib/Transaction.js:155:16)
    |   at Object.ReactDefaultBatchingStrategy.batchedUpdates (~/workspace/project/node_modules/react/lib/ReactDefaultBatchingStrategy.js:70:19)
    |   at Object.enqueueUpdate (~/workspace/project/node_modules/react/lib/ReactUpdates.js:209:22)
    |   at [object Object].ReactCompositeComponentMixin.replaceState (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:871:18)
    |   at [object Object].ReactCompositeComponentMixin.setState (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:850:10)
    |   at [object Object].module.exports.React.createClass.setup (~/workspace/project/scripts/index.coffee:52:10)
    |   at [object Object].boundMethod [as setup] (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:1287:21)
    |   at [object Object].module.exports.React.createClass.componentWillMount (~/workspace/project/scripts/index.coffee:28:10)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:769:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactMultiChild.Mixin.mountChildren (~/workspace/project/node_modules/react/lib/ReactMultiChild.js:202:42)
    |   at [object Object].ReactDOMComponent.Mixin._createContentMarkup (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:198:32)
    |   at [object Object].ReactDOMComponent.Mixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactDOMComponent.js:120:14)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at [object Object].ReactCompositeComponentMixin.mountComponent (~/workspace/project/node_modules/react/lib/ReactCompositeComponent.js:784:44)
    |   at [object Object].mountComponent (~/workspace/project/node_modules/react/lib/ReactPerf.js:57:21)
    |   at ~/workspace/project/node_modules/react/lib/ReactServerRendering.js:53:38
    |   at ReactServerRenderingTransaction.Mixin.perform (~/workspace/project/node_modules/react/lib/Transaction.js:141:20)
    |   at Object.renderComponentToString (~/workspace/project/node_modules/react/lib/ReactServerRendering.js:51:24)
```

**Comment by olance** [comment]
Hi guys!

The issue referenced above looks (reactjs/react-rails#146) related to this one... input welcome!
