### ISSUE TITLE
Error: "Commit tree does not contain fiber 55875. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by Lukavyi** [facebook/react#18701]
Describe what you were doing when the bug occurred:
1. Profiled my session, then selected to show commits over 10ms
2. Went through commits in profiler 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at j (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:162825)
    at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:161772)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:164582)
    at ec (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:339280)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at nl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:69923)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:110996)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)

Component stack: in ec
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment]
Hey @Lukavyi 

Are you able to reproduce this behavior? If so, can you share the app or example code with us to help us repro it?

**Comment by Lukavyi** [comment]
Nope, not able to reproduce.
It was a bug in react dev tools

**Comment by bvaughn** [comment]
Yes, I realize that :smile: but the conditions that trigger the bug are unknown to me, so it's hard to investigate and fix it.

**Comment by bvaughn** [comment]
I wasn't suggesting that we needed to close it. I was just agreeing that it seems like a DeTools bug, and trying to share the reason why it was important for us to try to get a little more info on how to reproduce.

**Comment by Lukavyi** [comment]
I get it, but I don't have a way to reproduce it. 
The bug just randomly happened once during profiling when I've opened first frame and that's it :)

**Comment by bvaughn** [comment]
Fair enough.

Sorry for the inconvenience. Hopefully someone will figure out a way to reproduce it eventually and we'll get it fixed. 😅 

Hope DevTools are working out well for you otherwise!
