### ISSUE TITLE
Bug: Unable to run command npm start

### ISSUE THREAD

**Issue by candreslobor** [facebook/react#18793]
## Steps To Reproduce

1.run `npx create-react-app`
2.cd `project-folder`
3.npm start

## The current behavior
`Starting the development server...

events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ENOSPC: System limit for number of file watchers reached, watch '/home/candres/Documents/Programacion/Cursos/MERN/frontend/public/logo512.png'
    at FSWatcher.<computed> (internal/fs/watchers.js:169:26)
    at Object.watch (fs.js:1388:34)
    at createFsWatchInstance (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:38:15)
    at setFsWatchListener (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:233:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:262:21)
    at FSWatcher.<anonymous> (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:495:21)
    at FSReqCallback.oncomplete (fs.js:172:5)
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/index.js:260:10)
    at createFsWatchInstance (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:40:5)
    at setFsWatchListener (/home/candres/Documents/Programacion/Cursos/MERN/frontend/node_modules/webpack-dev-server/node_modules/chokidar/lib/nodefs-handler.js:81:15)
    [... lines matching original stack trace ...]
    at FSReqCallback.oncomplete (fs.js:172:5) {
  errno: -28,
  syscall: 'watch',
  code: 'ENOSPC',
  path: '/home/candres/Documents/Programacion/Cursos/MERN/frontend/public/logo512.png',
  filename: '/home/candres/Documents/Programacion/Cursos/MERN/frontend/public/logo512.png'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! frontend@0.1.0 start: `react-scripts start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the frontend@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/candres/.npm/_logs/2020-04-30T18_30_11_541Z-debug.log`

**Comment by Elvis339** [comment]
Here's something that may help: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

**Comment by candreslobor** [comment]
> Here's something that may help: https://github.com/guard/listen/wiki/Increasing-the-amount-of-inotify-watchers

yeah it works, thanks a lot dude
