### ISSUE TITLE
Error: "Could not find node with id "4557" in commit tree"

### ISSUE THREAD

**Issue by kalyan-k** [facebook/react#18924]
Describe what you were doing when the bug occurred:
1. Started profiling the application
2. Tried to stop it after couple of navigation and actions on spa, but failed to stop.
3. Finally clicking multiple times on Stop has stopped profiling, and got his issue in graph option

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.6.0-6cceaeb67

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167472
    at Map.forEach (<anonymous>)
    at commitIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167418)
    at e.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167941)
    at lc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342270)
    at ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:59620)
    at Ll (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:109960)
    at qc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102381)
    at Hc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102306)
    at Vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102171)

Component stack: in lc
    in div
    in div
    in div
    in So
    in Unknown
    in n
    in Unknown
    in div
    in div
    in rl
    in Ze
    in fn
    in Ga
    in _s

**Comment by bvaughn** [comment]
Can you share any sort of repro case with us?

**Comment by bvaughn** [comment]
Resolved by #19987
