### ISSUE TITLE
Bug: SyntaxError when trying to import named exports from "react"

### ISSUE THREAD

**Issue by wereHamster** [facebook/react#18941]
React version: 16.13.1

## Steps To Reproduce

```
import React, { useState } from "react";
console.log(React, useState)
```

The import declaration is taken straight from the hooks documentation (https://reactjs.org/docs/hooks-intro.html), hence why I expected it to work.

Save as bug.mjs, run with `node bug.mjs` (node v13 or later).

## The current behavior

```
file:///…/bug.mjs:1
import React, { useState } from "react";
                ^^^^^^^^
SyntaxError: The requested module 'react' does not provide an export named 'useState'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
```

## The expected behavior

No Syntax Error.

**Comment by irohitb** [comment]
I am not sure about `.mjs` file but I don't think that's how you run a react app.

**Comment by kunukn** [comment]
It seems ES modules are expected.

React is officially not shipped as ES modules yet.
https://github.com/facebook/react/issues/11503

You could try this.

```
import React from "react";
const { useState } = React;
```

Or you could try these React installs
https://github.com/facebook/react/issues/11503#issuecomment-595263605
