### ISSUE TITLE
Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 36"

### ISSUE THREAD

**Issue by agustinpardolp** [facebook/react#19292]
Describe what you were doing when the bug occurred:
Hi I was using the profile functionallity from react dev tools, 
and suddenly this error happened.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.7.0-23309eb38

Call stack: at I (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:163895)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166664)
    at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342328)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:62450)
    at tl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:71793)
    at zl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:113765)
    at Ic (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104502)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104430)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:104298)
    at vc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:99542)

Component stack: at Ul (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:342099)
    at div
    at div
    at div
    at Co (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:263571)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:366677
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:276314)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:278724
    at div
    at div
    at Xi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:325177)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:207026)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:216342)
    at Va (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:293773)
    at us (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:371869)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18987) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Comment by agustinpardolp** [comment]
Hi Brian, thanks for your answer.

I have this issue again,

An error was thrown: "Commit tree does not contain fiber 819. This is a bug in React DevTools."


But now it's happening just by moving in a few pages;
I configured some filters, I don't know if that could affect something ...


________________________________
De: Brian Vaughn <notifications@github.com>
Enviado: jueves, 9 de julio de 2020 13:41
Para: facebook/react <react@noreply.github.com>
Cc: Agus Pardo <agustinpardo@hotmail.com>; Author <author@noreply.github.com>
Asunto: Re: [facebook/react] Error: "getCommitTree(): Unable to reconstruct tree for root "1" and commit 36" (#19292)


I'm sorry you experienced this bug! 🙇

Looks like this problem was already reported though (#18987<https://github.com/facebook/react/issues/18987>) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Comment by bvaughn** [comment]
There's an issue for that too: #18831

Any additional repro steps you could share- please do on that issue.
