### ISSUE TITLE
Error: "Commit tree does not contain fiber 2756. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by wojtekmaj** [facebook/react#19324]
Describe what you were doing when the bug occurred:
1. Recorded navigating between two pages using Profiler
2. After recording, tried to see the next frame in the profiler

The only thing that may be unusual about the app is that both pages were based on Recoil.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.1-d4eadea6c

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167176)
    at T (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166123)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:168938)
    at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346620)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:60964)
    at Ui (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:70944)
    at Bl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:117704)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103070)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102998)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102861)

Component stack: at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346391)
    at div
    at div
    at div
    at Eo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:266560)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:370969
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:279481)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:282269
    at div
    at div
    at Ji (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:329374)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:209300)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:218616)
    at Wa (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:297360)
    at ps (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:376211)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18831) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
