### ISSUE TITLE
Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by slavikhard** [facebook/react#19344]
DevTools version: 4.8.1-d4eadea6c

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:166989)
    at T (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:165979)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:168938)
    at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346620)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:60964)
    at Ui (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:70944)
    at Bl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:117704)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103070)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102998)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102861)

Component stack: at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346391)
    at div
    at div
    at div
    at Eo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:266560)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:370969
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:279481)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:282269
    at div
    at div
    at Ji (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:329374)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:209300)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:218616)
    at Wa (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:297360)
    at ps (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:376211)

**Comment by bvaughn** [comment]
Please search existing issues to see if something has already been reported before opening a new one :smile:

This issue has already been reported as #18256. Please add any extra helpful info you may have to that issue.
