### ISSUE TITLE
Error: "Commit tree does not contain fiber 3716. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by denieler** [facebook/react#19383]
Describe what you were doing when the bug occurred:
1. Open React Dev Tools
2. Click "Start profiling" on Profiler tab
3. Expand MUI Expandable component
4. Click "Stop profiling"
5. Have this error

<img width="831" alt="Screenshot 2020-07-16 at 11 26 03" src="https://user-images.githubusercontent.com/2836281/87646315-56c42a00-c757-11ea-97f0-d5fb1dd7b776.png">

Thank you guys for helping with this!

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.1-d4eadea6c

Call stack: at N (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:167176)
    at T (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:165979)
    at e.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:168938)
    at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346620)
    at oi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:60964)
    at Ui (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:70944)
    at Bl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:117704)
    at Tc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:103070)
    at Oc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102998)
    at Dc (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32:102861)

Component stack: at Wl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:346391)
    at div
    at div
    at div
    at Eo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:266560)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:370969
    at n (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:279481)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:282269
    at div
    at div
    at Ji (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:329374)
    at Ge (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:209300)
    at sn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:218616)
    at Wa (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:297360)
    at ps (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40:376211)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18831) and has been fixed as of yesterday in the version 4.8.2 release. Looks like you're still running version 4.8.1 though, so you might want to restart your browser.

**Comment by denieler** [comment]
> I'm sorry you experienced this bug! 🙇
> 
> Looks like this problem was already reported though (#18831) and has been fixed as of yesterday in the version 4.8.2 release. Looks like you're still running version 4.8.1 though, so you might want to restart your browser.

Cool thank you! Will try
