### ISSUE TITLE
Bug: React 16.11.0 Install error: Unexpected end of input

### ISSUE THREAD

**Issue by shrihanDev** [facebook/react#19445]
## Description
Today, I wanted to learn react-native after learning react. So, I went to [React Native Official Website](https://reactnative.dev). In the setup of the environment, I learnt about expo-cli. I went to [Expo](https://expo.io) and installed by copying the command. It installed well. But when I created a project by `expo init` command, it throwed an error at Installing React@16.11.0. See the below screenshot.
I tried to install every package except React, then `npm install react@~16.11.0` but failed.

My package.json:
```
{
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "dependencies": {
    "expo": "^38.0.8",
    "expo-status-bar": "^1.0.2",
    "react": "~16.11.0",
    "react-dom": "^16.11.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-38.0.2.tar.gz",
    "react-native-web": "^0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.8.6",
    "babel-preset-expo": "~8.1.0"
  },
  "private": true
}
```

npm Debug Log:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'react@~16.11.0'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.18.0
4 verbose npm-session 928895f1c47b33d6
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 304 https://registry.npmjs.org/react 2210ms (from cache)
8 silly fetchPackageMetaData error for react@~16.11.0 Unexpected end of JSON input while parsing near '...1.0","object-assign":'
9 timing stage:rollbackFailedOptional Completed in 1ms
10 timing stage:runTopLevelLifecycles Completed in 32243ms
11 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...1.0","object-assign":'
11 verbose stack     at JSON.parse (<anonymous>)
11 verbose stack     at parseJson (C:\Program Files\nodejs\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
11 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
11 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
12 verbose cwd D:\homework\COMPUTER\Programming\Web\Self Tutorials\swag-react-native
13 verbose Windows_NT 6.1.7601
14 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "react@~16.11.0"
15 verbose node v12.18.0
16 verbose npm  v6.14.4
17 error Unexpected end of JSON input while parsing near '...1.0","object-assign":'
18 verbose exit [ 1, true ]
```

React version: 16.11.0

## Steps To Reproduce

1. Run `npm install react@~16.11.0` from the terminal
2. Get an error:
![Capture](https://user-images.githubusercontent.com/54971391/88365179-d7f86e00-cda2-11ea-8ba6-26a37b06bfa3.PNG)

Link to code example: No code, as nothing is installed

## The current behavior
Throwing the above error.

## The expected behavior
Install React 16.11.0

**Comment by bvaughn** [comment]
Looks like a transient NPM error.

**Comment by shrihanDev** [comment]
Ok, so how do I fix this?

**Comment by shrihanDev** [comment]
I filed an issue to @expo/expo-cli and they told to fix it by running `npm cache clean --force`
