### ISSUE TITLE
App crashes upon the automatic attempt to inspect hooks on a Fiber with tag of type ClassComponent

### ISSUE THREAD

**Issue by shmuelhizmi** [facebook/react#19765]
the issue from https://github.com/facebook/react-devtools/issues/1352 still occur when trying to use react-devtools with a nodejs react application (the issue was closed due to the react-devtools rewrite of version 4)

**Comment by bvaughn** [comment]
(If the repro is literally the same as the issue you linked to, it's okay to copy that over to this issue. But please be very clear about how we can reproduce the failing behavior you're describing.)

**Comment by shmuelhizmi** [comment]
@bvaughn  I encunted this problem when trying to inspect any nodejs application build with [this library](https://github.com/shmuelhizmi/react-fullstack/tree/master/packages/fullstack ) which use an empty react-reconciler renderer as its render ( [source code](https://github.com/shmuelhizmi/react-fullstack/blob/master/packages/react-render-null/src/rendererLegacy.ts) ).
the full error is
```
[React DevTools] Error calling listener { event: 'inspectElement', payload: { id: 10, rendererID: 2 } }
[0] error: Error: Unknown Fiber. Needs to be a function component to inspect hooks.
[0]     at t.inspectHooksOfFiber (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:24:5162)
[0]     at We (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:46503)
[0]     at Object.inspectElement (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:52776)
[0]     at /home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:63361
[0]     at t.value (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:8223)
[0]     at /home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:72745
[0]     at /home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:90393
[0]     at Array.forEach (<anonymous>)
[0]     at WebSocket.Xt.g.onmessage (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/react-devtools-core/dist/backend.js:32:90368)
[0]     at WebSocket.onMessage (/home/shmuelhizmi/Documents/projects/web-desktop-environment/packages/flows/node_modules/ws/lib/event-target.js:125:16)
```

if your looking for an easy way to reproduce the issue you can do the following
 - `git clone https://github.com/shmuelhizmi/web-desktop-environment` 
- `cd  web-desktop-environment`
- `npm start`
and connect with the standalone react-devtools app -
the app will crash with error above

**Comment by shmuelhizmi** [comment]
bump

**Comment by Muriel-Gasparini** [comment]
same here
