### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by dziekonskik** [facebook/react#20165]
Describe what you were doing when the bug occurred:
1. fetching data from gh api
2. trying to append pictures to a slider ;p
3. happily hacking

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.9.0-75726fadfd

Call stack: at store_Store.getElementAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21068:35)
    at store_Store.getElementIDAtIndex (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21084:26)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28520:63
    at List.render (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22776:18)
    at wi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13590:76)
    at vi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13581:10)
    at nk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16165:86)
    at mk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15541:11)
    at lk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15533:23)
    at dk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15517:5)

Component stack: at List (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22471:30)
    at div
    at AutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:3006:5)
    at div
    at div
    at Tree_Tree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28271:47)
    at div
    at div
    at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28763:3)
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27400:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28048:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33225:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29061:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29178:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32776:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24164:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24653:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29246:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36049:3)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#19927) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
