### ISSUE TITLE
Error: "Commit tree already contains fiber 960. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by ATrogolo** [facebook/react#20268]
Describe what you were doing when the bug occurred:
1. Monitoring page load with ReactDevTool Profiler
2. Stopped the recording 
3. Selected a render phase in the FlameGraph

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Call stack: at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19650:17)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19583:26)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19576:32)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34133:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28195:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35761:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29208:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29325:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32923:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24311:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24800:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29393:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36196:3)

**Comment by eps1lon** [comment]
I'm sorry you experienced this bug!

Looks like this problem was already reported though (#18859) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you

**Comment by bvaughn** [comment]
@ATrogolo This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼

**Comment by ATrogolo** [comment]
Hi @bvaughn , 
I'll try to reproduce it when I'll have some spare time (tomorrow I suppose)

I'll let you know about. Almost 6 months passed since I opened this issue..

**Comment by bvaughn** [comment]
Okay, understood! Either way, thanks for checking.

**Comment by bvaughn** [comment]
> Almost 6 months passed since I opened this issue..

React DevTools only has one maintainer (me) and it's not my only job. I do the best I can to keep up with issues 😄  Ones that don't have repro steps (like this one) are _really hard_ to fix.

**Comment by ATrogolo** [comment]
Hi @bvaughn ,
of course, I really appreciate your job to maintain the React DevTools ;) 
Unfortunately I'm not able to reproduce the issue right now, I tried several times but nothing "crashed"! :D 

I'll do some experiments in the next days and I'll let you know

**Comment by bvaughn** [comment]
No problem :) Thanks!
