### ISSUE TITLE
Error: "Commit tree does not contain fiber 1069. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by hckhanh** [facebook/react#20273]
Describe what you were doing when the bug occurred:
1. Navigate between my routes when the record is turned on
2. Get this bug

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Call stack: at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19718:21)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19563:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20104:11)
    at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34150:33)
    at Fh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12806:7)
    at ni (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13448:7)
    at jk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16065:86)
    at ik (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15450:11)
    at hk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15442:23)
    at Zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15426:5)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34133:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28195:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35761:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29208:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29325:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32923:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24311:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24800:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29393:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36196:3)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20197) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
