### ISSUE TITLE
Error: "Commit tree does not contain fiber 9501. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by feedthejim** [facebook/react#20270]
Describe what you were doing when the bug occurred:
1. I was profiling a trace on Facebook
2. Tried to switch to another commit
3. The devtools crashed

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.8.2-7b6cac952

Call stack: at updateTree (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:19571:21)
    at getCommitTree (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:19436:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:19957:11)
    at CommitFlamegraphAutoSizer (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:34003:33)
    at Hh (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:12871:7)
    at qi (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:13521:7)
    at nk (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:16162:86)
    at mk (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:15541:11)
    at lk (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:15533:23)
    at dk (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:15517:5)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:33986:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:28048:3)
    at Profiler_Profiler (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:35614:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:29061:5)
    at PortaledContent (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:29178:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:32776:3)
    at TreeContextController (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:24164:3)
    at SettingsContextController (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:24653:3)
    at ModalDialogContextController (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:29246:3)
    at DevTools_DevTools (chrome-extension://dnjnjgbfilfphmojnmhliehogmojhclc/build/main.js:36049:3)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20197) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
