### ISSUE TITLE
Error: "Could not find node with id "7348" in commit tree"

### ISSUE THREAD

**Issue by RealDrewKlayman** [facebook/react#20295]
Describe what you were doing when the bug occurred:
1.  Ran Profiler
2.  Clicked on Rank

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.0-11a2ae3a0d

Call stack: at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20039:13
    at Map.forEach (<anonymous>)
    at RankedChartBuilder_getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20035:24)
    at ProfilingCache_ProfilingCache.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20157:11)
    at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34416:32)
    at Fh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12806:7)
    at jk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16003:11)
    at ik (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15450:11)
    at hk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15442:23)
    at Zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15426:5)

Component stack: at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34395:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28195:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35761:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29208:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29325:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32923:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24311:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24800:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29393:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36196:3)

**Comment by bvaughn** [comment]
It doesn't look like this bug report has enough info for one of us to reproduce it.

Please provide a CodeSandbox (https://codesandbox.io/s/new), a link to a repository on GitHub, or provide a minimal code example that reproduces the problem. Screenshots or videos can also be helpful if they help provide context on how to repro the bug.

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
Closing due to a lack of response.
