### ISSUE TITLE
Error: "Cannot read property 'concat' of undefined"

### ISSUE THREAD

**Issue by rufataliy** [facebook/react#20560]
Describe what you were doing when the bug occurred:
1. It worked the first time I ran it.
2. Then I added useRef and console for debugging (don't think is related to the but might help)
3. I profile the interaction
4. When I stopped profiling this error occurred

Link to repo [repo](https://github.com/rufataliy/recippy)

You will need API_KEY env variable to be able to access the api. I believe you can use 1 for searching but it will not get you initial recipes when you load the page first.

So if you run the `npm run next-dev` command after installing dependencies you will have dev version of the app and you will need to run the profiler, click the view button on the recipe card and stop profiler.

Sorry, if it not that helpful I couldn't reproduce it myself, as well.

Hope it is helpful.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Call stack: at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19702:53)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19574:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20115:11)
    at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34161:33)
    at Hh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:12807:7)
    at qi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13457:7)
    at mk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16074:86)
    at lk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15459:11)
    at kk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15451:23)
    at ck (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15435:5)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34144:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28206:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35772:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29219:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29336:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32934:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24322:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24811:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29404:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:36207:3)

**Comment by bvaughn** [comment]
> 1. It worked the first time I ran it.
> 2. Then I added useRef and console for debugging (don't think is related to the but might help)

Unfortunately these steps aren't going to help us repro the bug being reported here. Can you please provide a link to the code that you're running when this happens?

**Comment by rufataliy** [comment]
> > 1. It worked the first time I ran it.
> > 2. Then I added useRef and console for debugging (don't think is related to the but might help)
> 
> Unfortunately these steps aren't going to help us repro the bug being reported here. Can you please provide a link to the code that you're running when this happens?

**Comment by rufataliy** [comment]
Sorry closed it by mistake. 

I added repo link and some more steps to reproduce it.

**Comment by bvaughn** [comment]
Thank you. That would be very helpful.
