### ISSUE TITLE
Bug: why not exec yarn build 

### ISSUE THREAD

**Issue by nextdoorUncleLiu** [facebook/react#20616]
Why does `yarn build` prompt me:
Error: Cannot find module'react'
Require stack:
-/Users/react-source-code/scripts/rollup/build.js
     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
     at Function.resolve (internal/modules/cjs/helpers.js:80:19)
     at createBundle (/Users/react-source-code/scripts/rollup/build.js:556:13)
     at buildEverything (/Users/react-source-code/scripts/rollup/build.js:765:11) {
   code:'MODULE_NOT_FOUND',
   requireStack: [
     '/Users/react-source-code/scripts/rollup/build.js'
   ]
}

**Comment by nextdoorUncleLiu** [comment]
yarn ok
npm not exec
