### ISSUE TITLE
Error: "Commit tree already contains fiber 1. This is a bug in React DevTools."

### ISSUE THREAD

**Issue by singhdeepanshu** [facebook/react#21046]
I was just recording through the profiler in react-dev-tools. I started the recording and stopped it.
I clicked on the arrow, select next commit and after 4-5 simultaneous clicks and got this issue. 
The image is attached below for your reference. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.10.1-f160547f47

Call stack: at updateTree (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:19661:17)
    at getCommitTree (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:19594:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:20115:11)
    at CommitRankedAutoSizer (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:34423:33)
    at Hh (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:12807:7)
    at qi (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:13457:7)
    at mk (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:16074:86)
    at lk (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:15459:11)
    at kk (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:15451:23)
    at ck (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:15435:5)

Component stack: at CommitRankedAutoSizer (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:34406:50)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:28206:3)
    at Profiler_Profiler (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:35772:50)
    at ErrorBoundary_ErrorBoundary (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:29219:5)
    at PortaledContent (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:29336:32)
    at div
    at div
    at ProfilerContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:32934:3)
    at TreeContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:24322:3)
    at SettingsContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:24811:3)
    at ModalDialogContextController (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:29404:3)
    at DevTools_DevTools (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:36207:3)

![image](https://user-images.githubusercontent.com/38343658/111901979-14c75280-8a61-11eb-8ec5-2e7f582ab5e0.png)

![image](https://user-images.githubusercontent.com/38343658/111902105-afc02c80-8a61-11eb-80ee-61437855da47.png)

**Comment by bvaughn** [comment]
I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#18859) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~

**Comment by bvaughn** [comment]
@singhdeepanshu This error remains the highest reported DevTools bug but we still don't have a repro case so that I can fix it. Do you remember how to repro the error you saw above? Can you share the steps with me if so? It would be very helpful! Thank you 🙇🏼
