### ISSUE TITLE
Error: "Cannot read property 'isCollapsed' of undefined"

### ISSUE THREAD

**Issue by mrkev** [facebook/react#21258]
Describe what you were doing when the bug occurred:
1. Refresh the page I'm inspecting.
2. Notice two warnings in the errors and warnings section, like so: 
<img width="196" alt="Screen Shot 2021-04-13 at 7 44 32 PM" src="https://user-images.githubusercontent.com/1285131/114647125-65f9e900-9c91-11eb-8412-c7807a1c7063.png">
3. Click any arrow, either the one going up or the one going down, to view one of them. The tools crash.

If I restart the tools, things work smoothly again. I also don't see the warnings anymore.

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.11.0-39713716aa

Call stack: at store_Store.getIndexOfElementID (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:22245:24)
    at getCurrentValue (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29244:29)
    at useSubscription (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25874:12)
    at SelectedTreeHighlight_SelectedTreeHighlight (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29268:16)
    at Rh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13245:7)
    at Ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13944:7)
    at uk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16725:86)
    at tk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16245:11)
    at qk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16237:23)
    at jk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16221:5)

Component stack: at SelectedTreeHighlight_SelectedTreeHighlight (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29213:34)
    at div
    at InnerElementType (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29953:3)
    at div
    at List (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:23588:30)
    at div
    at AutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:3111:5)
    at div
    at div
    at Tree_Tree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29531:47)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28680:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29121:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34645:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30035:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30157:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34264:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25356:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25963:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30300:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37639:3)

**Comment by mrkev** [comment]
The trace looks different than the one on #19927— could be because I'm on a newer version of the tools, or in Web Speed terms, it could be a different MID.

I'll let you decide to close it @bvaughn (:

**Comment by bvaughn** [comment]
> could be because I'm on a newer version of the tools

Yes. Most likely.

> 1. Refresh the page I'm inspecting.

This isn't a repro I can try. Can you share something I can repro on my end?

**Comment by bvaughn** [comment]
Merging this into #19927 since there's still no repro on this one.

**Comment by mrkev** [comment]
Oops just saw this. Haven't been able to repro consistently in a way where I could build a repo that does. In fact, I'm seeing this error much less now too— I wonder if it's something that changed in our codebase or the tools since.
