### ISSUE TITLE
Error: "Commit tree does not contain fiber "281". This is a bug in React DevTools."

### ISSUE THREAD

**Issue by kmanimurugan** [facebook/react#21375]
Describe what you were doing when the bug occurred:
1. 
2. 
3. 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.12.3-8f202a7c8d

Call stack: at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20851:21)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20696:26)
    at ProfilingCache_ProfilingCache.getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21270:11)
    at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:38410:33)
    at Rh (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:13416:7)
    at Ci (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:14117:7)
    at vk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16901:86)
    at uk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16421:11)
    at rk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16413:23)
    at jk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16397:5)

Component stack: at CommitFlamegraphAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:38393:34)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:29447:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40191:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33093:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33173:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37212:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25675:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26289:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33316:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40587:3)

**Comment by bvaughn** [comment]
I'm confused about why DevTools did not automatically link this error to the pre-existing issue #20431 (unless maybe GitHub issue search timed out or failed for some reason?)

**Comment by bvaughn** [comment]
Well, regardless, I'm sorry you experienced this bug! 🙇 

Looks like this problem was already reported though (#20431) so I'm going to mark this issue as a duplicate and close it. If you have additional context that might help us repro this problem, please leave a comment on the other issue!

Thank you~
