### ISSUE TITLE
Error: "Node "103" was removed before its children."

### ISSUE THREAD

**Issue by alkairis** [facebook/react#21444]
### Which website or app were you using when the bug happened?

Please provide a link to the URL of the website (if it is public), a CodeSandbox (https://codesandbox.io/s/new) example that reproduces the bug, or a project on GitHub that we can checkout and run locally.

### What were you doing on the website or app when the bug happened?

If possible, please describe how to reproduce this bug on the website or app mentioned above:
1. 
2. 
3. 

### Generated information

DevTools version: 4.13.1-93782cfed2

Call stack:
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21514:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19607:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19767:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37788:39)

Component stack:
(none)

GitHub URL search query:
https://api.github.com/search/issues?q=Node%20%20was%20removed%20before%20its%20children.%20in%3Atitle%20is%3Aissue%20is%3Aopen%20is%3Apublic%20label%3A%22Component%3A%20Developer%20Tools%22%20repo%3Afacebook%2Freact

**Comment by bvaughn** [comment]
Hi @alkairis!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by mrhut10** [comment]
I'm having the same problem, but like about I don't have a minimal example to reproduce. just a huge private code base and no clue why its doing it.

I'm going to try do a git blame next week to see when it started

**Comment by bvaughn** [comment]
Thanks @mrhut10. Once we get a repro, we can try to fix. Without it though I can only guess.

**Comment by kartikv11** [comment]
Facing the same issue, only since yesterday though.

**Comment by bvaughn** [comment]
@kartikv11 Check out all of the comments above asking for repro information.

**Comment by ewdaimonia** [comment]
I encountered this issue today and created a small sandbox with all the components that I was working on when it occurred, but I cannot reproduce it, even though I tried for several hours. If this is not helpful and only an actual reproduction will help, I'd be happy to delete this comment, just let me know.

### **What were you doing on the website or app when the bug happened?**
1. Updating line 32 to the commented lines in App.js
2. Updating 36 to the commented lines in ShipLine.jsx
3. Updating 9-12 to the commented lines in SelectInput.jsx

Here's the information I have: 
SandBox: https://codesandbox.io/s/4qvik?file=/src/ShipDetails.jsx
Log: [localhost-1620694607043.log](https://github.com/facebook/react/files/6455832/localhost-1620694607043.log)
![devtools](https://user-images.githubusercontent.com/49082446/117743832-332e0c80-b1cd-11eb-95cb-74d47982cff6.png)

**Comment by bvaughn** [comment]
@ewdaimonia Thank you! This looks _very_ helpful

**Comment by bvaughn** [comment]
I think #21516 should resolve this issue (once released). If you see another repro though, please keep me posted.
