### ISSUE TITLE
Error: "Cannot read property 'length' of undefined"

### ISSUE THREAD

**Issue by skorotkiewicz** [facebook/react#21508]
Describe what you were doing when the bug occurred:
1. Profiler button clicked
2. Profiler used for 5 sec
3. Profiler button stop clicked and immediately this error 

---------------------------------------------
Please do not remove the text below this line
---------------------------------------------

DevTools version: 4.12.4-7becb2ff1b

Call stack: at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:329422)
    at fi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:63339)
    at as (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:119731)
    at Ps (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105351)
    at Rs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105279)
    at Fs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105142)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101735)
    at Ho (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:47259)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:110813
    at Ms (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:110819)
    at Ds (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101335)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101866)
    at w (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:1739)
    at Immediate.A [as _onImmediate] (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:2098)
    at processImmediate (internal/timers.js:439:21)

Component stack: at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:327171)
    at div
    at div
    at ja (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:235611)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:334153
    at hi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:247849)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:248684
    at div
    at div
    at Cs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:295413)
    at hn (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:180675)
    at Un (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:194758)
    at Ii (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:250120)
    at Nc (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:338247)

**Comment by bvaughn** [comment]
Hi!

I'm sorry you ran into this problem 😦 

Unfortunately, it doesn't look like this issue has enough info for one of us to reproduce it though. This means that **it's going to be very hard for us to fix**.

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by bvaughn** [comment]
Please also try updating to the latest version of React DevTools (4.13) to rule out any possible bugs that have already been fixed.

**Comment by liyatang** [comment]
React Developer Tools  still stay in version at 4.13.2 (5/7/2021) ? 
Is there a plan to update

**Comment by bvaughn** [comment]
Don't understand the question. It's May 16. The last release was only a few days ago.

**Comment by gtp-m3** [comment]
Hey @bvaughn Hope you are good I'm looking for my first open source contribution please help

**Comment by FlashJonas** [comment]
I am getting the same error. Using profiler for 5-10 seconds, start/stop. Click in my app. Then stop and I get this error as well.

Using: expo-cli
Local connection
Emulator: Pixel4
SDK: 41.0.0
react-native-cli: 2.0.1
react-native: 0.63.2
React Native Debugger 0.11.8
DevTools 4.12.4-7becb2ff1b

`Uncaught Error: Cannot read property 'length' of undefined
The error was thrown at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:329422)
    at fi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:63339)
    at as (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:119731)
    at Ps (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105351)
    at Rs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105279)
    at Fs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:105142)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101735)
    at Ho (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:47259)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:110813
    at Ms (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:110819)
    at Ds (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101335)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24:101866)
    at w (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:1739)
    at Immediate.A [as _onImmediate] (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40:2098)
    at processImmediate (internal/timers.js:439:21)
The error occurred at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:327171)
    at div
    at div
    at ja (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:235611)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:334153
    at hi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:247849)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:248684
    at div
    at div
    at Cs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:295413)
    at hn (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:180675)
    at Un (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:194758)
    at Ii (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:250120)
    at Nc (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56:338247)`


`bundle.js:10 Console was cleared
RemoteConsole.js:80 Running "main" with {"initialProps":{"exp":{"initialUri":"exp://127.0.0.1:19000","shell":false,"manifestString":"{\"name\":\"rn-complete-guide\",\"slug\":\"rn-complete-guide\",\"version\":\"1.0.0\",\"orientation\":\"portrait\",\"icon\":\".\\/assets\\/icon.png\",\"splash\":{\"image\":\".\\/assets\\/splash.png\",\"resizeMode\":\"contain\",\"backgroundColor\":\"#ffffff\",\"imageUrl\":\"http:\\/\\/127.0.0.1:19000\\/assets\\/.\\/assets\\/splash.png\"},\"updates\":{\"fallbackToCacheTimeout\":0},\"assetBundlePatterns\":[\"**\\/*\"],\"ios\":{\"supportsTablet\":true},\"android\":{\"adaptiveIcon\":{\"foregroundImage\":\".\\/assets\\/adaptive-icon.png\",\"backgroundColor\":\"#FFFFFF\",\"foregroundImageUrl\":\"http:\\/\\/127.0.0.1:19000\\/assets\\/.\\/assets\\/adaptive-icon.png\"}},\"web\":{\"favicon\":\".\\/assets\\/favicon.png\"},\"_internal\":{\"isDebug\":false,\"projectRoot\":\"\\/Users\\/xxxxxxxxxx\\/development\\/xxxxxxReact\\/Academind\\/rn-complete-guide\",\"dynamicConfigPath\":null,\"staticConfigPath\":\"\\/Users\\/xxxxxxx\\/development\\/xxxxxReact\\/Academind\\/rn-complete-guide\\/app.json\",\"packageJsonPath\":\"\\/Users\\/xxxxxxxx\\/development\\/xxxxxxxReact\\/Academind\\/rn-complete-guide\\/package.json\"},\"sdkVersion\":\"41.0.0\",\"platforms\":[\"ios\",\"android\",\"web\"],\"developer\":{\"tool\":\"expo-cli\",\"projectRoot\":\"\\/Users\\/xxxxxxxx\\/development\\/xxxxxxReact\\/Academind\\/rn-complete-guide\"},\"packagerOpts\":{\"scheme\":null,\"hostType\":\"localhost\",\"lanType\":\"ip\",\"devClient\":false,\"dev\":true,\"minify\":false,\"urlRandomness\":null,\"https\":false},\"mainModuleName\":\"node_modules\\/expo\\/AppEntry\",\"bundleUrl\":\"http:\\/\\/127.0.0.1:19000\\/node_modules\\/expo\\/AppEntry.bundle?platform=android&dev=true&hot=false&minify=false\",\"debuggerHost\":\"127.0.0.1:19000\",\"logUrl\":\"http:\\/\\/127.0.0.1:19000\\/logs\",\"hostUri\":\"127.0.0.1:19000\",\"iconUrl\":\"http:\\/\\/127.0.0.1:19000\\/assets\\/.\\/assets\\/icon.png\",\"id\":\"UNVERIFIED-127.0.0.1-rn-complete-guide\",\"isVerified\":true,\"primaryColor\":\"#023C69\"}"}},"rootTag":21}
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56 [React DevTools] Connected
app.html:1 Uncaught (in promise) undefined
Promise.then (async)
yl @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
setTimeout (async)
e @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56
RemoteConsole.js:80 1
.... etc ....
RemoteConsole.js:80 2
RemoteConsole.js:80 goal: qwdasd123123
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24 TypeError: Cannot read property 'length' of undefined
    at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56)
    at fi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at as (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ps (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Rs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Fs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ho (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
    at Ms (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ds (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at w (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40)
    at Immediate.A [as _onImmediate] (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40)
    at processImmediate (internal/timers.js:439)
Dl @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
n.payload @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
da @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ji @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
as @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ps @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Rs @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Fs @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
ws @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ho @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
(anonymous) @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ms @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ds @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
ws @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
w @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40
A @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40
processImmediate @ internal/timers.js:439
/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24 TypeError: Cannot read property 'length' of undefined
    at ec (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:56)
    at fi (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at as (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ps (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Rs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Fs (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ho (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
    at Ms (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at Ds (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at ws (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24)
    at w (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40)
    at Immediate.A [as _onImmediate] (/Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40)
    at processImmediate (internal/timers.js:439)
Dl @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
n.payload @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
da @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ji @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
as @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ps @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Rs @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Fs @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
ws @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ho @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
(anonymous) @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ms @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
Ds @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
ws @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:24
w @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40
A @ /Applications/React Native Debugger.app/Contents/Resources/app.asar/node_modules/react-devtools-core/dist/standalone.js:40
processImmediate @ internal/timers.js:439`

**Comment by FlashJonas** [comment]
I have tried upgrading DevTools to 4.13, but either locally or globally for my RN-project, it still says 4.12 in React Native Debugger. And before the update, I had 4.10 globally but it said 4.12 in the debugger. So please advice on this if you want me to rule out the previous version.

**Comment by FlashJonas** [comment]
Used the downloaded .dmg from the release page, version 11.8. 
(16 days old as of today.)

**Comment by bvaughn** [comment]
@FlashJonas Can you share a repro with me? This issue is still blocked on needing a repro case.

**Comment by FlashJonas** [comment]
Hi, the app is nothing more than a standard Expo-cli init with two buttons. Nothing to check-in really.

**Comment by skorotkiewicz** [comment]
@FlashJonas I use without Expo and also have the same problem.

I haven't updated to the latest version yet, so I don't know if this problem occurs on the new version.

**Comment by bvaughn** [comment]
> I haven't updated to the latest version yet, so I don't know if this problem occurs on the new version.

@skorotkiewicz This sounds like an important first step.

> DevTools version: 4.12.4-7becb2ff1b

DevTools is now on 4.13.3 but it looks like you're running 4.12.4. Updating to rule out a bug that's already be fixed would be nice.

**Comment by bvaughn** [comment]
> Hi, the app is nothing more than a standard Expo-cli init with two buttons. Nothing to check-in really.

@FlashJonas Sounds like it should be easy to share the code and repro steps then? Would be helpful to us.

**Comment by skorotkiewicz** [comment]
@bvaughn Okay, I will build a new version of React Native Debugger with a new version of DevTools right away.
I will let you know if the problem still occurs.

**Comment by bvaughn** [comment]
Thanks @skorotkiewicz!

**Comment by skorotkiewicz** [comment]
@bvaughn @FlashJonas I regret to say that on 4.13.3 this bug does not occur.

![Screenshot 2021-05-20 at 03 04 32](https://user-images.githubusercontent.com/899351/118903630-78aeb000-b918-11eb-9ec0-01ab0ca3ffcf.png)

@FlashJonas Update to the latest version (4.13.3) and it will work nicely.

**Comment by skorotkiewicz** [comment]
@bvaughn PS. Thank you for a great web development tool!

**Comment by bvaughn** [comment]
That's great. Thanks for the update!
