### ISSUE TITLE
[DevTools Bug] Cannot remove node "47636" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by GGWebProject** [facebook/react#21568]
### Website or app

development server localhost:3000

### Repro steps

1) Open `Components tab`
2) Update node tree

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Cannot remove node "47636" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:21178:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19286:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19446:12
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37413:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by PawelGIX** [comment]
I have similar problems with react-konva, some time ago everything was fine. The bugs appear in their codesandbox demos

https://github.com/konvajs/react-konva/issues/586 

https://ox106pyo65.csb.app/
https://codesandbox.io/s/github/konvajs/site/tree/master/react-demos/images?from-embed

**Comment by bvaughn** [comment]
@GGWebProject: We're sorry you've seen this error. ❤️

It looks like you forgot to specify an accessible URL though. (This means that we will not be able to reproduce the problem you're reporting.)

Please help us by providing a link to a CodeSandbox (https://codesandbox.io/s/new), a repository on GitHub, or a minimal code example that reproduces the problem. (Screenshots or videos can also be helpful if they help provide context on how to repro the bug.)

Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

Issues without repros are automatically closed but we will re-open if you update with repro info.

**Comment by bvaughn** [comment]
@PawelGIX If you are able to provide a repro, I can re-open with that too!

**Comment by d-pollard** [comment]
@bvaughn I've ran into this issue as well and have opened a new issue here: https://github.com/facebook/react/issues/23049

has an MCVE
