### ISSUE TITLE
[DevTools Bug] Could not inspect element with id 9

### ISSUE THREAD

**Issue by luifo** [facebook/react#21573]
### Website or app

https://github.com/academind/react-complete-guide-code/tree/07-debugging

### Repro steps

Developing a simple react app in a course on udemy
1- this is the link address
2- https://github.com/academind/react-complete-guide-code/tree/07-debugging

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Could not inspect element with id 9

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31392:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30033:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30176:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32661:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28268:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28709:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34512:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30033:5)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30147:5)
    at div
    at div
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:34138:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24945:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25548:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30234:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37241:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not inspect element with id 9 in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bvaughn** [comment]
@luifo I think this issue needs more repro instructions. I checked out the repo you linked, installed and ran the "finished" code example, and interacted with it a bit and DevTools doesn't throw any errors that I see.

Can you describe _exactly_ what you're doing? (Maybe even share a small screen recording?)

**Comment by bvaughn** [comment]
Closing this issue in favor of #21579 which has repro steps.
