### ISSUE TITLE
Bug: "Cannot read property 'length' of undefined" in areHookInputsEqual

### ISSUE THREAD

**Issue by hamzahamidi** [facebook/react#22049]
React version: 17.0.2

## Steps To Reproduce
When testing my component where I'm using this usecallback hook. I'm getting the error.
```
  const getUrlWithPrefix = useCallback(
    (href: string) => {
      let url = href;
      // logic
      return url;
    },
    [prefix],
  );
```
![image](https://user-images.githubusercontent.com/22576950/128743558-6db90fb6-bafb-4a47-9d4b-d2b8b4bad177.png)

When I dug a little in the callstack I found that it's linked to the code here:

https://github.com/facebook/react/blob/cae635054e17a6f107a39d328649137b83f25972/packages/react-dom/src/server/ReactPartialRendererHooks.js#L92

Shouldn't we just check if prevDeps is neither null nor undefined?

**Comment by bvaughn** [comment]
> Shouldn't we just check if prevDeps is neither null nor undefined?

Hooks are expected to define dependencies _unconditionally_, and the code does check if one of the dependencies arrays is undefined:
https://github.com/facebook/react/blob/ecd73e17bcdecc092cb56259999787d832d6510a/packages/react-dom/src/server/ReactPartialRendererHooks.js#L347-L359

Can you share a full repro of your code? Sounds like maybe it's defining dependencies conditionally?

**Comment by hamzahamidi** [comment]
@bvaughn Thank you for your quick response. But wouldn't be better to make a proper message when dependencies are defined unconditionally instead of the error "Cannot read property 'length' of undefined"

**Comment by bvaughn** [comment]
Dependencies can be undefined. The thing they can't do is change from undefined to defined between renders.

It would still be better to have a proper DEV mode warning about this, (if we don't already), but I wanted to clarify that it's not supported.

**Comment by behagoras** [comment]
Still affecting me

**Comment by jinrichardJIN** [comment]
> Still affecting me

and me , so you resolve the question?

**Comment by d4rky-pl** [comment]
In case you're coming here from Google: had the same issue, turns out I accidentally used hooks incorrectly and used `useCallback` after `if` conditional:

```javascript
  if (loading) {
    return <LoadingComponent />
  }

  const renderItem = useCallback(
    ({ item: candidate }) => <CandidateCard key={candidate?.provider?.id} candidate={candidate} />,
    []
  )
```

The solution was to swap those two blocks. I guess the error message could be more developer-friendly.

**Comment by noopurphalak** [comment]
@d4rky-pl Don't have any conditional statements in my code before the hooks, but I am still getting this error.

**Comment by noopurphalak** [comment]
> This issue has been automatically marked as stale. **If this issue is still affecting you, please leave any comment** (for example, "bump"), and we'll keep it open. We are sorry that we haven't been able to prioritize it yet. If you have any new additional information, please include it with your comment!

Still affecting me...

**Comment by waseem-netsolutions** [comment]
Still affecting me...

**Comment by rinzexe** [comment]
did u solve it?

> > This issue has been automatically marked as stale. **If this issue is still affecting you, please leave any comment** (for example, "bump"), and we'll keep it open. We are sorry that we haven't been able to prioritize it yet. If you have any new additional information, please include it with your comment!
> 
> Still affecting me...

**Comment by Nantris** [comment]
Seeing this in `18.2.0` in exactly one situation.

We are definitely _not_ breaking the rules of hooks and there seems nothing we can do to resolve this. 

**This is a big problem.**

**Comment by Nantris** [comment]
At no time are our dependencies undefined according to conditional breakpoints on the problem hook, and yet in `areHookInputsEqual` the `prevDeps` is undefined - which is made ever more confusing by the fact the component has rendered dozens of times with defined dependencies in those hooks - and yet it's saying the previous deps are undefined?

**Comment by Nantris** [comment]
I tracked down the supposed problem hook. I confirmed nothing was wrong with it according to my knowledge, and then commented it out.

Now instead of the error here, I get:

```
Error: Should have a queue. This is likely a bug in React. Please file an issue.
    at updateReducer (react-dom.development.js:16572:1)
    at updateState (react-dom.development.js:17004:1)
    at Object.useState (react-dom.development.js:17915:1)
    at useState (react.development.js:1622:1)
    at UseState (whyDidYouRender.js:1259:1)
    at useEditExploreCapabilities (hooks.js:11:41)
    at eval (EditorSection.js:147:61)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
```
