### ISSUE TITLE
Await detection in act() is not compatible with react-native

### ISSUE THREAD

**Issue by getsaf** [facebook/react#22634]
I'm posting this here to get some feedback on a potential fix for this issue. I have a work-around (see below) but would like some guidance on whether or not this workaround is sand and satisfies the original intent of the await detection.

[Related issue in `@testing-library/react-native` repo](https://github.com/callstack/react-native-testing-library/issues/379)

### Synopsis
This await detection in `ReactAct` is somewhat incompatible with core.js promise implementation which is used by react-native causing false-positive errors to be dumped to the console.

| `You called act(async () => ...) without await`

### Notes
* The issue only occurs when `act` is wrapped in a module dependency (aka: `@testing-library/react-native`)
* The issue only occurs on the *second* awaited promise in a test

### Version Info
"react-test-renderer": "17.0.2"
"jest": "26.6.3"

### Problem area
https://github.com/facebook/react/blob/a724a3b578dce77d427bef313102a4d0e978d9b4/packages/react/src/ReactAct.js#L95-L97
### Reproduction

```sh
npx react-native init promiseTest
cd promiseTest

# Create a fake node module that wraps act
mkdir node_modules/foo
cat <<EOT > node_modules/foo/wrapAct.js
'use strict';
const  act =  require( 'react-test-renderer').act;
exports.__esModule = true;

exports.default = async function wrapAct(action) {
  await act(action)
}
EOT

# Create a test that uses the module
cat <<EOT > act.test.js
import wrapAct from 'foo/wrapAct';

describe('async', () => {
  it('warns when act is wrapped in a package', async () => {
    await wrapAct(async () => {
      console.log('first');
    });
    await wrapAct(async () => {
      console.log('second');
    });
  });
});
EOT

yarn test
```

### Produces this error
```
 PASS  ./act.test.js
  ● Console

    console.log
      first

      at _callee$ (act.test.js:6:15)

    console.log
      second

      at _callee2$ (act.test.js:9:15)

    console.error
      Warning: You called act(async () => ...) without await. This could lead to unexpected testing behaviour, interleaving multiple act calls and mixing their scopes. You should - await act(async () => ...);

      at printWarning (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:68:30)
      at error (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:44:5)
      at node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15297:13
      at tryCallOne (node_modules/promise/lib/core.js:37:12)
      at node_modules/promise/lib/core.js:123:15
      at flush (node_modules/asap/raw.js:50:29)
```

### Workaround

I have patched the `react-test-renderer` package to use `finally` instead of `Promise.resolve().then(() => {}).then(...)`:
```diff
diff --git a/node_modules/react-test-renderer/cjs/react-test-renderer.development.js b/node_modules/react-test-renderer/cjs/react-test-renderer.development.js
index f401dd2..ac4bb87 100644
--- a/node_modules/react-test-renderer/cjs/react-test-renderer.development.js
+++ b/node_modules/react-test-renderer/cjs/react-test-renderer.development.js
@@ -15292,7 +15292,7 @@ function act(callback) {
     {
       if (typeof Promise !== 'undefined') {
         //eslint-disable-next-line no-undef
-        Promise.resolve().then(function () {}).then(function () {
+        result.finally(() => {}).then(function () {
           if (called === false) {
             error('You called act(async () => ...) without await. ' + 'This could lead to unexpected testing behaviour, interleaving multiple act ' + 'calls and mixing their scopes. You should - await act(async () => ...);');
           }

```
Edits:
* Updated patch to use finally and then combo

**Comment by billnbell** [comment]
let's commit this fix.
