### ISSUE TITLE
react-devtools report Error: Cannot find module './app'

### ISSUE THREAD

**Issue by smoothdvd** [facebook/react#22959]
react-devtools version: 4.22.0
npm -g install react-devtools
react-devtools

```
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './app'
Require stack:
- /Users/foo/.nvm/versions/node/v14.18.1/lib/node_modules/react-devtools/bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.resolve (internal/modules/cjs/helpers.js:99:19)
    at Object.<anonymous> (/Users/foo/.nvm/versions/node/v14.18.1/lib/node_modules/react-devtools/bin.js:32:46)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/foo/.nvm/versions/node/v14.18.1/lib/node_modules/react-devtools/bin.js'
  ]
}
```

**Comment by bvaughn** [comment]
This was broken because of #22949. My apologies.

**Comment by bvaughn** [comment]
Sorry again. We will publish the fix for this tomorrow morning as 4.22.1, along with #22958.

**Comment by bvaughn** [comment]
Fix has been published as 4.22.1. Sorry again.

**Comment by smoothdvd** [comment]
@bvaughn

react-devtools: 4.22.1

<img width="417" alt="Screen Shot 2021-12-15 at 1 09 33 PM" src="https://user-images.githubusercontent.com/22420/146127191-a2476dfd-4f00-4581-9168-4436f51ffae3.png">

 react-devtools: 4.21 has no problem.

**Comment by bvaughn** [comment]
Thanks for confirming, @smoothdvd.
