### ISSUE TITLE
Problem with unique "key" prop

### ISSUE THREAD

**Issue by shreedharhegde99** [facebook/react#22986]
#### Iam using uuid to generate the keys for the list item. But its still showing an error saying
>Warning: Each child in a list should have a unique "key" prop. Check the render method of `List`. See https://reactjs.org/link/warning->keys for more information. at ListItem (http://localhost:3000/static/js/main.chunk.js:488:5) at List(http://localhost:3000/static/js/main.chunk.js:291:5) at div at App

![Error image](https://i.imgur.com/77qjeGR.png)

my codes are as follows

## App component
```
import "./App.css";
import List from "./Components/List/List";
// import ClassExample from "./Components/Classexample";
// import Stateful, { Stateless } from "./Components/State";
// import List from "./Components/List";
// import { Button } from "./Components/Button";
// import { PaymentCard } from "./Components/Card/PaymentCard";

function App() {
  return (
    <div className="App">
      {/* <ClassExample /> */}
      {/* <PaymentCard/> */}
      <List />
    </div>
  );
}

export default App;

```
##  List component
```
import React from "react";
import {v4 as uuidv4} from "uuid"
import { ListItem } from "./ListItem";

export default class List extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      todo: [],
      q: "",
    };
  }

  handleAdd = () => {
    let { q, todo } = this.state;
    let payload = {
      id: uuidv4(),
      title: q,
      status: false,
    };
    this.setState({
      todo: [...todo, payload],
    });
  };

  handleDelete = (id) => {
    const updatedState = this.state.todo.filter((item) => item.id !== id);
    this.setState({
      todo: updatedState,
    });
  };

  handleToggle = (id) => {
    const updatedState = this.state.todo.map((item) =>
      item.id === id ? { ...item, status: !item.status } : item
    );

    this.setState({
      todo: updatedState,
    });
  };

  render() {
    return (
      <div style={{ margin: "50px" }}>
        <div>
          <input
            value={this.state.q}
            onChange={(e) => this.setState({ q: e.target.value })}
            type="text"
          />
          <button onClick={this.handleAdd}>Add</button>
        </div>
        <div>
          {this.state.todo?.map((item, index) => {
            return <ListItem
              id={item.id}
              item={item}
              handleDelete={this.handleDelete}
              handleToggle={this.handleToggle}
            />;
          })}
        </div>
      </div>
    );
  }
}
``` 
##  List Item component
```
import React from "react";


export const ListItem = ({ item, id,handleDelete,handleToggle }) => {
  const style = {};
  if (item.status) {
    style.color = "green";
  } else {
    style.color = "red";
  }

  return (
    <>
      <div style={{ display: "flex", ...style }}>
        <div key={id} onClick={() => handleToggle(item.id)}>
          <p>{item.title}</p>
        </div>
        <button onClick={() => handleDelete(item.id)}>Delete</button>
      </div>
    </>
  );
};
```

**Comment by dylangarcia** [comment]
The `key` has to come from the parent, you don't apply it in the child.

```js
        <div>
          {this.state.todo?.map((item, index) => {
            return <ListItem
              id={item.id}
              key={item.id}
              item={item}
              handleDelete={this.handleDelete}
              handleToggle={this.handleToggle}
            />;
          })}
        </div>
 ```
