### ISSUE TITLE
[DevTools Bug] Could not find node with id "18" in commit tree

### ISSUE THREAD

**Issue by wolfcomp** [facebook/react#23283]
### Website or app

https://github.com/ModelSaber/ModelSaber.Main

### Repro steps

Just try and load the 2/5 and 3/5 report from a reload and start profiling instance.

Change `REACT_APP_API_URL` to `https://apimodelsaber.rainemods.io` in order to launch the app without needing the full .NET 6 environment and the corresponding data in the postgres database.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Could not find node with id "18" in commit tree

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25574:13
    at Map.forEach (<anonymous>)
    at RankedChartBuilder_getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25570:24)
    at ProfilingCache_ProfilingCache.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25686:11)
    at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43680:32)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15400:7)
    at zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16741:7)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19201:86)
    at il (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18756:11)
    at hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18748:23)
```

### Error component stack (automated)

```text
at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43659:34)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35975:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53276:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37375:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37548:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42700:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42146:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30256:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30878:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37927:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53807:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not find node with id  in commit tree in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! Thanks so much for reporting! I tried going through your repro steps but I got this error
<img width="434" alt="image" src="https://user-images.githubusercontent.com/2735514/153947279-736bd14d-7207-4009-946f-4a328a3f2fda.png">

Could you let me know how to fix this so I can start your app or could you maybe make a smaller repro (perhaps in codesandbox) so it's easier for me to test? Thanks!

**Comment by wolfcomp** [comment]
I could possibly setup the dev server to run in Debug mode instead of Release so all of the development scripts are running for React.

I'm also a little confused why you are getting postcss errors when that comes from react-scripts.

**Comment by wolfcomp** [comment]
Update again. 
It seems to revolve around Suspense that causes the crash, and it's only on the Ranked tab and not Flamegraph tab.

**Comment by ImanMahmoudinasab** [comment]
I have the same issue.

`Uncaught Error: Could not find node with id "13" in commit tree`

Version
4.23.0 (1/24/2022)


more info:
```
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25574:13
    at Map.forEach (<anonymous>)
    at RankedChartBuilder_getChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25570:24)
    at ProfilingCache_ProfilingCache.getRankedChartData (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25686:11)
    at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43680:32)
    at gi (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:15400:7)
    at zj (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16741:7)
    at jl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19201:86)
    at il (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18756:11)
    at hl (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:18748:23)
```

```
The error occurred at CommitRankedAutoSizer (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:43659:34)
    at div
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35975:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53276:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37375:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37548:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42700:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42146:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30256:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30878:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37927:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53807:3)
```

> it's only on the Ranked tab and not Flamegraph tab.

The same for me.

**Comment by ImanMahmoudinasab** [comment]
@lunaruan Any update on this issue? This issue stops us from debugging our app.

**Comment by lunaruan** [comment]
Hey, could either of you give me access to the codebase where this crash is happening? Unfortunately without a code repro I'm unable to debug this issue

**Comment by wolfcomp** [comment]
Code: https://github.com/ModelSaber/ModelSaber.Main
Website: https://modelsaber.rainemods.io

The react app is in `ClientApp` in the code base as it is running with an ASP.NET instance as the server

**Comment by bvaughn** [comment]
> If you try and load, https://modelsaber.rainemods.io/ you should get access to the profiler on the page now.

I can repro the error being reported by @wolfcomp by:

1. Reload and profile
2. Click the "Ranked" tab
3. Click on the 2nd commit

**Comment by bvaughn** [comment]
@wolfcomp I tried to checkout the main [modelsaber](https://github.com/modelsaber/modelsaber) repo and get the client running locally so I could narrow down the repro case, but it seems like the READMEs are missing some instructions for how to get things running (like how to start the Apollo server). Any pointers?

**Comment by bvaughn** [comment]
I've got a repro: 
https://codesandbox.io/s/nameless-monad-opbrrv

```js
// Does repro the error

import React, { lazy, Suspense, useEffect } from "react";
import { render } from "react-dom";

function Component({ children = null }) {
  return children;
}

let resolveComponentA = null;
const LazyComponentA = lazy(() => new Promise(resolve => {
  resolveComponentA = () => {
    resolve({ default: Component });
  };
}));

let resolveComponentB = null;
const LazyComponentB = lazy(() => new Promise(resolve => {
  resolveComponentB = () => {
    resolve({ default: Component });
  };
}));

function Index() {
    useEffect(() => {
        setTimeout(() => {
            resolveComponentA();
        }, 500);
    }, []);

    return (
        <React.StrictMode>
            <Suspense fallback={null}>
                <LazyComponentA>
                    <App />
                </LazyComponentA>
            </Suspense>
        </React.StrictMode>
    );
}

function App() {
    useEffect(() => {
        setTimeout(() => {
            resolveComponentB();
        }, 500);
    }, []);

  return <LazyComponentB />;
}

render(<Index />, document.getElementById("root"));
```

I have tried (unsuccessfully so far) to replicate this repro in a Jest test:
```js
// Does not repro the error

function Component({ children = null, label }) {
  return children;
}

let resolveComponentA = null;
const ComponentA = React.lazy(() => new Promise(resolve => {
  resolveComponentA = () => {
    resolve({ default: Component });
  };
}));

let resolveComponentB = null;
const ComponentB = React.lazy(() => new Promise(resolve => {
  resolveComponentB = () => {
    resolve({ default: Component });
  };
}));

function Index() {
  React.useEffect(() => {
    setTimeout(async () => {
      resolveComponentA();
    }, 500);
  }, []);

  return (
    <React.StrictMode>
      <React.Suspense fallback={null}>
        <ComponentA label="A">
          <App />
        </ComponentA>
      </React.Suspense>
    </React.StrictMode>
  );
}

function App() {
  React.useEffect(() => {
    setTimeout(async () => {
      resolveComponentB();
    }, 500);
  }, []);

  return <ComponentB label="B" />;
}

utils.act(() => store.profilerStore.startProfiling());
await utils.actAsync(async () => {
  legacyRender(<Index />, document.createElement('div'));
});
utils.act(() => store.profilerStore.stopProfiling());

const TestRenderer = utils.requireTestRenderer();
const rootID = store.roots[0];

let renderFinished = false;

function Validator({commitIndex, rootID}) {
  const commitTree = store.profilerStore.profilingCache.getCommitTree({
    commitIndex,
    rootID,
  });
  const chartData = store.profilerStore.profilingCache.getRankedChartData(
    {
      commitIndex,
      commitTree,
      rootID,
    },
  );

  renderFinished = true;

  return null;
}

for (let commitIndex = 0; commitIndex < 2; commitIndex++) {
  renderFinished = false;

  utils.act(() => {
    TestRenderer.create(
      <Validator commitIndex={commitIndex} rootID={rootID} />,
    );
  });

  expect(renderFinished).toBe(true);
}
```

**Comment by bvaughn** [comment]
Inspecting DevTools internals after this error has occurred, I can see that the `Store` contains the inner `Component` node:
```
[root]
  ▾ <Index>
    ▾ <Suspense>
      ▾ <Component>
        ▾ <App>
            <Component> <-- This one
```
But for some reason, the tree built up by the `CommitTreeBuilder` _doesn't_ contain the inner `Component` node (or anything beneath the `Suspense` node):
```
1:  (4.2)
•2:Index  (1.899)
••4:Suspense  (0.399)
```
I have occasionally seen the Profiler *not* error (and the `CommitTreeBuilder` contains the node) but most of the time it throws. So there's either a flat out logic error or (worse but maybe more likely?) a race case here.

**Comment by ImanMahmoudinasab** [comment]
@lunaruan any progress on this bug?

**Comment by bvaughn** [comment]
@ImanMahmoudinasab There is a trail of comments on the issue right above yours that show progress.

**Comment by bvaughn** [comment]
#24031 has the fix. Soon as it's reviewed (tomorrow?) we'll release it to NPM and the browsers.

**Comment by ImanMahmoudinasab** [comment]
@bvaughn Thank you for your great work!

**Comment by bvaughn** [comment]
4.24 release will be made today. Fix should roll out as soon as the release goes live.
