### ISSUE TITLE
[DevTools Bug] Cannot read properties of undefined (reading 'skin')

### ISSUE THREAD

**Issue by StefanoA1** [facebook/react#23303]
### Website or app

https://coorpacademy.github.io/components/components/?path=/story/moleculequestionsfreetext--withdefaultvalue

### Repro steps

Using the React dev tools, example: search for moleculequestionsfreetext in the story book, then the context is undefined hence the error (the provider shows that the skin is ok but the context doesn't reach the component - at least for the dev tools, because it actually reaches as the context is used), the patch is easy to get a default value in case it is undefined but it should not be needed because it would only for the devtools' sake.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.23.0-e28a0db22

### Error message (automated)

Cannot read properties of undefined (reading 'skin')

### Error call stack (automated)

```text
at FreeText (https://coorpacademy.github.io/components/components/main.e80d0d6a3191ede6a2b1.bundle.js:1:322446)
    at H (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:13603:5)
    at exports.inspectHooksOfFiber (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:13671:12)
    at inspectElementRaw (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:8426:65)
    at Object.inspectElement (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:8709:38)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:10542:56
    at Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:4225:18)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:4868:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/react_devtools_backend.js:12535:9)
```

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39022:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37375:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37864:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40513:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:33354:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35975:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42520:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37375:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37548:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37518:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42700:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42146:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30256:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:30878:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37927:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:53807:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot read properties of undefined (reading 'skin') in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by lunaruan** [comment]
Hey! Thanks for reporting this bug. Unfortunately, it's really hard to debug this issue without having more of the source code. Could you either provide us with the source code or create a codesandbox or github repro of the issue? Thanks so much!

**Comment by lunaruan** [comment]
Looking more at this, it seems as if your code might be wrong. I can't be sure, but it seems like your component `FreeText` takes `_ref` as a second argument. Function components should only take one argument, props, unless you pass a ref using a [foward ref](https://reactjs.org/docs/forwarding-refs.html). The reason why devtools is crashing here is because you're using function components incorrectly.

However, separately, using function components incorrectly should not crash devtools. Thanks for letting us know! We're working on making devtools less brittle to user error, and we'll add this issue to the list.

Feel free to reopen if you feel like this doesn't answer your question.

**Comment by StefanoA1** [comment]
Hello, thanks for your time @lunaruan & sorry for the delay, sure I can provide the code, the second argument contains the context (not the ref but things as a trad function, skin & others) which is passed with an englobing Provider component:
(the entire code can be found at https://github.com/CoorpAcademy/components/blob/master/packages/@coorpacademy-components/src/molecule/questions/free-text/index.js )

``` javascript
import React, {useCallback, useMemo, useState} from 'react';
import PropTypes from 'prop-types';
import {noop, getOr} from 'lodash/fp';
import {convert} from 'css-color-function';
import Provider from '../../../atom/provider';
import style from './style.css';

const FreeText = (props, context) => {
  const {placeholder = '', value = '', onChange = noop, 'aria-label': ariaLabel} = props;
  const [hovered, setHovered] = useState(false);

  const handleChange = useCallback(e => onChange(e.target.value), [onChange]);
  const primarySkinColor = getOr('#00B0FF', 'skin.common.primary', context);

  const handleMouseOver = useCallback(() => setHovered(true), [setHovered]);

  const handleMouseLeave = useCallback(() => setHovered(false), [setHovered]);

  const shadowBoxPrimaryColor = useMemo(() => convert(`color(${primarySkinColor} a(12%))`), [
    primarySkinColor
  ]);

  return (
    <div
      data-name="freeText"
      className={style.wrapper}
      onMouseOver={handleMouseOver}
      onMouseLeave={handleMouseLeave}
      style={{
        ...(value && {
          boxShadow: hovered ? 'none' : `0 4px 16px ${shadowBoxPrimaryColor}`
        })
      }}
    >
      <input
        data-name="free-text-input"
        type="text"
        aria-label={ariaLabel || value || placeholder}
        className={style.freeText}
        placeholder={placeholder}
        value={value}
        onInput={handleChange}
        onChange={noop}
        style={{
          boxShadow: `0 4px 16px ${shadowBoxPrimaryColor}`,
          ...(value && {
            boxShadow: `0 4px 16px ${
              hovered ? convert(`color(${primarySkinColor} a(20%))`) : shadowBoxPrimaryColor
            }`
          }),
          color: primarySkinColor
        }}
      />
    </div>
  );
};

FreeText.contextTypes = {
  skin: Provider.childContextTypes.skin
};

FreeText.propTypes = {
  placeholder: PropTypes.string,
  value: PropTypes.string,
  onChange: PropTypes.func,
  'aria-label': PropTypes.string
};

export default FreeText;

```
