### ISSUE TITLE
Bug: TypeError elem.nodeName.toLowerCase is not a function

### ISSUE THREAD

**Issue by Theoton** [facebook/react#23324]
React version: 17 +

## Steps To Reproduce

1.window.nodeName exists and does not have a toLowerCase method
2.an error will be reported when the event is triggered, such as clicking on the page

![image](https://user-images.githubusercontent.com/18453647/154606817-e28d1747-1c85-4ce3-b384-35c8e198cad0.png)

[ChangeEventPlugin.js](https://github.com/facebook/react/blob/54f785bc51800556dead12aaedf9594b2f15e836/packages/react-dom/src/events/plugins/ChangeEventPlugin.js)

![image](https://user-images.githubusercontent.com/18453647/154607065-e1d6e87b-6c5a-493a-9e3c-5a7836d14a57.png)

**Comment by sammy-SC** [comment]
Could you please share link for sandbox shown in attached screenshot?

**Comment by Sunilkumarchoudari** [comment]
can you explain more!

**Comment by hiteshk567** [comment]
Tried reproducing this issue in local environment and its **not happening**.
I am able to reproduce in codesandbox only.

**Comment by mesteche** [comment]
Same thing happened to me today.
In my case the culprit was an element on the page which had the unfortunate id `nodeName`.
Turns out that any element having an id anywhere can be accessed through `window.<id>` (I tried on Firefox and Chromium, same behavior).
![image](https://user-images.githubusercontent.com/3534244/157117300-75972184-7726-4458-8fca-fb76b413f94a.png)
So when [this line](https://github.com/facebook/react/blob/54f785bc51800556dead12aaedf9594b2f15e836/packages/react-dom/src/events/plugins/ChangeEventPlugin.js#L80) is hit, the check of having `nodeName` as a property is not enough to safely call toLowerCase on it.
Not sure what the fix should be though. In my case, replacing `id` by `data-id` is fine but I'm not sure everyone has this possibility.

**Comment by Theoton** [comment]
> 

There is no way to prevent someone from using `nodeName` in the project，just like your scene.
https://codesandbox.io/s/bold-phoebe-xbiqcj?file=/src/App.js

@sammy-SC @Sunilkumarchoudari @hiteshk567

**Comment by eps1lon** [comment]
> [codesandbox.io/s/bold-phoebe-xbiqcj?file=/src/App.js](https://codesandbox.io/s/bold-phoebe-xbiqcj?file=/src/App.js)

The linked codesandbox didn't include a repro.

I can reproduce it (though not 100%) in https://codesandbox.io/s/window-nodename-extractevents-crligx though.

**Comment by wangyg115** [comment]
I runs into similar issue, with a  `TextField ` named nodeName, at SSR.

```tsx
<TextField  name="nodeName" /> 
```
react-dom version: 18.2.0
error info:
```    
react-dom.development.js:11187 
Uncaught TypeError: instance.nodeName.toLowerCase is not a function
    at canHydrateInstance (react-dom.development.js:11187:86)
    at tryHydrate (react-dom.development.js:12441:24)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12532:8)
    at updateHostComponent (react-dom.development.js:19902:5)
    at beginWork (react-dom.development.js:21618:14)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26560:12)
```

**Comment by FrominXu** [comment]
> Could you please share link for sandbox shown in attached screenshot?

I get this bug is the same as [mesteche] https://github.com/facebook/react/issues/23324#issuecomment-1061144768 said.

My Component's jsx just like this:
<Form>
<Input name ="nodeName"/>
<Input name="others"/>
</Form>

And when the mouse pointerover the Form element,  react-dom code:
```
  h = d ? pb(d) : window;
  k = h.nodeName && h.nodeName.toLowerCase();
  if ("select" === k || "input" === k && "file" === h.type)
```
The h refer to the Form, But , as this link said :
https://stackoverflow.com/questions/6503764/form-elements-as-properties-of-the-form
the Form has a property named nodeName which is the first field object inside it.

so, the k is not the right object 'Form' but the field object form.nodeName. so ,elem.nodeName.toLowerCase is not a function.

**Comment by daxiazilong** [comment]
+1
Same issue, when I set the name of Input (ANTD Form component) width 'nodeName'
