### ISSUE TITLE
Bug: RC1 Cannot create property '_updatedFibers' when using createRoot

### ISSUE THREAD

**Issue by drcmda** [facebook/react#24049]
React version: RC1

## Steps To Reproduce

❌

```jsx
import { createRoot } from 'react-dom/client'
import { Suspense } from 'react'
import { App } from './App'

createRoot(document.getElementById('root')).render(
  <Suspense fallback={null}>
    <App />
  </Suspense>
)
```

Link to code example: https://codesandbox.io/s/building-live-envmaps-forked-j334tc?file=/src/index.js

This worked in RC0. It seems to have a problem with this component: https://github.com/pmndrs/react-three-fiber/blob/v8/packages/fiber/src/web/Canvas.tsx#L41-L47

It starts to work again when using the old `render` method.

✅

```jsx
import { render } from 'react-dom'
import { Suspense } from 'react'
import { App } from './App'

render((
  <Suspense fallback={null}>
    <App />
  </Suspense>
), document.getElementById('root'))
```

#### stack trace

```text
Uncaught TypeError: Cannot create property '_updatedFibers' on number '0'
    at requestUpdateLane (j334tc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:25238:35)
    at dispatchSetState (j334tc.csb.app/node_modules/react-dom/cjs/react-dom.development.js:17324:14)
    at ErrorBoundary.componentDidCatch (j334tc.csb.app/node_modules/@react-three/fiber/dist/react-three-fiber.esm.js:264:16)
    at ErrorBoundary.callback (j334tc.csb.app/node_modules/react-reconciler/cjs/react-reconciler.development.js:9871:12)
    at callCallback (j334tc.csb.app/node_modules/react-reconciler/cjs/react-reconciler.development.js:4397:12)
    at commitUpdateQueue (j334tc.csb.app/node_modules/react-reconciler/cjs/react-reconciler.development.js:4418:9)
    at commitLayoutEffectOnFiber (j334tc.csb.app/node_modules/react-reconciler/cjs/react-reconciler.development.js:14829:13)
```

**Comment by drcmda** [comment]
never mind, there is a rc2 now, or it was there before and i didn't see it. i don't see the error no more :-)
