### ISSUE TITLE
Bug: Using lerna-managed react projects, an error is reported after ssr is enabled and packaged

### ISSUE THREAD

**Issue by see** [facebook/react#24257]
React version: 17.0.2

## Steps To Reproduce

1. yarn install
2. yarn build:admin-react
3. node server2

Link to code example:
https://github.com/see/ssr-demo

## The current behavior

```
(node:97731) UnhandledPromiseRejectionWarning: Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at R (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:5394)
    at t.useContext (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:7108)
    at C (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:14117)
    at A (/Users/ying/workspace/FEProjects/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:15285)
    at processChild (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/ying/workspace/FEProjects/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at /Users/ying/workspace/FEProjects/ssr-demo/server2.js:29:22
(Use `node --trace-warnings ...` to show where the warning was created)
(node:97731) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

**Comment by see** [comment]
I don't know if it's a problem with the react library or the learn library, so I also submitted an issue in the lerna project

lerna/lerna#3100

**Comment by gaearon** [comment]
The production error message contains a link to decode it. If you follow that link and read the decoded message, it contains another link which explains the issue (you have multiple copies of React) and common ways to debug it.

**Comment by see** [comment]
I have followed the information in the link and I have no problem with my code and ssr works fine without using learn

**Comment by gaearon** [comment]
The problem you’re running into is described here. 

https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react

That’s the most we can help you with — you need to figure out as a Lerna user how to avoid having a duplicate installation.

**Comment by see** [comment]
I suspect that it is caused by the yarn workspace. I set useWorkspaces to false when integrating learn, and everything is normal

**Comment by gaearon** [comment]
Looking at this stack trace:

```
Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at R (/Users/dan/p/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:5394)
    at t.useContext (/Users/dan/p/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:7108)
    at C (/Users/dan/p/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:14117)
    at A (/Users/dan/p/ssr-demo/dist/admin-react/node/static/js/main.01e60cfb.js:2:15285)
    at processChild (/Users/dan/p/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/Users/dan/p/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/Users/dan/p/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/Users/dan/p/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at renderToString (/Users/dan/p/ssr-demo/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at /Users/dan/p/ssr-demo/server2.js:29:22
```

you can see that some React internals are in `node_modules/react-dom`:

```

**Comment by gaearon** [comment]
Here's a fix. https://github.com/see/ssr-demo/pull/1

https://stackoverflow.com/a/53453054/458193

**Comment by see** [comment]
thanks.
