### ISSUE TITLE
Bug: Internal React error: Expected static flag was missing

### ISSUE THREAD

**Issue by Developer-Nijat** [facebook/react#24391]
React version: V18.0.0
React router DOM: V5.2.1

## Steps To Reproduce

1. Going to profile page
2. Warning: Internal React error: Expected static flag was missing. Please notify the React team.

Link to code example:
![Screenshot 2022-04-17 124859](https://user-images.githubusercontent.com/51002164/163707500-3ee1ca51-9695-4e2e-b3c4-3f5e8f7a98b3.png)
DynamicFilter.js component
![Screenshot 2022-04-17 125107](https://user-images.githubusercontent.com/51002164/163707576-b8536b98-3b47-4c7e-84f3-abfa9f93dddf.png)

**Comment by gaearon** [comment]
Please provide a reproducible example. Either on GitHub or a sandbox. Otherwise we can’t really fix this. Thanks!

**Comment by Developer-Nijat** [comment]
> Please provide a reproducible example. Either on GitHub or a sandbox. Otherwise we can’t really fix this. Thanks!

Probably it is not possible. Because this is the large project and totally code sharing is prohibited. It is understandable, React v18 is not good for old projects.

**Comment by gaearon** [comment]
> It is understandable, React v18 is not good for old projects.

That's absolutely not correct. We're running huge codebases from 2013-2014 with almost no changes on React 18. The error is just a bug in React that will be easy to fix as soon as somebody gives us a reproducible example.

>Probably it is not possible. Because this is the large project and totally code sharing is prohibited.

Usually the way you can do this is by deleting code until you're left with a small example that doesn't contain any app-specific logic.

**Comment by orangecoding** [comment]
@gaearon Here's a small test repo, that will reproduce the bug.
https://github.com/orangecoding/react-static-flag-exception

**Comment by gaearon** [comment]
Thank you! This example seems to use a Hook conditionally — `it (data) useStyles()`. This is not supported in React. If you use Hooks you need to either follow rules or use the linter rule which forbids this.

**Comment by orangecoding** [comment]
Yeah I know this. Unfortunatelly lot's of ppl doesn't seem to know this and this is a common thing that I'm seeing throughout a lot of libs. I copied this particular issue from here: https://github.com/farahat80/react-open-weather/blob/master/src/js/components/ReactWeather.js#L20

Going back to react 17, these things work without any issues...

**Comment by orangecoding** [comment]
I fear that when this is going to be thrown as an error (which it actually is, no discussion here), a lot of external libs will be broken. 
However not sure if this is the only case where such an error occures. Maybe @Developer-Nijat can check this with his code as well?

**Comment by Developer-Nijat** [comment]
> I fear that when this is going to be thrown as an error (which it actually is, no discussion here), a lot of external libs will be broken. 
> However not sure if this is the only case where such an error occurs. Maybe @Developer-Nijat can check this with his code as well?

First of all, let's say this is not understandable error.  We can't figure out where the error is.  Again there is a high risk of errors in the next days.  Currently v18 is risk for large projects. I will check this error again but

**Comment by firoz2580** [comment]
The issue is exactly as what @gaearon said.
In my case, the very first line of the component was checking a prop 'hidden' and returning a fragment if it is true.
That was causing this error. Though it was not a best practice, V17 was OK with this.


`// SidebarItem.tsx
// Issue
interface SidebarItemProps {
  hidden: boolean
}
const SidebarItem: FC<SidebarItemProps> = ({ hidden }) => {
  if (hidden) return <></>
  const navigate = useNavigate()

  return (
    <div>{
      // Some JSX
    }</div>
  )
}`

The fix was to do the check after initiating the hook. 
`
// Fix
const SidebarItem: FC<SidebarItemProps> = ({ hidden }) => {
  const navigate = useNavigate()
  if (hidden) return <></>

  return (
    <div>{
      // Some JSX
    }</div>
  )
}
`

**Comment by eps1lon** [comment]
Reproducible if an additional `useEffect` was called: https://codesandbox.io/s/conditional-useeffect-static-flag-was-missing-gg94qy

An additional `useState` will throw the expected "rendered more hooks than expected" error.

**Comment by gaearon** [comment]
>Though it was not a best practice, V17 was OK with this.

I want to make it clear that it worked accidentally and in a narrow range of circumstances. You should absolutely not rely on this. For example, any person who adds state to the corresponding custom Hook would break every component relying on this even in 17.

I agree it’s a problem that the error is unclear and removed from the actual case. That has to be fixed.

But this has nothing to do with 18. If your code relies on this, it is extremely fragile in 17. Enable the linter and fix it.

**Comment by orangecoding** [comment]
> Enable the linter and fix it.
As I said, I saw these things in at least 2 external debts (one of which is semantic-ui-react which has millions of downloads). So yeah, I agree it kinda has to be fixed by the vendor, however I guess this deserves some major communication efforts, coz otherwise ppl will most likely not update their libs (I guess)

**Comment by FabrizioArmango** [comment]
I had the same warning migrating from v17 to v18:

#### Before
``` js
const C = () =>  {
    if (condition) return null;
    useEffect(() => {/*...*/}, []);
    return <div></div>
}
```

#### After
``` js
const C = () =>  {
    useEffect(() => {/*...*/}, []);
    if (condition) return null;
    return <div></div>
}
```
The above change solved.

Thanks.

**Comment by joeelmahallawy** [comment]
I can confirm, I get the same error: "Expected static flag was missing. Please notify the React team." with the code below:
```js
import React, { useMemo } from "react";
import { useTable, useSortBy, usePagination } from "react-table";

const JSONTable = ({ arr }: { arr?: object[] }) => {

  if (!arr?.length) return null;

  const data = useMemo(() => arr, [arr]);

  const keys = Object.keys(arr[0]);

  const columns = useMemo(
    () => keys.map((key) => ({ Header: key, accessor: key })),
    [arr]
  );

  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow,
    page, // Instead of using 'rows', we'll use page,
    // which has only the rows for the active page

    // The rest of these things are super handy, too ;)
    canPreviousPage,
    canNextPage,
    pageOptions,
    pageCount,
    gotoPage,
    nextPage,
    previousPage,
    setPageSize,
    state: { pageIndex, pageSize },
  } = useTable(
    { columns, data, initialState: { pageIndex: 0 } },
    useSortBy,
    usePagination
  );

  return null;
}
  ```
However, I stop getting the error when I remove the following code below:
```js
  const {
    getTableProps,
    getTableBodyProps,
    headerGroups,
    rows,
    prepareRow,
    page, // Instead of using 'rows', we'll use page,
    // which has only the rows for the active page

    // The rest of these things are super handy, too ;)
    canPreviousPage,
    canNextPage,
    pageOptions,
    pageCount,
    gotoPage,
    nextPage,
    previousPage,
    setPageSize,
    state: { pageIndex, pageSize },
  } = useTable(
    { columns, data, initialState: { pageIndex: 0 } },
    useSortBy,
    usePagination
  );
```

**Comment by gaearon** [comment]
The issue is the early return. Put the return after calls to Hooks. Please add the linter to your setup to detect these issues at compile time as originally intended.

**Comment by ahuigo** [comment]
> The issue is the early return. Put the return after calls to Hooks. Please add the linter to your setup to detect these issues at compile time as originally intended.

Bad case: https://codepen.io/ahuigo/pen/YzOVPQv

**Comment by 3mper0r** [comment]
Just ran at this error trying to validate forms within Modal with zod validation library and react hook form. Basically the error was coming when I was checking (conditional rendering) for the modal and I was doing before the useForm hook of react-hook-form.

The lesson here is: when you have any kind of hooks always do your conditional renderings at the bottom right before returning your jsx/tsx!

**Comment by vilelalabs** [comment]
> The issue is exactly as what @gaearon said. In my case, the very first line of the component was checking a prop 'hidden' and returning a fragment if it is true. That was causing this error. Though it was not a best practice, V17 was OK with this.
> 
> SidebarItem.tsx Issue: ![image](https://user-images.githubusercontent.com/32398477/164969104-bfd3c094-0e40-4ed1-bded-21080e1e5290.png)
> 
> The fix was to do the check after initiating the hook.
> 
> Fix: ![image](https://user-images.githubusercontent.com/32398477/164969146-69fc0361-5e42-4cd3-998a-71c74991a788.png)

totally solved my problem. 

I had in code 

```
    if (!visible) return null;
    const proModal = useProModal();
```
and just moved up of component return:
```
    const proModal = useProModal();
    if (!visible) return null;
```

**Comment by Josema** [comment]
Similar issue here. I am using react-native-web:
```
"react": "18.2.0",
"react-dom": "18.2.0",
"react-native": "0.71.8",
"react-native-web": "~0.18.10",
```

Is a simple hook that does this:
```js
    const [cards, setCards] = useState([])

    useEffect(() => {
        ;(async () => {
            try {
                const cards = await Server.userCards({ user_id })
                setCards(cards)
            } catch (error) {
                //
            }
        })()
    }, [user_id, setCards])
```

If a comment the line `setCards(cards)` I don't get any error.
```
react-dom.development.js:86 Warning: Internal React error: Expected static flag was missing. Please notify the React team.
    at Deck (http://localhost:19006/static/js/bundle.js:27119:20)
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:9361:24
    at ScrollView (http://localhost:19006/static/js/bundle.js:39905:37)
    at ScrollView
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:7859:24
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at Lobby (http://localhost:19006/static/js/bundle.js:26652:23)
    at Cards (http://localhost:19006/static/js/bundle.js:27938:79)
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at div
    at http://localhost:19006/static/js/bundle.js:13035:25
    at http://localhost:19006/static/js/bundle.js:33953:45
    at Views (http://localhost:19006/static/js/bundle.js:25587:79)
    at App (http://localhost:19006/static/js/bundle.js:25525:70)
    at withDevTools(App)
```

**Comment by adaboese** [comment]
Getting this when using `@sentry/react`.

```ts
import { captureRemixErrorBoundaryError, withSentry } from '@sentry/remix';

const Root = () => {};

const RootWithSentry = withSentry(Root);

export default Root;
```

**Comment by rickhanlonii** [comment]
@adaboese I'm not able to reproduce that example in a new Remix project, can you provide a full repro? I want to rule out the known issue above that hooks are being called conditionally.

**Comment by adaboese** [comment]
> @adaboese I'm not able to reproduce that example in a new Remix project, can you provide a full repro? I want to rule out the known issue above that hooks are being called conditionally.

That turned out to be a false-positive.

Although I am not clear why adding/removing `withSentry` caused the issue/made it go away, but I am pretty sure that the issue is actually with this package. https://github.com/edmundhung/conform/issues/375#issuecomment-1887514277

**Comment by andylovescode** [comment]
This is an important issue to fix, although with a little bit of googling you can figure out *what is causing this error*, having a proper error message would allow React to tell the developer *where* they should look for their conditional hooks to fix, as right now it's a bit of a pain to figure out where to look.

**Comment by Owhab** [comment]
`import { RootState, useAppSelector } from "@/store";

export const getLocationNameById = (id: number | string): string => {
  const { locations } = useAppSelector((state: RootState) => state.locations);
  const location = locations.find(
    (location) =>
      location.posID === parseInt(String(id), 10) || location.posID === id
  );
  return location ? location.locationName : "Unknown Location";
};`



I am getting the same error 
` ERROR  Warning: Internal React error: Expected static flag was missing. Please notify the React team.
`
when calling `getLocationNameById` this function.

**Comment by tu2-atmanand** [comment]
I recently updated my packages and since then started getting this exact error. 

Although this error is not causing any issues from the user's perspective. But, not sure if this is causing extra re-rendering or whatever is going on behind the scenes.

Current version when the issue started happening: 
```bash
node: v24.14.0
├── @types/react-dom@19.2.3
├── @types/react@19.2.14
├── react-dom@19.2.5
├── react@19.2.5
```

### Error

<img width="1920" height="154" alt="Image" src="https://github.com/user-attachments/assets/cd19f933-5c2f-4582-8895-04ad44334452" />

The error message is shown as many times as my LazyColumn.tsx component is rendered on the screen.

### Approaches

I have used two approaches, in both the approaches the issue is shown...

**Approach 1 :** [Creating a memoized component for a sub-component](https://github.com/tu2-atmanand/Task-Board/blob/38ba85e1cfb0cbd24c2e193fcee2ffa24ff04f48/src/components/KanbanView/LazyColumn.tsx#L973).
**Approach 2 :** [Using `React.createElement()` to render this sub-component](https://github.com/tu2-atmanand/Task-Board/blob/7e7707c354c1a62aeb988689594b3fedb367c5dd/src/components/KanbanView/LazyColumn.tsx#L924).

AI is taking me in circles, not able to find the correct fix which can hide this error message entirely.

## Edit : The issue has been fixed

The reason was indeed hooks mismatch between previous and next renders which was mainly happening because of early conditional returns. Here is the complete analysis with the updated commit : https://github.com/tu2-atmanand/Task-Board/issues/771
