### ISSUE TITLE
[DevTools Bug]: Error in event handler: Error: Attempting to use a disconnected port object

### ISSUE THREAD

**Issue by himankpathak** [facebook/react#24417]
### Website or app

https://codesandbox.io/s/blissful-raman-2on7k2

### Repro steps

1. Create a react app 
```
yarn create react-app test-react
cd test-react
yarn start
```
2. Create `.env.development` file in root.
```
HTTPS=true
PORT=4100
BROWSER=none
```
3. Visit https://localhost:4100/ in Chrome v100.0.4896.127
4. Open React Devtools by inspecting page, some times it shows `Components` tab but in large application it does not show the `Components` tab. If it shows the tab the error message is sent to dev tools every second.
5. See error message in [chrome://extensions/](chrome://extensions/)
6. This is not reproducible in Firefox v99.0.1.

### How often does this bug happen?

Every time

### DevTools version (automated)

`4.24.3 (3/30/2022)`

### Error message (automated)

`Error in event handler: Error: Attempting to use a disconnected port object`

### Error call stack (automated)
`build/background.js:139 (lOne)`

```
/******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/build/";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 115);
/******/ })
/************************************************************************/
/******/ ({

/***/ 115:
/***/ (function(module, exports, __webpack_require__) {

"use strict";
/* global chrome */


const ports = {};
const IS_FIREFOX = navigator.userAgent.indexOf('Firefox') >= 0;
chrome.runtime.onConnect.addListener(function (port) {
  let tab = null;
  let name = null;

  if (isNumeric(port.name)) {
    tab = port.name;
    name = 'devtools';
    installContentScript(+port.name);
  } else {
    tab = port.sender.tab.id;
    name = 'content-script';
  }

  if (!ports[tab]) {
    ports[tab] = {
      devtools: null,
      'content-script': null
    };
  }

  ports[tab][name] = port;

  if (ports[tab].devtools && ports[tab]['content-script']) {
    doublePipe(ports[tab].devtools, ports[tab]['content-script']);
  }
});

function isNumeric(str) {
  return +str + '' === str;
}

function installContentScript(tabId) {
  chrome.tabs.executeScript(tabId, {
    file: '/build/contentScript.js'
  }, function () {});
}

function doublePipe(one, two) {
  one.onMessage.addListener(lOne);

  function lOne(message) {
    two.postMessage(message);
  }

  two.onMessage.addListener(lTwo);

  function lTwo(message) {
    one.postMessage(message);
  }

  function shutdown() {
    one.onMessage.removeListener(lOne);
    two.onMessage.removeListener(lTwo);
    one.disconnect();
    two.disconnect();
  }

  one.onDisconnect.addListener(shutdown);
  two.onDisconnect.addListener(shutdown);
}

function setIconAndPopup(reactBuildType, tabId) {
  chrome.browserAction.setIcon({
    tabId: tabId,
    path: {
      '16': 'icons/16-' + reactBuildType + '.png',
      '32': 'icons/32-' + reactBuildType + '.png',
      '48': 'icons/48-' + reactBuildType + '.png',
      '128': 'icons/128-' + reactBuildType + '.png'
    }
  });
  chrome.browserAction.setPopup({
    tabId: tabId,
    popup: 'popups/' + reactBuildType + '.html'
  });
}

function isRestrictedBrowserPage(url) {
  return !url || new URL(url).protocol === 'chrome:';
}

function checkAndHandleRestrictedPageIfSo(tab) {
  if (tab && isRestrictedBrowserPage(tab.url)) {
    setIconAndPopup('restricted', tab.id);
  }
} // update popup page of any existing open tabs, if they are restricted browser pages.
// we can't update for any other types (prod,dev,outdated etc)
// as the content script needs to be injected at document_start itself for those kinds of detection
// TODO: Show a different popup page(to reload current page probably) for old tabs, opened before the extension is installed


if (!IS_FIREFOX) {
  chrome.tabs.query({}, tabs => tabs.forEach(checkAndHandleRestrictedPageIfSo));
  chrome.tabs.onCreated.addListener((tabId, changeInfo, tab) => checkAndHandleRestrictedPageIfSo(tab));
} // Listen to URL changes on the active tab and update the DevTools icon.


chrome.tabs.onUpdated.addListener((tabId, changeInfo, tab) => {
  if (IS_FIREFOX) {
    // We don't properly detect protected URLs in Firefox at the moment.
    // However we can reset the DevTools icon to its loading state when the URL changes.
    // It will be updated to the correct icon by the onMessage callback below.
    if (tab.active && changeInfo.status === 'loading') {
      setIconAndPopup('disabled', tabId);
    }
  } else {
    // Don't reset the icon to the loading state for Chrome or Edge.
    // The onUpdated callback fires more frequently for these browsers,
    // often after onMessage has been called.
    checkAndHandleRestrictedPageIfSo(tab);
  }
});
chrome.runtime.onMessage.addListener((request, sender) => {
  var _request$payload, _ports$id;

  const tab = sender.tab;

  if (tab) {
    const id = tab.id; // This is sent from the hook content script.
    // It tells us a renderer has attached.

    if (request.hasDetectedReact) {
      // We use browserAction instead of pageAction because this lets us
      // display a custom default popup when React is *not* detected.
      // It is specified in the manifest.
      setIconAndPopup(request.reactBuildType, id);
    } else {
      switch ((_request$payload = request.payload) === null || _request$payload === void 0 ? void 0 : _request$payload.type) {
        case 'fetch-file-with-cache-complete':
        case 'fetch-file-with-cache-error':
          // Forward the result of fetch-in-page requests back to the extension.
          const devtools = (_ports$id = ports[id]) === null || _ports$id === void 0 ? void 0 : _ports$id.devtools;

          if (devtools) {
            devtools.postMessage(request);
          }

          break;
      }
    }
  }
});

/***/ })

/******/ });
```

**Comment by lunaruan** [comment]
Hey! Thanks for reporting. This is a known Chrome issue that is targeted to be fixed in v102. Check out #24093 for a list of potential workarounds. Closing this because it's a duplicate.

**Comment by woody-li** [comment]
@lunaruan The bug still exists with Chrome 115 and devTool 4.28.0.
Could you provide chromium issue link about it?

**Comment by franva** [comment]
I still have the issue in Chrome Version 120.0.6099.225 (Official Build) (64-bit).

**Comment by michaelycy** [comment]
版本 120.0.6099.234（正式版本） (arm64)   +1

**Comment by woody-li** [comment]
Still exists with Chrome 121 and devTool 5.0.0

**Comment by Esty12** [comment]
+1

**Comment by pninaPolchak** [comment]
i also

**Comment by GOWxx** [comment]
I still have the issue in `Chromium 122(arm64)` with `React Developer Tools@5.0.2`

**Comment by puskuruk** [comment]
Unfortunately, I also have this issue. Details:
```
Chrome: 119.0.6045.123 (Official Build) (arm64) 
```

```
React Developer Tools: 5.0.2 (3/8/2024)
```

**Comment by muyiyr** [comment]
+1
Chrome Version 123.0.6312.87 (Official Build) (x86_64)
DevTools Version: 5.0.2
![img_v3_029q_5dfd989c-4863-4640-bf42-d0e7eb059e4g](https://github.com/facebook/react/assets/32588751/7cc5cacd-4bd6-4c1d-8573-e50fafe39dfd)

**Comment by tylerjc** [comment]
Still occurring:

```
React Developer Tools Version
5.1.0 (4/15/2024)
```
```
Chrome Version (MacBook)
Version 124.0.6367.80 (Official Build) (x86_64)
```

**Comment by thomastvedt** [comment]
I get this error message on each hot reload:

<img width="1368" alt="image" src="https://github.com/facebook/react/assets/4746639/f2680733-89dd-453f-8f39-9f08ca0434fc">

<img width="843" alt="image" src="https://github.com/facebook/react/assets/4746639/f35ecc25-4f0e-4a0d-90ac-735422a817ab">

browser:
Arc Version 1.44.2 (50412)
Chromium Engine Version 125.0.6422.112

DevTools version:
[5.2.0-1717ab0171](https://github.com/facebook/react/blob/main/packages/react-devtools/CHANGELOG.md#520)

**Comment by LukeParsnip** [comment]
I am getting this error a lot and have yet to actually nail down what triggers it because it seems to happen so randomly. I'll occasionally leave my devtools open to go for lunch and come back to hundreds of console errors, of which 95% are this error (and the other 5% are my garbage code)

![image](https://github.com/facebook/react/assets/155459875/70b466cd-8ba1-4bab-ae43-409db5a2ac89)

Stack for reference 

![image](https://github.com/facebook/react/assets/155459875/8c98ec83-8e57-4459-a42b-e418a9299116)

Version 125.0.6422.114 (Official Build) (64-bit)

**Comment by vavanv** [comment]
any ideas for a fix/work around?

**Comment by mohitmohlia** [comment]
I am facing this issue too. This especially starts arising when i open dev tools and while debugging in source tab

**Comment by Lord-Leonard** [comment]
+1

**Comment by aikrez** [comment]
Chrome Version 127.0.6533.89 (Official Build) (64-bit)
React developer tools 5.3.1 (7/3/2024)

`Uncaught Error: Attempting to use a disconnected port object
    at handleMessageFromPage (proxy.js:1:779)`

**Comment by vavanv** [comment]
Hey fellas, I have disabled **React Developer Tools** extension and so far no this uncaught error during debugging

**Comment by sKopheK** [comment]
it's still alive :(

**Comment by alexdev888** [comment]
+1

**Comment by darmawan01** [comment]
+1

**Comment by fgerges** [comment]
+1

**Comment by asimsoroya** [comment]
Experienced when doing hot refresh of the components. Uncaught Error: Attempting to use a disconnected port object

Uncaught Error: Attempting to use a disconnected port object
    at handleMessageFromPage (proxy.js:1:779)

**Comment by MADrickx** [comment]
Still experiencing this with latest devtools

**Comment by jiangxiaoqiang** [comment]
still facing the issue with google chrome 129.

**Comment by LTS2** [comment]
It will still be called.

**Comment by Nantris** [comment]
This makes debugging such a huge pain in the ass. God forbid you pause the script to debug for a minute - the whole page practically becomes unusable unless you skip all breakpoints - and adding a "Never pause here" does nothing.

This really needs to be addressed.

**Comment by Nantris** [comment]
@poteto @sebmarkbage I'm sorry to ping but this issue is very old, closed, and an absolute plague. Can someone please comment on the potential to truly resolve this?

**Comment by hoxyq** [comment]
> This makes debugging such a huge pain in the ass. God forbid you pause the script to debug for a minute - the whole page practically becomes unusable unless you skip all breakpoints - and adding a "Never pause here" does nothing.
> 
> This really needs to be addressed.

Hey, thanks for flagging this. As I understand, you are getting this error in the console while you are paused in debugger?

Can you please share steps how I can reproduce this? Is hitting a breakpoint and waiting until extension port becomes dead enough?

**Comment by Nantris** [comment]
Thanks very much for your reply @hoxyq!

> Is hitting a breakpoint and waiting until extension port becomes dead enough?

Yep, that's all it takes. I'm not sure how long you have to wait, but maybe 30-60 seconds. Specifically we're seeing this in Electron (which I'm not sure is relevant) but it's the only environment I'm working in so I can't attest to the behavior elsewhere with certainty.

I am way overloaded at the moment, but when time allows I'd be happy to throw together a repro case.

Short of that, I assume loading up [electron-react-boilerplate](https://github.com/electron-react-boilerplate/electron-react-boilerplate) would be sufficient since it auto-installs React-Devtools last I checked, though it is quite outdated now.

Thanks again for the reply!

**Comment by tulipandmills** [comment]
I can confirm I am experiencing the same problem in my vita-react project. Just hitting a breakpoint and wait

**Comment by leonardoraele** [comment]
Still happens in Chrome 134

**Comment by Gavinluo** [comment]
Still happens in Chrome 136

**Comment by Dorious** [comment]
Still getting this damn thing:
Edge 142.0.3595.94
React Dev Tools 7.0.1

It's so damn annoying!

**Comment by Sayedabutahir** [comment]
Still happens in Edge

Edge: 145.0.3800.82 
React Dev Tools: 7.0.1

**Comment by daniele-orlando** [comment]
Chrome: 148.0.7778.97
React Developer Tools: 7.0.1 (10/20/2025)
