### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by danbart909** [facebook/react#24559]
### Website or app

[expo init](https://codesandbox.io/s/new)

### Repro steps

All you have to do is use 'expo init' or 'npx create-react-native-app' and make a fresh app with a blank template. When I open it with 'expo start' or 'npm start' I get this message every time in the debugger.

When I press the 'dismiss' button, I get a box that says:
'Unsupported DevTools backend version
You are running react-devtools version 4.14.0-d0ec283819.
This requires bridge protocol version 1. However the current backend version uses bridge protocol version 2.
To fix this, upgrade the DevTools NPM package: npm i -g react-devtools@^4.22.0'

I follow all the steps I can find to solve the issue (including yarn resolutions, updating node.js and packages, etc.) but nothing works at all.

I cannot initialize new apps without getting the error. I really want this debugger to work again.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.14.0-d0ec283819

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:140545
    at c.emit (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:89515)
    at G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:90986
    at G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:347787
    at Array.forEach (<anonymous>)
    at S.Gc.e.onmessage (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:48:347771)
    at S.n (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:40:3009)
    at S.emit (events.js:315:20)
    at e.exports.P (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:9318)
    at e.exports.emit (events.js:315:20)
    at e.exports.dataMessage (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:15409)
    at e.exports.getData (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:14651)
    at e.exports.startLoop (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:12066)
    at e.exports._write (G:\Workspace\rn-debugger-windows-x64\resources\app.asar\node_modules\react-devtools-core\dist\standalone.js:8:11421)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by danbart909** [comment]
Finally found the fix:

1. remove react-devtools-core from global dependencies

2. create new project using 'expo init --npm'

3. npm i react-devtools-core@4.14.0 in project folder

4. added the following to package.json:
"overrides": {
  "react-native": {
    "react-devtools-core": "4.14.0"
  }
},

5. remove node_modules and package-lock.json

6. yarn install
