### ISSUE TITLE
[DevTools Bug] Cannot remove node "0" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by nitish24p** [facebook/react#24818]
### Website or app

React Native App

### Repro steps

1. Run react native app
2. npx react-devtools
3. adb reverse tcp:8097 tcp:8097
4. reload the app, this error should come as mentioned below

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.24.7-7f673317f

### Error message (automated)

Cannot remove node "0" because no matching node was found in the Store.

### Error call stack (automated)

```text
at /Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:48:333971
    at f.emit (/Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:48:279464)
    at /Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:48:281005
    at /Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:48:667650
    at Array.forEach (<anonymous>)
    at A.e.onmessage (/Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:48:667634)
    at A.t (/Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:39:2838)
    at A.emit (events.js:315:20)
    at e.exports.L (/Users/300037427/.npm/_npx/64332/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:3:58322)
    at e.exports.emit (events.js:315:20)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by nitish24p** [comment]
@lunaruan My app was using 4.14.0 and i explicitly installed that version of devtools and things worked.. One question, can this be the reason for the issue, the major version mismatch?

**Comment by lunaruan** [comment]
@nitish24p Yes, a version mismatch would cause this problem. In later versions of DevTools, we warn if you have a version mismatch, but in earlier ones unfortunately we don't have that warning. Closing this! Glad it worked for you!
