### ISSUE TITLE
[DevTools Bug] Cannot remove node "0" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by Mass812** [facebook/react#24870]
### Website or app

Bitbucket repo

### Repro steps

just npm react-devtools and run

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.24.7-7f673317f

### Error message (automated)

Cannot remove node "0" because no matching node was found in the Store.

### Error call stack (automated)

```text
at /Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:333971
    at f.emit (/Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:279464)
    at /Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:281005
    at /Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:667650
    at Array.forEach (<anonymous>)
    at A.e.onmessage (/Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:667634)
    at A.t (/Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:39:2838)
    at A.emit (events.js:315:20)
    at e.exports.L (/Users/matt/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:3:58322)
    at e.exports.emit (events.js:315:20)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by mondaychen** [comment]
Can you provide more details so that we can try reproduce your issue? "Bitbucket repo" is not something we can work on

**Comment by mondaychen** [comment]
One possible direction is to check whether the devtools' frontend and backend are aligned (e.g. whether they are the same version, whether there're multiple instances of devtools loaded)
I'll close it for now. If you still need help and can provide for more information, feel free to reopen
