### ISSUE TITLE
Bug:  Got error while running npm run build

### ISSUE THREAD

**Issue by ghost** [facebook/react#24895]
Got following error when building production build folders for my project.

`/home/lazyubuntu/Documents/developementProject/amazon-clone/node_modules/react-scripts/config/webpack.config.js:664
        new MiniCssExtractPlugin({
        ^

TypeError: MiniCssExtractPlugin is not a constructor
    at module.exports (/home/lazyubuntu/Documents/developementProject/amazon-clone/node_modules/react-scripts/config/webpack.config.js:664:9)
    at Object.<anonymous> (/home/lazyubuntu/Documents/developementProject/amazon-clone/node_modules/react-scripts/scripts/build.js:58:16)
    at Module._compile (internal/modules/cjs/loader.js:1076:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:941:32)
    at Function.Module._load (internal/modules/cjs/loader.js:782:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! amazon-clone@0.1.0 build: `react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the amazon-clone@0.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lazyubuntu/.npm/_logs/2022-07-12T13_26_59_561Z-debug.log`

**Comment by pierrybos** [comment]
whats your node version?
And react?

**Comment by deepakdubey8756** [comment]
React : -- `17.0.2`
Node: -- '14.10.0`
