### ISSUE TITLE
[DevTools Bug]: window.bundle.js:2 TypeError: Cannot read properties of undefined (reading 'action')

### ISSUE THREAD

**Issue by orangeswim** [facebook/react#24965]
### Website or app

https://onepiece-cardgame.dev/builder?f=%24R+%28%22zoro%22%29

### Repro steps

1. Load webpage
2. Tools doesnt work

### How often does this bug happen?

Every time

**Comment by orangeswim** [comment]
`window.bundle.js:2 TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
as @ window.bundle.js:2
window.bundle.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'action')
    at o.value (window.bundle.js:2:1651470)
    at o.value (window.bundle.js:2:1650604)
    at ds (window.bundle.js:2:153189)
    at Pu (window.bundle.js:2:169890)
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)
    at $o (window.bundle.js:2:112201)
    at Cu (window.bundle.js:2:166629)
    at mu (window.bundle.js:2:162828)
    at window.bundle.js:2:112424
    at t.unstable_runWithPriority (window.bundle.js:2:1032894)`

**Comment by orangeswim** [comment]
![image](https://user-images.githubusercontent.com/1499212/180023304-9e3d889c-5685-45b1-bf00-4ac5c8193092.png)
![image](https://user-images.githubusercontent.com/1499212/180023401-b5f2d955-9220-4181-bdfc-b947c9e77628.png)

**Comment by orangeswim** [comment]
React Dev Tools version 3.0.11

**Comment by mondaychen** [comment]
Are you using the chrome extension or building react devtools into your JS bundle?
The latest version of react devtools is 4.25.0. I'm curious why you are using a much older version.

**Comment by orangeswim** [comment]
Just realized the issue was with Redux Dev Tools
