### ISSUE TITLE
Bug: Using `createRoot` during jest tesing throws "TypeError: Cannot read property 'body' of null"

### ISSUE THREAD

**Issue by turn-a-round** [facebook/react#24993]
React-Dom version: v18.2.0

## Steps To Reproduce

1. Create a test file and use `createRoot` insteasd of `ReactDOM.render`
2. try to run test

```tsx
// file: MyComponent.test.tsx
import React from 'react'
// import ReactDOM from 'react-dom'
import { createRoot } from 'react-dom/client'

import MyComponent from '.'

describe('it', () => {
  it('renders without crashing', () => {
    const div = document.createElement('div')
    // ReactDOM.render(<DummyButton buttonText="Hii!!!" />, div)
    // ReactDOM.unmountComponentAtNode(div)

    const root = createRoot(div)
    root.render(<MyComponent />)
    root.unmount()
  })
})
```

Link to code example:

## The current behavior
It throws
```sh
 RUNS  _src_/MyComponent/MyComponent.test.tsx
/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:1731
    return doc.body;
               ^

TypeError: Cannot read property 'body' of null
    at getActiveElement (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:1731:16)
    at getActiveElementDeep (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:8443:17)
    at getSelectionInformation (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:8476:21)
    at prepareForCommit (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:10912:26)
    at commitBeforeMutationEffects (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:22941:27)
    at commitRootImpl (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:26801:45)
    at commitRoot (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
    at finishConcurrentRender (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:25981:9)
    at performConcurrentWorkOnRoot (/_src_/MyComponent/node_modules/react-dom/cjs/react-dom.development.js:25809:7)
    at workLoop (/_src_/MyComponent/node_modules/scheduler/cjs/scheduler.development.js:266:34)
    at flushWork (/_src_/MyComponent/node_modules/scheduler/cjs/scheduler.development.js:239:14)
    at Immediate.performWorkUntilDeadline (/_src_/MyComponent/node_modules/scheduler/cjs/scheduler.development.js:533:21)
    at processImmediate (internal/timers.js:464:21)
error Command failed with exit code 1.
```

## The expected behavior
Test should pass gracefully
```sh
  PASS  _src_/MyComponent/MyComponent.test.tsx

Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.729s
Ran all test suites.
Done in 5.54s.
```

**Comment by eps1lon** [comment]
Thanks for the report.

This is an issue with Jest that's already tracked in https://github.com/facebook/jest/issues/12670
