### ISSUE TITLE
[DevTools Bug]: "Message length exceeded maximum allowed length" when profiling a complex application

### ISSUE THREAD

**Issue by joshkel** [facebook/react#25415]
### Website or app

N/A

### Repro steps

When profiling a complex, proprietary app, I regularly get an error message, "Message length exceeded maximum allowed length."

Steps to reproduce:

1. Within the Dev Tools, go to the Profiler tab.
2. Click the "Start Profiling" button.
3. Let the app run for a bit. Do some things in the app.
4. Click the "Stop Profiling" ("record") button.

At this point, the Chrome Dev Tools console logs an error:

```
contentScript.js:116 Uncaught Error: Message length exceeded maximum allowed length.
    at handleMessageFromPage (contentScript.js:116:10)
```

And the Profiler tab is stuck with the message, "Processing data... This should only take a minute."

The error is thrown from https://github.com/facebook/react/blob/64fe791be84ad04a4a1d005376ba5cf5701db9b7/packages/react-devtools-extensions/src/contentScript.js#L36

The last time this occurred, when breaking on exceptions at that line, `JSON.stringify(event.data.payload).length` reports 92074565. I can provide further information on the contents of the problematic `event.data.payload` if that would be helpful.

I apologize for the lack of a reproducible test case - it's a complex app (which is why I was looking into profiling), and I don't think I could simplify it down to a public test case while triggering the error.

### How often does this bug happen?

Often

**Comment by MuhammadJufri** [comment]
I think I do this,
Can you assign this issue to me please?

**Comment by elliot-huffman** [comment]
Bumping. Any updates?
I just had this happen to me and I can reproduce this.

**Comment by PiTiLeZarD** [comment]
I think he couldn't do this ;) (teasing) but yeah I have the same issue now!

**Comment by fgatti675** [comment]
Yep, same here!

**Comment by pwbriggs** [comment]
@PiTiLeZarD @fgatti675 are either of you able to share a reproducible example?

**Comment by kaikun213** [comment]
Got the same issue, any updates?
Is there a workaround?

**Comment by jorge-fernandes** [comment]
Also have this issue, albeit a slightly different stacktrace:

````
proxy.js:1 
 Uncaught Error: Message length exceeded maximum allowed length.
    at handleMessageFromPage (proxy.js:1:779)
handleMessageFromPage	@	proxy.js:1
postMessage (async)		
send	@	backendManager.js:1
(anonymous)	@	bridge.js:72
setTimeout (async)		
(anonymous)	@	bridge.js:79
setTimeout (async)		
send	@	bridge.js:168
(anonymous)	@	agent.js:405
emit	@	events.js:37
(anonymous)	@	bridge.js:136
listener	@	backendManager.js:1
postMessage (async)		
handleMessageFromDevtools	@	proxy.js:1
````

Unfortunately i can't also share a repro scenario as "complex application" is proprietary.

Got the same error with both versions 4.2.8 and 5.0.0 of the react devtools

**Comment by fgatti675** [comment]
> @PiTiLeZarD @fgatti675 are either of you able to share a reproducible example?

Hi, we face this issue when debugging FireCMS. It is a fairly large project. It is all open source and can be run locally:
https://github.com/firecmsco/firecms

If you would like to give it a try, running it should be as simple as `yarn` and `yarn dev`

**Comment by danielsgriffin** [comment]
I had the same issue in my program. In case it is useful to anyone: it turned out to be caused by a few runaway useEffects in my code that were constantly updating.

**Comment by Aidam1** [comment]
Any update on this? I have the same issue in my app.

**Comment by mgmrx** [comment]
We experience this issue in our application aswell. Without the help of the react profiler performance optimizations are almost impossible so we would highly appreciate a fix.

**Comment by rahulparmar339** [comment]
Experiencing same issue. Can someone please check this?

**Comment by Angelelz** [comment]
I just ran into this trying to profile a huge internal application and worked around it by reducing the number of components that I'm rendering (for example, don't map over the entire array but just a small slice).
If you have bottlenecks in your application, they should still be visible when you profile the smaller version.

**Comment by rishitells** [comment]
Looks like it's a chrome/chromium specific issue (Message length exceeded maximum allowed length). I tried profiling using React DevTools in Firefox and didn't face this.

**Comment by BrennanptC** [comment]
Also experiencing this problem. Any updates on potential resolution?

**Comment by dir** [comment]
> I had the same issue in my program. In case it is useful to anyone: it turned out to be caused by a few runaway useEffects in my code that were constantly updating.

That's the whole reason I'm profiling!! Hahaha, this is quite the catch-22 situation.

**Comment by nsthorat** [comment]
I also have this problem, and am caught in this catch-22.

**Comment by Zerebokep** [comment]
Same here.

**Comment by ofersadgat** [comment]
@bvaughn you seemed to look into this issue previously here: https://github.com/facebook/react-devtools/issues/1200 it is still occuring with the exact same repro. Any idea for a fix / workaround?

**Comment by cesar-rl** [comment]
Same issue here... Nothing yet?

**Comment by Zerebokep** [comment]
As this will not get fixed anytime soon the only workaround is to user another browser, it works fine in Safari.

**Comment by jasontlouro** [comment]
Three years later and profiling React is still not stable...

**Comment by tkachukivan** [comment]
can add update from 2026 and this issue still does exist

**Comment by gund** [comment]
are you guys still using react in 2026 lol 😁
