### ISSUE TITLE
Bug: Compatibility between ReactServerDOMReader and ReactDOMServer

### ISSUE THREAD

**Issue by penx** [facebook/react#25646]
React version: 0.0.0-experimental-6883d7944-20221101

## Steps To Reproduce

1. Render a server component with `ReactServerDOMWriter.renderToPipeableStream` (with `react-server-dom-webpack/node-register` codemod)
2. Using `ReactDOMServer.renderToPipeableStream`, render a client component that uses `ReactServerDOMReader.createFromReadableStream` (without codemod) to process the server component 
  (note that we can't load the codemod at this point as we need to render client components)

Link to code example:

https://github.com/penx/server-components-ssr

Note that in this example, I have a set `globalThis.__webpack_require__` in `src/api.server.js` in order provide a basic mock, this seems to work but I doubt is the intended usage of this library.

## The current behavior

ReferenceError: __webpack_chunk_load__ is not defined

```console
ReferenceError: __webpack_chunk_load__ is not defined
    at preloadModule (/server-components-demo/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.development.js:76:22)
    at resolveModule (/server-components-demo/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.development.js:643:17)
    at processFullRow (/server-components-demo/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.development.js:728:9)
    at processBinaryChunk (/server-components-demo/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.development.js:782:5)
    at progress (/server-components-demo/node_modules/react-server-dom-webpack/cjs/react-server-dom-webpack-client.development.js:835:5)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

If we set `globalThis.__webpack_chunk_load__`, we then get a similar error regarding `__webpack_require__`.

This is due to

https://github.com/facebook/react/blob/8e2bde6f2751aa6335f3cef488c05c3ea08e074a/packages/react-server-dom-webpack/src/ReactFlightClientWebpackBundlerConfig.js#L75

and

https://github.com/facebook/react/blob/8e2bde6f2751aa6335f3cef488c05c3ea08e074a/packages/react-server-dom-webpack/src/ReactFlightClientWebpackBundlerConfig.js#L94

## The expected behavior

A way to call ReactServerDOMReader.createFromReadableStream that is not dependent on `__webpack_chunk_load__`  and `.__webpack_require__`, or for this error to be silenced if this isn't required on the server.

**Comment by penx** [comment]
Thinking about this further, I suspect it is because I am passing the client moduleMap (react-client-manifest.json) in to the server render of `ReactServerDOMWriter.renderToPipeableStream`, and I need to find a way to pass something else so that the files are client component files loaded directly rather than via the chunks.

**Comment by penx** [comment]
I have this working by passing a proxy object in as the moduleMap:


```js
let proxy = new Proxy(
  {},
  {
    get(_, id) {
      return new Proxy(
        {},
        {
          get(_, n) {
            return {
              id,
              chunks: [],
              name: n,
            };
          },
        }
      );
    },
  }
);
```

and then setting 

```js
globalThis.__webpack_require__ = (name) =>
  require(path.relative(__filename, new URL(name).pathname));
```

...though pretty sure this isn't the intended usage, so would be good to know if there's another way to get ReactDOMServer to render a component that has been created by ReactServerDOMReader.
