### ISSUE TITLE
undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')

### ISSUE THREAD

**Issue by ZeeshanAhmadKhalil** [facebook/react#25676]
I created the next js app using bun but I am getting the following error after I added redux packages in it.

```
Error loading app: /Users/uni/Projects/NFTDD/nftdd-wallet/pages/_app
989 |       error('disabledDepth fell below zero. ' + 'This is a bug in React. Please file an issue.');
990 |     }
991 |   }
992 | }
993 | 
994 | var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;
                                 ^
TypeError: undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/cjs/react-dom.development.js:994:29
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/cjs/react-dom.development.js:29864:71
      at http://localhost:3000/blob:node_modules.server.bun:1:16360
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/index.js:37:27
      at http://localhost:3000/blob:node_modules.server.bun:1:16360
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-redux/es/utils/reactBatchedUpdates.js:1:0
989 |       error('disabledDepth fell below zero. ' + 'This is a bug in React. Please file an issue.');
990 |     }
991 |   }
992 | }
993 | 
994 | var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;
                                 ^
TypeError: undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/cjs/react-dom.development.js:994:29
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/cjs/react-dom.development.js:29864:71
      at http://localhost:3000/blob:node_modules.server.bun:1:16360
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-dom/index.js:37:27
      at http://localhost:3000/blob:node_modules.server.bun:1:16360
      at /Users/uni/Projects/NFTDD/nftdd-wallet/node_modules/react-redux/es/utils/reactBatchedUpdates.js:1:0
```

React version:

`"react": "^18.2.0",`

## Steps To Reproduce

1. install bun
2. clone https://github.com/ZeeshanAhmadKhalil/react-bug
3. `bun dev`

Link to code example:

https://github.com/ZeeshanAhmadKhalil/react-bug

## The current behavior

Getting error:

` undefined is not an object (evaluating 'ReactSharedInternals.ReactCurrentDispatcher')`

## The expected behavior

Should run the next app with redux store added

**Comment by ZeeshanAhmadKhalil** [comment]
When creating the same thing with yarn instead of a bun app is running fine.
Might need to transfer this issue to bun's repo.

**Comment by ZeeshanAhmadKhalil** [comment]
Closing because it's stale now.
