### ISSUE TITLE
[DevTools Bug] Element "41" not found

### ISSUE THREAD

**Issue by Afrokk** [facebook/react#25755]
### Website or app

https://github.com/Afrokk/litmus.tools

### Repro steps

In branch litmus.tools -> feature/LIT-5: 
I just run the app and it throws this error.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.0-bd2ad89a4

### Error message (automated)

Element "41" not found

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39558:15
```

### Error component stack (automated)

```text
at InspectedElementContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:40933:3)
    at Suspense
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39237:5)
    at div
    at InspectedElementErrorBoundaryWrapper (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39771:3)
    at NativeStyleContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:42429:3)
    at div
    at div
    at OwnersListContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:35080:3)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37705:3)
    at Components_Components (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44505:52)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39237:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39409:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39439:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39409:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44686:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44115:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31940:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32584:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39834:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56039:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Element  not found in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by LuizPelegrini** [comment]
This issue starts happening on my end as well, I tried to reinstall the extension but no difference

**Comment by isRostCompany** [comment]
can't confirm that the error is the same, however react-devtools extension stopped working for me as well (even in project where it worked yesterday)
current version "4.27.0, created from bd2ad89a4 on 11/28/2022.

**Comment by MohamedGallab** [comment]
same problem, seems like it happens when redux is used.
it happens to me on a local project I am working on.
happens even after updating both chrome and firefox to the lastest versions.

**Comment by yeana-dev** [comment]
> ~can't confirm that the error is the same, however react-devtools extension stopped working for me as well (even in project where it worked yesterday)~ ~current version "4.27.0, created from [bd2ad89](https://github.com/facebook/react/commit/bd2ad89a4143126e80cc563e195050ea4fe7ce80) on 11/28/2022.~
> 
> ~Screenshot shows where it gets stuck~ ![image](https://user-images.githubusercontent.com/52238490/205018518-7380745f-3f43-4927-9a9a-b2fc35cf19f3.png)
> 
> updating Google Chrome to Version 108.0.5359.71 fixed it for me

This worked for me. Make sure you go to Chrome's setting to update. The update indication on browser isn't showing.
<img width="730" alt="Screen Shot 2022-12-01 at 8 21 05 AM" src="https://user-images.githubusercontent.com/78275456/205076685-a5d912c0-db1a-4c87-beb0-93f75b2f98ee.png">

**Comment by yeana-dev** [comment]
> same problem, seems like it happens when redux is used. it happens to me on a local project I am working on. happens even after updating both chrome and firefox to the lastest versions.

You might want to exit and completely quit Chrome and restart.

**Comment by danilo-vieira** [comment]
Same here :bug:

**Comment by arbocobra** [comment]
Having this issue too. Warning appeared a couple days ago. 
Chrome is up to date (Version 108.0.5359.71 (Official Build) (x86_64)), and restarted. I also tried reinstalling React extension (running 4.27.0).

Confirm what MohamedGallab said above, my project is also using Redux.

**Comment by peteredhead** [comment]
I'm experiencing this issue too using the DevTools in Firefox (107.0).

One common factor I see is that the "Element x not found" error appears for functional components that are using the `useEffect` hook. 
Other hooks I have quickly tested, such as `useState` don't appear to trigger the error for me.

**Comment by Afrokk** [comment]
> I'm experiencing this issue too using the DevTools in Firefox (107.0).
> 
> One common factor I see is that the "Element x not found" error appears for functional components that are using the `useEffect` hook. Other hooks I have quickly tested, such as `useState` don't appear to trigger the error for me.

Nice find, I also think that the useEffect hook has something to do with this. My components that don't use useEffect work just fine.

**Comment by mondaychen** [comment]
Sorry for the inconvenience!
We have submitted a patch (version 4.27.1) to the browser extension stores. It's still under review with Chrome and Edge, but is already published for Firefox https://addons.mozilla.org/en-US/firefox/addon/react-devtools/
Can people give it a test to see if the issue is gone for y'all?

**Comment by Afrokk** [comment]
> Sorry for the inconvenience! We have submitted a patch (version 4.27.1) to the browser extension stores. It's still under review with Chrome and Edge, but is already published for Firefox https://addons.mozilla.org/en-US/firefox/addon/react-devtools/ Can people give it a test to see if the issue is gone for y'all?

Hi, thank you! I'll give it a try as soon as it's live on Chrome.

**Comment by mondaychen** [comment]
It should be on Chrome web store now. Is the issue gone?

**Comment by Afrokk** [comment]
> It should be on Chrome web store now. Is the issue gone?

I just checked, and the issue seems to be gone! Worked perfectly.
