### ISSUE TITLE
[DevTools Bug] Cannot remove node "XX" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by baptistemanson** [facebook/react#25884]
### Website or app

https://ideaflow.app

### Repro steps

Using next 12.3 and windows 10 chrome 108.0.5359.99 (Official Build) (64-bit)
- Open the inspector
- Navigate to the components tab. Open it a few times until it displays something. (blank screen issue already logged #22034 )
- eventually it will display the component tree, but after one scroll, it fails with this error:
![image](https://user-images.githubusercontent.com/5444992/207644741-c870e4bd-8514-4f4f-850a-8713217e41e9.png)

Uncaught Error: Cannot remove node "1946" because no matching node was found in the Store.
Dismiss
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27994:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25895:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26064:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56299:39)

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.1-47f63dc54

### Error message (automated)

Cannot remove node "1946" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27994:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25895:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26064:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56299:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by thestarsahil** [comment]
it doesn't look like this issue has enough info for one of us to reproduce it though. This means that it's going to be very hard for us to fix.
Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve

**Comment by inoyakaigor** [comment]
Got the same issue. Nothing to add except basic information about my app:
React@17.0.2
react-router@5.2.0
mobx@6.6.2
antd@4.23.1
typescript@4.8.3
App builded with webpack through ts-loader (means there is no Babel)

**Comment by Moskowitza** [comment]
This issue has arisen in our app only recently.
"react": "16.5.0"
"redux": "4.0.0"
 "redux-persist": "5.10.0"
 "webpack": "4.12.0",

**Comment by christina-kirk** [comment]
I don't know about anyone else but I'm noticing this issue is happening roughly the same time as an auto update of the react-native-debugger package. 

The react-native-debugger client was prompting an upgrade that I kept ignoring but after running `brew info react-native-debugger` I can see the package is subscribed to auto-updates and the version was automatically bumped to v0.13.0

I'm also not seeing any way to deprecate the debugger client to an older version, so I also can't actually test the version theory.

**Comment by interhub** [comment]
I noticed that the problem occurs - when I'm looking for components nested in the ReactNativeSvg tree

**Comment by johnson-jesse** [comment]
Saw this today:

```bash
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27994:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25895:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26064:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56299:39)
```

Noticed my Chrome was out of date. After updating, no longer saw the error.

**Comment by christina-kirk** [comment]
Updating chrome resolved this for me also.

**Comment by TomasHubelbauer** [comment]
Still happens for me in up to date Firefox Version 110.0 (64-bit). Repeatable 100 % of the time. Do not have a minimal repro, just adding data points about liveness and frequency of the issue.

**Comment by UrUrZa** [comment]
Heve the same issue using `React Developer Tools` for Chrome in  `Storybook 7.0.7 for react-webpack5` 


![React Storybook error](https://user-images.githubusercontent.com/100308055/235155463-fc46bf34-b481-445b-bb76-bb30f5512b7a.png)

**Comment by pankajsoni91** [comment]
I am also facing the same issue. The browser update resolved it once. But it is coming again and again.

**Comment by francisashley** [comment]
Also getting this with React Dev Tools + Storybook

**Comment by SwapnilSoni1999** [comment]
> Also getting this with React Dev Tools + Storybook

Same issue

**Comment by alexandrubodnar1996** [comment]
Same here with following configuration:
    
node: 16.6.0
npm: 7.19.1

webpack: 5.32.0
webpack-cli: ^4.10.0
webpack-dev-server: 3.11.2

**Comment by kiliancs** [comment]
Different repro Firefox 116.0.2. I had a node selected, clicked somewhere in the page (which might have caused that node to unmount), and got this error.

**Comment by gewesp** [comment]
![image](https://github.com/facebook/react/assets/7306215/b1736350-b90e-4b64-b7b2-31bad58fdeab)

Chrome: Version 117.0.5938.149 (Official Build) (arm64) (up to date)
node: v18.16.0
npm: 9.5.1
react: 18.2.0

**Comment by axmachina** [comment]
![image](https://github.com/facebook/react/assets/1904640/fa37b834-71b6-47b4-82f2-19dfc7541ecf)

![image](https://github.com/facebook/react/assets/1904640/e14bf85c-630b-42ff-99f7-721d5e4e5999)

**Comment by alexeykagansky** [comment]
Same here with the following configuration:

node: 21.2.0
npm: 10.3.0
"react": "18.2.0"
"redux": "5.0.0"
"react-redux": "9.0.4"
"react-router-dom": "6.21.1"

**Comment by natle01** [comment]
Same. Been getting it for the last several weeks on both the "Profiler" and "Components".
Getting is both on initial load, and when interacting with elements with react hooks.
```
Uncaught Error: Cannot remove node "137" because no matching node was found in the Store.
The error was thrown at chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:1:1133050
    at A.emit (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:1:1101500)
    at chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:1:1103188
    at bridgeListener (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:1:1509193)
```
![image](https://github.com/facebook/react/assets/74999478/fd29bf9e-08f4-44d8-bfa6-fa52e555aa65)
- node: 18.19.0
- redux: 4.2.1
- react: 18.2.0
- react-redux: 8.1.1
- react-router-dom:  6.14.1
- Edge: 123.0.2420.81
