### ISSUE TITLE
[DevTools Bug] Commit tree does not contain fiber "4543". This is a bug in React DevTools.

### ISSUE THREAD

**Issue by dmaretskyi** [facebook/react#26009]
### Website or app

https://kai.dev.dxos.org/

### Repro steps

1. Open devtools components panel and trigger a re-render in the app.
2. In my case sometimes the component tree doesnt appear at first, but pressing the devtools extension action button in the browser navbar makes it load.

### More info

App built with react `18.2.0` and vite

To repro with Vite running in dev mode:

```
# checkout https://github.com/dxos/dxos/tree/main/packages/experimental/kai

pnpm install
pnpm -w nx serve kai
```

Open devtools component view and trigger a re-render in the app.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.1-47f63dc54

### Error message (automated)

Commit tree does not contain fiber "4543". This is a bug in React DevTools.

### Error call stack (automated)

```text
at updateTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26856:21)
    at getCommitTree (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26716:20)
    at SidebarCommitInfo_SidebarCommitInfo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:55240:42)
    at Ri (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:16122:7)
    at tk (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:17190:7)
    at kn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20548:86)
    at gn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20091:11)
    at fn (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:20011:23)
    at Um (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19991:5)
    at Wm (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:19795:7)
```

### Error component stack (automated)

```text
at SidebarCommitInfo_SidebarCommitInfo (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:55220:34)
    at div
    at div
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:37690:3)
    at Profiler_Profiler (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:55516:34)
    at ErrorBoundary_ErrorBoundary (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39222:5)
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39394:3)
    at PortaledContent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39424:5)
    at div
    at div
    at div
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39394:3)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44671:3)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:44100:3)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:31925:3)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:32569:3)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:39819:3)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56024:3)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Commit tree does not contain fiber . This is a bug in React DevTools. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by shreya-as** [comment]
no idea about this

**Comment by mondaychen** [comment]
I went to the website link you provided, and didn't reproduce this bug. Does it only happen on dev mode?

**Comment by sudarshan1933** [comment]
Hello @dmaretskyi - Please uninstall the React Developer tools extension and then re-install it. Re-launch your browser and try it again. I also faced this issue and it worked for me!!! 
I hope this will help.

**Comment by hoxyq** [comment]
Closing as stale, please open a different issue if seeing this error in versions 7+.
