### ISSUE TITLE
[DevTools Bug]: 

### ISSUE THREAD

**Issue by cherryshoe** [facebook/react#26022]
### Website or app

https://pda.ritis.org/suite/download/

### Repro steps

I noticed this when using React DevTools in my DEV environment with both Chrome and Firefox which is https://pda-dev.ritis.org/suite/download/ but I also see it in the production URL.
1.  Logged in URL with React Developer Tools 4.27.1 installed and enabled (in Chrome or Firefox)
2.  Navigate to a the Download tool
3. Almost immediate the below error displays
`
TypeError: Cannot read properties of undefined (reading 'displayName')
    at getWrappedDisplayName (react_devtools_backend.js:247:33)
    at getDisplayNameForFiber (react_devtools_backend.js:6384:62)
`
![outerType_undefined](https://user-images.githubusercontent.com/3752154/213483566-c6f2c74f-8e79-4d36-bb8a-2d55a103782c.png)
![getWrappedDisplayName](https://user-images.githubusercontent.com/3752154/213483568-af17e1d2-f713-45f3-9c82-f66369bf77f6.png)
![forwardRef](https://user-images.githubusercontent.com/3752154/213483572-1418cbc1-b0ca-4934-bbe9-cddd09ce2091.png)

I'm unable to downgrade React DevTools in Chrome, but can in Firefox and notice that this started occuring with Version 4.27.0.
- "4.27.1 Relased December 6, 2022" produces this error
- "4.27.0 Released November 28, 2022" produces this error
- "4.25.0 Released July 14, 2022" does not produce this error

Since I only use the browser version of react dev-tools, is there any way to install 4.25.0 in Chrome browser?

Other environment information:
Chrome "Version 109.0.5414.75 (Official Build) (64-bit)"
Firefox  "Version 109.0 (64-bit)
Windows 10 Pro build 19044.2486

### How often does this bug happen?

Every time

**Comment by mondaychen** [comment]
Hello. When I visit the URL you provided, I see a login UI not built with React. I assume your application can only be viewed after login. Is it possible for you to provide a test account, or provide a minimal repro using codesandbox.io?

**Comment by cherryshoe** [comment]
Hi. Yes the application can only be viewed after login.  Unfortunately, I won't be able to provide a test account.
I did notice that in the React DevTools changelog for 4.26.0, there is a change related to ForwardRef/Memo if displayName is set.
[react/CHANGELOG.md at main · facebook/react](https://github.com/facebook/react/blob/main/packages/react-devtools/CHANGELOG.md#4260)  (last bullet).

My project's code base does have one reference to ForwardRef in one component.  I'll research into any changes I can make in the code base in response to how ForwardRef has been changed.

**Comment by cherryshoe** [comment]
Hi.  I made a [minimal codesandbox.io project](https://codesandbox.io/s/goofy-bird-6bijxt) with the offending component in my code base "TabNavigator.js" copied exactly as is to the sandbox - with same react, react-dom, and prop-types versions (My project doesn't use create-react-app, but I used it for the sandbox).  I was **not** able to recreate the error with React DevTools 4.27.1 installed and enabled.

Can you give insight on how the getDisplayNameForFiber elementType is populated for tag === 14 (ForwardRef)?  This is undefined in my application where I encounter this issue.
![getDisplayNameForFiber_ForwardRef](https://user-images.githubusercontent.com/3752154/214650697-e48f6003-5e9e-4cce-b33d-e3542422c25f.PNG)
And then when it reaches getWrappedDisplayName, outerType is thus undefined, causing the error.
![getWrappedDisplayName](https://user-images.githubusercontent.com/3752154/214651241-124507a9-6c71-4d03-abb1-6e3d383bc1d6.png)

**Comment by eps1lon** [comment]
The fiber tagged as `MemoComponent` (14) but then enters the case for `ForwardRef` (11 in latest versions). Seems like Devtools doesn't detect the version of React you're using correctly (and uses the v[alue for `ForwardRef` if it doesn't know the version](https://github.com/facebook/react/blob/ee85098019bf9703b32f608f8bbd5f8fb1a7d60b/packages/react-devtools-shared/src/backend/renderer.js#L355)).

@cherryshoe  In your application, could you check, without the 
offending component in your tree, what it displays in the element inspector under "rendered by"? 
![Screenshot from 2023-01-27 08-52-39](https://user-images.githubusercontent.com/12292047/215035676-ff1b3b0d-ab60-41c7-80ed-b24e3f22bbf7.png)

**Comment by cherryshoe** [comment]
With React DevTools version 4.25.0 installed and enabled, and the offending component <TabNavigator> not in the component tree, the react-dom version is 16.4.0, matches what yarn thinks too.

![react-devtools_react-dom-version](https://user-images.githubusercontent.com/3752154/215102327-43a1a462-0267-415d-8010-e1d1c62302fb.PNG)

**Comment by cherryshoe** [comment]
Since outerType is undefined, can you add a check if it's defined then access outerType.displayName, else set it to empty string?
