### ISSUE TITLE
Bug: lazy + Suspense + hydrateRoot = mismatch

### ISSUE THREAD

**Issue by spudly** [facebook/react#26181]
I'm trying to use React' 18's new APIs to enable server-side suspense, but I'm getting hydration mismatch errors when I try to hydrate components that are wrapped in both `lazy()` and `<Suspense />`.

React version: 18.2.0

## Steps To Reproduce

1. wrap a react component with `lazy` and `Suspense`
2. server-side render it using `renderToPipeableStream`
3. try to hydrate it using `hydrateRoot`
4. look in dev console - notice errors

Link to code example: https://codesandbox.io/p/sandbox/dreamy-tristan-8ldu3o

## The current behavior

Hydration fails with the following errors:

```
Warning: Expected server HTML to contain a matching <body> in <html>.
    at body
    at html
    at App
printWarning @ react-dom.development.js:73
react-dom.development.js:12517 
        
Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12517:11)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12545:9)
    at updateHostComponent (react-dom.development.js:19912:7)
    at beginWork (react-dom.development.js:21628:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4151:16)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4200:18)
    at invokeGuardedCallback (react-dom.development.js:4264:33)
    at beginWork$1 (react-dom.development.js:27461:9)
    at performUnitOfWork (react-dom.development.js:26567:14)
    at workLoopSync (react-dom.development.js:26476:7)
react-dom.development.js:73 
        
Warning: An error occurred during hydration. The server HTML was replaced with client content in <#document>.
printWarning @ react-dom.development.js:73
client.js:5 
        
onRecoverableError Error: Hydration failed because the initial UI does not match what was rendered on the server.
    at throwOnHydrationMismatch (react-dom.development.js:12517:11)
    at tryToClaimNextHydratableInstance (react-dom.development.js:12545:9)
    at updateHostComponent (react-dom.development.js:19912:7)
    at beginWork (react-dom.development.js:21628:16)
    at beginWork$1 (react-dom.development.js:27436:16)
    at performUnitOfWork (react-dom.development.js:26567:14)
    at workLoopSync (react-dom.development.js:26476:7)
    at renderRootSync (react-dom.development.js:26444:9)
    at performConcurrentWorkOnRoot (react-dom.development.js:25748:76)
    at workLoop (react.development.js:2653:36)
onRecoverableError @ client.js:5
client.js:5 
        
onRecoverableError Error: There was an error while hydrating. Because the error happened outside of a Suspense boundary, the entire root will switch to client rendering.
    at updateHostRoot (react-dom.development.js:19859:59)
    at beginWork (react-dom.development.js:21625:16)
    at beginWork$1 (react-dom.development.js:27436:16)
    at performUnitOfWork (react-dom.development.js:26567:14)
    at workLoopSync (react-dom.development.js:26476:7)
    at renderRootSync (react-dom.development.js:26444:9)
    at recoverFromConcurrentError (react-dom.development.js:25860:22)
    at performConcurrentWorkOnRoot (react-dom.development.js:25760:24)
    at workLoop (react.development.js:2653:36)
    at flushWork (react.development.js:2626:16)
```

## The expected behavior

Successful hydration / no errors

**Comment by eps1lon** [comment]
Where can I see server and client console output in the repro?

I think you need to bundle the React packages instead of loading them via CDN. Have you tried removing them and then add `import * as ReactDOM from 'react-dom/client'` to `client.js`?

**Comment by eps1lon** [comment]
I think this is caused by a missing `head` tag. The browser will always insert that element but then React tries to hydrate a `body` into the `head` from the user agent. Once you've added a `head` tag I get no more hydration mismatch: https://codesandbox.io/p/sandbox/react-lazy-suspense-hydration-mismatch-forked-cwkpd8?file=%2Fsrc%2FApp.js&selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A16%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A15%7D%5D

Can you confirm this works for you?

**Comment by spudly** [comment]
Yes, I see that fixes the issue in this case. This was an attempt to reproduce a bug I have in a larger, private repo. I'll keep tweaking it and see if I can create a better reproduction.

**Comment by spudly** [comment]
Just a quick update to let you know this issue is not dead.

I'm think my problem is related to #24384 and the associated fix, #24404.

This has been incredibly difficult to debug. I'm still working on creating a minimal repro.

**Comment by spudly** [comment]
@eps1lon , have a chance to review the updated repro?

**Comment by spudly** [comment]
anybody?
