### ISSUE TITLE
Bug: Tests using jest.useFakeTimers gave different results in react 17 and 18.

### ISSUE THREAD

**Issue by skahack** [facebook/react#26273]
I had a test using `jest.FakeTimers` where the results were different between React 17 and 18.

In React 17, useEffect was called each time the state was updated during setInterval, but in React 18, useEffect is no longer executed each time.

https://github.com/facebook/react/commit/06f7b4f43a93eae9111cfbd972ab1ae1148f6afb. The behavior seemed to have changed since this commit.

React version: 17, 18

## Steps To Reproduce

<details>
<summary>Expand reproduce code</summary>

```ts
import { useEffect, useState } from "react";

let count = 0;
function useHooks() {
  const [a, setA] = useState(0);
  const [b, setB] = useState(0);

  useEffect(() => {
    const id = setInterval(() => {
      console.log("interval");
      setA((v) => v + 1);
    }, 100);
    return () => clearInterval(id);
  }, []);

  useEffect(() => {
    count = a;
    setB((v) => v + 1);
    console.log({ count });
  }, [a]);

  return b;
}
module.exports = { count, useHooks };
```

```ts
let TestRenderer;
let React;
let target;
let act;

beforeAll(() => {
  jest.useFakeTimers();
  TestRenderer = require('react-test-renderer');
  React = require('react');
  target = require('./hooks');
  act = TestRenderer.act;
});

it('', () => {
  const result = renderHook(target.useHooks);

  act(() => {
    jest.advanceTimersByTime(0);
  });
  expect(target.count).toBe(0);

  act(() => {
    jest.advanceTimersByTime(500);
  });

  expect(target.count).toBe(5);
  expect(result.current).toBe(6);
});

function renderHook(cb) {
  const result = React.createRef();

  function Component() {
    const renderResult = cb();

    React.useEffect(() => {
      result.current = renderResult;
    });
    return null;
  }

  TestRenderer.create(<Component />);
  return result;
}
```

</details>

Link to code example:

React 17: https://codesandbox.io/p/sandbox/test-issue-repro-react17-mus0c8
React 18: https://codesandbox.io/p/sandbox/test-issue-repro-react18-wlrskc

## The current behavior (React 18)

```
 console.log
    { count: 0 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 5 }
      at src/hooks.js:19:13
```

## The expected behavior (React 17)

```
 console.log
    { count: 0 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 1 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 2 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 3 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 4 }
      at src/hooks.js:19:13

  console.log
    interval
      at src/hooks.js:10:15

  console.log
    { count: 5 }
      at src/hooks.js:19:13
```

## Links

- https://reactjs.org/blog/2022/03/29/react-v18.html#new-feature-automatic-batching
  - https://github.com/facebook/react/issues/26273#issuecomment-1451229823
- https://github.com/reactwg/react-18/discussions/21
- https://github.com/reactwg/react-18/discussions/23

**Comment by 42shadow42** [comment]
I think this is a feature: https://reactjs.org/blog/2022/03/29/react-v18.html#new-feature-automatic-batching

**Comment by skahack** [comment]
Thank you. I was able to get it to behave as before.
I don't know if this is the spec, but I'm going to close the Issue since it seems to have already been discussed.

https://codesandbox.io/p/sandbox/test-issue-repro-react18-resolved-5uxc9h

```diff
--- a.js        2023-03-02 13:52:47.000000000 +0900
+++ b.js        2023-03-02 13:52:59.000000000 +0900
@@ -1,27 +1,22 @@
 let TestRenderer
 let React
 let target
-let act
+
+global.IS_REACT_ACT_ENVIRONMENT = false
 
 beforeAll(() => {
   jest.useFakeTimers()
   TestRenderer = require('react-test-renderer')
   React = require('react')
   target = require('./hooks')
-  act = TestRenderer.act
 })
 
 it('', () => {
   const result = renderHook(target.useHooks)
 
-  act(() => {
-    jest.advanceTimersByTime(0)
-  })
+  jest.advanceTimersByTime(0)
   expect(target.count).toBe(0)
-
-  act(() => {
-    jest.advanceTimersByTime(500)
-  })
+  jest.advanceTimersByTime(501)
 
   expect(target.count).toBe(5)
   expect(result.current).toBe(6)
```
