### ISSUE TITLE
[DevTools Bug] Cannot add node "621" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by iprinceroyy** [facebook/react#26340]
### Website or app

https://github.com/iprinceroyy/crwn-clothing

### Repro steps

Bug report:
1. Clone & run in the local environment.
2. Sign in.
3. Head over to the shop.
4. Add some items to cart.
5. Click on the cart icon.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.2-1a88fbb67

### Error message (automated)

Cannot add node "621" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27863:41
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25892:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26061:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56323:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by 5unnyWind** [comment]
trying to fix it

**Comment by iprinceroyy** [comment]
> trying to fix it

hey, @5unnyWind have you fixed it?

**Comment by 5unnyWind** [comment]
hey,but I don't seem to be getting the error you're talking about
![image](https://user-images.githubusercontent.com/72289221/227821688-c42cdcba-86cf-4563-985b-48dec545ab6c.png)

**Comment by daniel-lee-tech** [comment]
I am also experiencing this issue.

Firefox Extension Version: 4.27.1
My local npm package is version 4.27.4-a8f2653fa

Could the mismatched versions be the cause? (This most likely is a stupid question).

**Comment by long76** [comment]
seems it's crash on big tree

**Comment by long76** [comment]
log spamming warnings
![image](https://user-images.githubusercontent.com/18124433/235104328-7140b7f0-4b0d-4aa5-9056-1bb7c0eb7760.png)

version 4.27.6

**Comment by long76** [comment]
![image](https://user-images.githubusercontent.com/18124433/235104533-d8ab1958-b13e-40b6-b972-82b9b9414c2a.png)

**Comment by THEmmanuel** [comment]
getting this error too... any ideas on how to get around and contribute to fixing this? pointers?

**Comment by Lxylona** [comment]
I got the error too
![image](https://user-images.githubusercontent.com/30256809/236108764-fb709dd8-6540-4e8a-a268-24f00ce3a6cb.png)

**Comment by filipclavin** [comment]
Same here
<img width="558" alt="image" src="https://user-images.githubusercontent.com/70087412/236442301-7802ec36-c51c-498a-a706-a74be583d535.png">

**Comment by hopemiller14** [comment]
I've also been getting this error a ton the past few days.
<img width="1348" alt="Screenshot 2023-05-05 at 11 04 37 AM" src="https://user-images.githubusercontent.com/12564252/236496073-e092fcba-4aab-42ac-9cd7-8c6d79024ae2.png">

Chrome extension version: 4.27.6 (4/20/2023)
Chrome version: 112.0.5615.137 (Official Build) (x86_64)

**Comment by kamranayub** [comment]
Duplicate/related: https://github.com/facebook/react/issues/23226

This seems to happen more often when you have multiple tabs open on different domains with devtools also open for each one. That's what's happening right now.

I had to "end task" for the tabs and dev tools process to get it working again.

**Comment by V1shvesh** [comment]
Hey @kamranayub,
> I had to "end task" for the tabs and dev tools process to get it working again.

Can you please elaborate on the steps to fix this?

Thanks!

**Comment by hoxyq** [comment]
> Duplicate/related: #23226
> 
> This seems to happen more often when you have multiple tabs open on different domains with devtools also open for each one. That's what's happening right now.
> 
> FWIW it's happening on the React site itself, e.g. https://react.dev/learn/describing-the-ui so it's pretty reproducible. I have a `localhost:3000` react app running in another tab.
> 
> I had to "end task" for the tabs and dev tools process to get it working again.
> 
> Chrome extension version: [4.27.7-783e7fcfa](https://github.com/facebook/react/blob/main/packages/react-devtools/CHANGELOG.md#4277) Chrome version: Version 112.0.5615.138 (Official Build) (64-bit)

@kamranayub Can you please share a list of steps which result into facing this error?

I've tried opening multiple (4+ tabs) at the same time, both production and dev builds of React, refreshing pages and reloading Chrome DevTools panels, but cannot reproduce it.

I know that reproducing this can be random, but I am happy to follow the same steps if this errors pops up more frequently for you.
