### ISSUE TITLE
Bug:  `Cannot set properties of null (setting 'dev')` When running `npm link ../myapp/node_modules/react`

### ISSUE THREAD

**Issue by wcardosodev** [facebook/react#26396]
When running `npm link` we have two different versions of react on the library and app. I'm trying to run `npm link ../myapp/node_modules/react` (replacing the template as the path to my app from the library) to which I get an error:
`Cannot set properties of null (setting 'dev')`

React version: 18.2.0
OS: Windows 11

## Steps To Reproduce

1. run `npm link` in my library
2. run `npm link @my-package` in the app
3. run `npm link ../myapp/node_modules/react` (replacing the template) in my library to fix issues with different react versions.
4. get error: 
```
npm ERR! Cannot set properties of null (setting 'dev')
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sarco\AppData\Local\npm-cache\_logs\2023-03-15T15_52_45_146Z-debug.log
```

## The current behavior
Get's the error mentioned

## The expected behavior
Links correct and resolves the issue with duplicate react versions.

Debug.log file:
```
0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'link',
0 verbose cli   '../iq-web/v2/node_modules/react'
0 verbose cli ]
1 info using npm@8.1.2
2 info using node@v16.13.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:D:\GitHub\statsbomb\soccer-kitbag\.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\sarco\.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing config:load:flatten Completed in 2ms
23 timing npm:load:cleanupLog Completed in 2ms
24 timing npm:load:configScope Completed in 0ms
25 timing npm:load:projectScope Completed in 1ms
26 timing npm:load Completed in 18ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 2ms
29 timing idealTree:userRequests Completed in 2ms
30 silly idealTree buildDeps
31 silly placeDep ROOT react@18.2.0 OK for:  want: file:D:/GitHub/statsbomb/iq-web/v2/node_modules/react
32 timing idealTree:#root Completed in 4ms
33 timing idealTree:node_modules/react Completed in 0ms
34 timing idealTree:buildDeps Completed in 5ms
35 timing idealTree:fixDepFlags Completed in 0ms
36 timing idealTree Completed in 10ms
37 timing reify:loadTrees Completed in 10ms
38 timing reify:diffTrees Completed in 1ms
39 silly reify moves {}
40 timing reify:retireShallow Completed in 0ms
41 timing reify:createSparse Completed in 0ms
42 timing reify:loadBundles Completed in 0ms
43 silly audit bulk request { react: [ '18.2.0' ] }
44 timing reifyNode:node_modules/react Completed in 20ms
45 timing reify:unpack Completed in 20ms
46 timing reify:unretire Completed in 0ms
47 timing build:queue Completed in 0ms
48 timing build:deps Completed in 0ms
49 timing build:queue Completed in 0ms
50 timing build:links Completed in 0ms
51 timing build Completed in 0ms
52 timing reify:build Completed in 1ms
53 timing reify:trash Completed in 0ms
54 timing command:link Completed in 6711ms
55 verbose stack TypeError: Cannot set properties of null (setting 'dev')
55 verbose stack     at calcDepFlagsStep (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:34:21)
55 verbose stack     at visit (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:12:20)
55 verbose stack     at visitNode (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:57:25)
55 verbose stack     at next (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:44:19)
55 verbose stack     at depth (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\treeverse\lib\depth-descent.js:82:10)
55 verbose stack     at depth (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\treeverse\lib\depth.js:27:12)
55 verbose stack     at calcDepFlags (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\@npmcli\arborist\lib\calc-dep-flags.js:10:15)
55 verbose stack     at Arborist.[copyIdealToActual] (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:1400:7)
55 verbose stack     at Arborist.reify (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:153:35)
55 verbose stack     at async Link.linkInstall (C:\Users\sarco\AppData\Roaming\nvm\v16.13.1\node_modules\npm\lib\link.js:105:7)
56 verbose cwd D:\GitHub\statsbomb\soccer-kitbag
57 verbose Windows_NT 10.0.22621
58 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "link" "../iq-web/v2/node_modules/react"
59 verbose node v16.13.1
60 verbose npm  v8.1.2
61 error Cannot set properties of null (setting 'dev')
62 verbose exit 1

```

**Comment by pranshu05** [comment]
I guess there should be conflict in the version of app and library...Try deleting ur node-modules and package-lock.json and try installing packages again!
