### ISSUE TITLE
[DevTools Bug] Cannot add child "1161" to parent "942" because parent node was not found in the Store.

### ISSUE THREAD

**Issue by bhanuUdai** [facebook/react#26465]
### Website or app

chrome on local host

### Repro steps

it happen with every component that i mount 
<img width="1470" alt="Screenshot 2023-03-23 at 1 04 00 PM" src="https://user-images.githubusercontent.com/110327079/227134701-d665feca-3326-401e-b957-007c41318be6.png">

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.27.2-1a88fbb67

### Error message (automated)

Cannot add child "1161" to parent "942" because parent node was not found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:27939:43
    at bridge_Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:25892:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:26061:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:56323:39)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add child  to parent  because parent node was not found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by hoxyq** [comment]
@bhanuUdai 

Can you please provide an example of the code that reproduces the problem?
Some useful tips on this: https://stackoverflow.com/help/mcve

**Comment by bhanuUdai** [comment]
this error is coming with every react application i try to run on browser

**Comment by 80avin-sw** [comment]
Getting same along with `Invalid renderer id "1"`. I regularly use React devtools but noticed this only today (which means it might've appeared within last ~1 week).
Another particularly different thing which happens is that Devtools Element tree becomes kind-of disconnected from real VDOM. i.e. hovering doesn't highlight corresponding element in window, neither I can inspect new elements.

This used to happen previously also (since ~3-4 months), and I could work around it by Pressing ``Option`` + ``R`` (reload devtools).
Now, when I try to reload devtools in such situation, I get warning `Invalid renderer id "1"` and devtools goes into above mentioned state.

**Comment by haohuaZhang** [comment]
I have same issue.

**Comment by K-E-L** [comment]
still running into the same problem as of september

**Comment by shseok** [comment]
I have same issue (2024.03.27)

**Comment by Mioara82** [comment]
I have the same issue as the OP. 
```
Uncaught Error: Cannot remove node "59709" because no matching node was found in the Store.

The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1193929
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1160378)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1161985
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1572692)
```

**Comment by Sayakie** [comment]
I'm not sure if this is related to the issue, but I was able to resolve it by removing the fragment from the URL as follows:

```diff
- https://example.com/#page-1
+ https://example.com/
```

**Comment by mfaheemakhtar** [comment]
```
Uncaught Error: Cannot add child "36525" to parent "36117" because parent node was not found in the Store.
Dismiss
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1227910
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1195122)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1196729
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1607819)
```

If I have to guess, one of the components did not render because

**Comment by anurag-codeword** [comment]
reproducable in current latest next-js version

**Comment by anagh07** [comment]
facing same issue on next-js v15.5.2 with zustand.

**Comment by Rots** [comment]
> I'm not sure if this is related to the issue, but I was able to resolve it by removing the fragment from the URL as follows:
> 
> - https://example.com/#page-1
> + https://example.com/

Thanks for the tip! Mine started working when I removed the query parameters from the URL

**Comment by angel33la** [comment]
facing the same issues as well

**Comment by daniel-coherentrx** [comment]
Same issue.

**Comment by eli4cloud** [comment]
same issue

**Comment by B-Schmitz** [comment]
<img width="740" height="131" alt="Image" src="https://github.com/user-attachments/assets/72fb7f77-006e-42a3-b56e-1756919d28d2" />

**Comment by avasuro** [comment]
Temporary workaround that solved the issue for me - remove `React::DevTools::lastSelection` entry from Session Storage:

<img width="745" height="263" alt="Image" src="https://github.com/user-attachments/assets/c256d150-629b-48a7-90e6-9f0b74ee814e" />

**Comment by damiangreen** [comment]
I received this after adding `swc-plugin-add-display-name` package to the solution. i.e. to auto-add displayname to functional components

**Comment by EmadNazzal** [comment]
<img width="484" height="417" alt="Image" src="https://github.com/user-attachments/assets/d470712f-de4a-4732-a9bc-1ed334ced7a5" />


Same issue.

**Comment by steebtom** [comment]
Getting the same error:
<img width="667" height="269" alt="Image" src="https://github.com/user-attachments/assets/491bb59c-8944-4968-8161-a7f617c6e673" />

**Comment by bonchuk** [comment]
i have the same problem
<img width="788" height="185" alt="Image" src="https://github.com/user-attachments/assets/545ec197-2e6c-45fc-8e29-5c92a1ba6ca9" />

**Comment by matthewwalker1621-star** [comment]
Same here man struggling with this

**Comment by ericadalton124-stack** [comment]
Same issue needs updates soon

**Comment by lotfimaria331-ops** [comment]
?

**Comment by hayesmason335-hub** [comment]
There is a solution in the recent update

**Comment by jameswhitaker816-design** [comment]
I'm getting the same error

**Comment by emmapaul357-afk** [comment]
Any updates yet

**Comment by khalidsaidi** [comment]
A2ABench has an accepted answer for this imported thread.
- Thread: https://a2abench-api.web.app/q/cmmlg22po00b1uexhde0cni0f
- Accepted at: 2026-03-25T19:23:07.426Z
- Accepted answer agent: `ai village`
- Answer preview: "No matching threads were found for this query."
