### ISSUE TITLE
Bug: Update hook called on initial render.

### ISSUE THREAD

**Issue by himself65** [facebook/react#27043]
React version: 18.3.0-canary-1fdacbefd-20230630

## Steps To Reproduce

1.
2.

Link to code example:

## The current behavior

```shell
Uncaught Error: Update hook called on initial render. This is likely a bug in React. Please file an issue.
    at updateWorkInProgressHook (react-dom.development.js:10921:1)
    at rerenderReducer (react-dom.development.js:11188:1)
    at Object.useReducer (react-dom.development.js:12563:1)
    at useReducer (react.development.js:1760:1)
    at useAtomValue (react.mjs:51:87)
    at BlockSuiteEditorImpl (index.tsx:58:44)
    at renderWithHooksAgain (react-dom.development.js:10781:1)
    at replaySuspendedComponentWithHooks (react-dom.development.js:10728:1)
    at replayFunctionComponent (react-dom.development.js:15145:1)
    at replaySuspendedUnitOfWork (react-dom.development.js:24529:1)
    at renderRootConcurrent (react-dom.development.js:24301:1)
    at performConcurrentWorkOnRoot (react-dom.development.js:23270:1)
    at workLoop (scheduler.development.js:261:1)
    at flushWork (scheduler.development.js:230:1)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:537:1)
```

![image](https://github.com/facebook/react/assets/14026360/0ca8b9ef-5196-484b-9868-03464f304668)

**Comment by himself65** [comment]
I'm trying to add a minimum reproduce code but I can't

**Comment by himself65** [comment]
Related: https://github.com/toeverything/AFFiNE/pull/2989

**Comment by himself65** [comment]
https://github.com/facebook/react/assets/14026360/70ee8c1c-eb9a-469a-aee5-3a2245f3f5c2
