### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by amrsmind** [facebook/react#27121]
### Website or app

react-devtools with expo

### Repro steps

Once react-devtools run this happen there 

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

4.13.5-0ae5290b54

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at /Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:139060
    at c.emit (/Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:88052)
    at /Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:89523
    at /Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:341120
    at Array.forEach (<anonymous>)
    at S.Vc.e.onmessage (/Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:48:341104)
    at S.n (/Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:40:2971)
    at S.emit (events.js:315:20)
    at e.exports.P (/Users/amr/.config/yarn/global/node_modules/react-devtools-core/dist/standalone.js:8:9318)
    at e.exports.emit (events.js:315:20)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by kiliancs** [comment]
I just run into this using Firefox.

```
The error was thrown emit@moz-extension://57001395-8940-45ea-8bc9-bae1a432b322/build/main.js:27059:22
bridge_Bridge/this._wallUnlisten<@moz-extension://57001395-8940-45ea-8bc9-bae1a432b322/build/main.js:27228:14
listener@moz-extension://57001395-8940-45ea-8bc9-bae1a432b322/build/main.js:57497:41
```

**Comment by Truiteseche** [comment]
Yeah I also ran into this error using Edge (Chromium):
```The error was thrown at chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:28171:41
    at Bridge.emit (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:24827:22)
    at chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:24996:14
    at listener (chrome-extension://gpphkfbcpidddadnkolkpfckpihlkkil/build/main.js:57406:39)```

**Comment by zaqqaz** [comment]
same issue when have multiple iframes and fix like for the iframe support ```if (window.parent !== window && !!window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__) {
                    window.__REACT_DEVTOOLS_GLOBAL_HOOK__ = window.parent.__REACT_DEVTOOLS_GLOBAL_HOOK__;
                }```

**Comment by kweh** [comment]
Got this while refreshing minimal react app with just a single username/password form:
```
The error was thrown at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:28171:41
    at Bridge.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24827:22)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:24996:14
    at listener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:57406:39)
```

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
