### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by amirfSellerCloud** [facebook/react#27547]
### Website or app

[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### Repro steps

[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

4.28.4-5eda682f8

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1186277
    at C.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1143218)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1144967
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1599236)
```

### Error component stack (automated)

```text
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by hoxyq** [comment]
Duplicate of https://github.com/facebook/react/issues/27185
