### ISSUE TITLE
 Bug: react-server-dom-webpack gets confused by package.json#exports map and crashes

### ISSUE THREAD

**Issue by danieltroger** [facebook/react#27711]
React version: 18.2.0

## Steps To Reproduce

1. `git clone git@github.com:danieltroger/react-server-components-stuff.git`
2. `cd react-server-components-stuff`
3. `yarn`
4. `yarn build`

Link to code example: https://github.com/danieltroger/react-server-components-stuff

## The current behavior

```
Error: Could not find the module "/private/tmp/nextjs/nextjs-app-router-examples/.yarn/__virtual__/@depict-ai-react-ui-virtual-3869a00161/5/Users/daniel/.yarn/berry/cache/@depict-ai-react-ui-npm-2.1.15-cf7dcd910c-10c0.zip/node_modules/@depict-ai/react-ui/server/ES10/index.js#DepictProvider" in the React Client Manifest. This is probably a bug in the React Server Components bundler.
    at eS (/private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129767)
    at /private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:140430
    at Array.toJSON (/private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:143576)
    at stringify (<anonymous>)
    at eE (/private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:131961)
    at eR (/private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:132404)
    at Timeout._onTimeout (/private/tmp/nextjs/nextjs-app-router-examples/.yarn/unplugged/next-virtual-e0eb339554/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:129184)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
```

## The expected behavior

App builds successfully

## Additional information

The error is thrown here: https://github.com/facebook/react/blob/07cc4a0002d0bbaaf8910404895eeb9c199831c4/packages/react-server-dom-webpack/src/ReactFlightServerConfigWebpackBundler.js#L65 from a minified copy of  react-server-dom-webpack that is embedded into nextjs.

I've stepped through the code when it throws in a debugger (unfortunately didn't take any screenshots) and the issue is that `config` contains the "browser"-export-ed path of `@depict-ai/react-ui` while `modulePath` contains the `node`-export-ed path (as can be seen in the error message)

**Comment by danieltroger** [comment]
Bump
