### ISSUE TITLE
Bug:  Cannot read properties of null (reading 'useState')

### ISSUE THREAD

**Issue by GantaVenkataKousik** [facebook/react#27987]
Cannot read properties of null (reading 'useState')
TypeError: Cannot read properties of null (reading 'useState')
    at useState (http://localhost:3000/static/js/bundle.js:75196:25)
    at Q (http://localhost:3000/static/js/bundle.js:82555:61)
    at renderWithHooks (http://localhost:3000/static/js/bundle.js:24955:22)
    at mountIndeterminateComponent (http://localhost:3000/static/js/bundle.js:28239:17)
    at beginWork (http://localhost:3000/static/js/bundle.js:29535:20)
    at HTMLUnknownElement.callCallback (http://localhost:3000/static/js/bundle.js:14551:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3000/static/js/bundle.js:14595:20)
    at invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:14652:35)
    at beginWork$1 (http://localhost:3000/static/js/bundle.js:34516:11)
    at performUnitOfWork (http://localhost:3000/static/js/bundle.js:33764:16)
    
    How to solve this issue???

**Comment by JAKEdevilhunter** [comment]
Its most likely an  import issue try and add 
import { useState } from 'react'

**Comment by akdinesh124** [comment]
May I have the Steps to reproduce?

**Comment by RishabhReactJS** [comment]
@GantaVenkataKousik Please confirm if the bug is still replicable?

**Comment by ritikbanger** [comment]
Please provide with reproduce steps or share a codesandbox. @GantaVenkataKousik

**Comment by rickhanlonii** [comment]
This is likely a problem in your code and not React, but if you provide a isolated sandbox showing the bug in React I can re-open and take a look.

**Comment by GantaVenkataKousik** [comment]
Issue is resolved 

-->> The problem occured because I have sent a request to server and it was returning null object 
-->> That null object is being as a state that is the reason I am getting that problem
