### ISSUE TITLE
[React 19] useEffect does not re-fire on hot reload with React 19 and vite

### ISSUE THREAD

**Issue by gkiely** [facebook/react#29915]
In prior versions of react, saving a file will trigger the components useEffect hooks to run. This does not work for react 19.
This applies to both @vitejs/plugin-react-swc and @vitejs/plugin-react

Repo: https://github.com/gkiely/swc-issue

Steps to reproduce:
- npm i
- npm run dev
- open repo and press save in App.tsx
- console.log will not fire after pressing save
- npm i react@latest react-dom@latest  (installs latest react 18)
- npm run dev
- press save in App.tsx
- console.log will fire

Video reproduction:
https://www.loom.com/share/b493602e3f7244d2948c5bb871531881?sid=c9bdec15-5b87-4375-a659-6c63804cb032

Notes:
I previously opened a ticket here but it is perhaps an issue with react 19: https://github.com/vitejs/vite-plugin-react/issues/335

**Comment by prafulla-codes** [comment]
Hey @gkiely - 
I'd like to work on this issue

**Comment by ArnaudBarre** [comment]
I've looked into it and this happen only with StrictMode enabled.

**Comment by eps1lon** [comment]
Does this work in React 18?

**Comment by ArnaudBarre** [comment]
Yep, React with 18 useEffect runs everytime if the file is updated

**Comment by eps1lon** [comment]
Can reproduce with the provided repro and also `next@15.0.0-canary.76`. I also double checked by using breakpoints to ensure it's not just `console.log` being incorrectly silenced.

**Comment by gkiely** [comment]
Gentle bump on this @eps1lon. Unfortunately it is a blocker for me upgrading to 19.

**Comment by kg55kmr** [comment]
Still not fixed?

**Comment by ArnaudBarre** [comment]
@eps1lon I still have the issue with the latest canary: https://stackblitz.com/edit/vitejs-vite-zgcjfkx7?file=src%2FApp.tsx

Is your PR including the canary version?

**Comment by eps1lon** [comment]
The linked Stackblitz crashes for me before the dev server is up:
```
$ npm run dev
(node:27) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27) ExperimentalWarning: WASI is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
worker (tid = 43) sent an error! Invalid atomic access index
RangeError: Invalid atomic access index
    at Object.storeSizeTypeValue (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1218:29)
    at Object.pushQueue (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:990:28)
    at eval (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1040:36)
    at Object.execute (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1094:36)
    at Object.push (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1029:33)
    at napi_call_threadsafe_function (/tmp/rolldown-1.0.1/node_modules/.pnpm/@emnapi+core@1.10.0/node_modules/@emnapi/core/dist/emnapi-core.cjs.js:1612:31)

Node.js v22.22.0
```

**Comment by ArnaudBarre** [comment]
Arf sad, it just worked for me with Chrome (148) and Firefox (150)

**Comment by eps1lon** [comment]
So that specific issue seems intentional. The signature of the Component is still the same so we can just do a re-render. With no dependencies, the Effect doesn't even need to run. The fix was for refreshes that would mount a new Component after Fast Refresh (i.e. run any Effects) but don't double invoke.

Vite would need to add support for invalidating the signature of a Function Component if any Effect implementation is invalidated.

**Comment by ArnaudBarre** [comment]
Oh ok thanks for the explanation, I will try to get the effects implementation impact the component signature!
