### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by arvindhcm** [facebook/react#30607]
### Website or app

local repo

### Repro steps

just loaded the local  react app

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

5.3.1-ccb20cb88b

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1172435
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1141877)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1143565
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1551564)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by Marvinrose** [comment]
Hello,
I’m interested in working on this issue. Before I do so, I wanted to check if anyone is currently working on it or if there are any ongoing discussions that I should be aware of.
If it's available, I’d love to take a look and contribute. Please let me know!
Thanks!

**Comment by eric-gitta-moore** [comment]
+1
I'm followed https://zh-hans.react.dev/learn/react-developer-tools#safari-and-other-browsers

```
Uncaught Error: 
Cannot add node "1" because a node with that id is already in the Store.
```

```
The error was thrown 
at /Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:1043404
    at f.emit (/Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:989541)
    at /Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:991083
    at /Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:1392030
    at Array.forEach (<anonymous>)
    at e.onmessage (/Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:1392013)
    at H.s (/Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:404466)
    at H.emit (node:events:513:28)
    at e.exports.B (/Users/admin/.nvm/versions/node/v20.14.0/lib/node_modules/react-devtools/node_modules/react-devtools-core/dist/standalone.js:2:438611)
    at e.exports.emit (node:events:513:28)

```

**Comment by sshakil** [comment]
seeing this, too

**Comment by stealth90** [comment]
+1

**Comment by ramansaini14** [comment]
+1

**Comment by Not-James-Bond** [comment]
+1 .Facing this with Firefox.

`Uncaught Error: Cannot add node "1" because a node with that id is already in the Store.

The error was thrown emit@moz-extension://35d01427-9a13-4135-8eff-8ba691c5a227/build/main.js:1:1141877
v/this._wallUnlisten<@moz-extension://35d01427-9a13-4135-8eff-8ba691c5a227/build/main.js:1:1143565
bridgeListener@moz-extension://35d01427-9a13-4135-8eff-8ba691c5a227/build/main.js:1:1551393`

**Comment by jasperfernandez** [comment]
+1 Facing this with Microsoft Edge

**Comment by konoufo** [comment]
+1

**Comment by KunalSukhija-Fareye** [comment]
+1 facing in Google Chrome

**Comment by RPSingh0** [comment]
+1 Facing this issue in Microsoft Edge

**Comment by kayquealmeida** [comment]
+1 facing this issue in Edge

**Comment by GLEF1X** [comment]
+1 facing this issue in Google Chrome Version 128.0.6613.138 (Official Build) (arm64)

**Comment by ZandercraftGames** [comment]
+1 Facing this issue in Brave browser
```
1.69.168 Chromium: 128.0.6613.138 (Official Build) (64-bit)
Windows 11 Version 23H2 (Build 22631.4169)
```

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
