### ISSUE TITLE
[DevTools Bug] Cannot add node "20468" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by NirnayK** [facebook/react#31086]
### Website or app

https://demo.ragflow.io/

### Repro steps

Login into the site and checkout components at any page. The error will pop up.

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

5.3.1-ccb20cb88b

### Error message (automated)

Cannot add node "20468" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1172435
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1141877)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1143565
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1551564)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by neeraj03788** [comment]
Hey I am not getting your issue could you brief that?

**Comment by NigeAtAnd** [comment]
I've seen it a few times now, developing a React Native Expo app using Expo Go. I reload the app with DevTools open and I get this error.

```
Uncaught Error: Cannot add node "1734" because a node with that id is already in the Store.
Dismiss
The error was thrown at http://192.168.0.66:8081/_expo/react-devtools/standalone.js:2:1011371
    at f.emit (http://192.168.0.66:8081/_expo/react-devtools/standalone.js:2:984358)
    at http://192.168.0.66:8081/_expo/react-devtools/standalone.js:2:985900
    at http://192.168.0.66:8081/_expo/react-devtools/standalone.js:2:1359186
    at Array.forEach (<anonymous>)
    at U_.e.onmessage (http://192.168.0.66:8081/_expo/react-devtools/standalone.js:2:1359169)
```

Refreshing DevTools doesn't help. 

MacOS Sonoma 14.7
DevTools 5.2.0-1717ab0171
Chrome 129.0.6668.101 x86_64
react 18.2.0
react-native 0.74.5
expo 51.0.37

**Comment by piecdar** [comment]
Uncaught Error: Cannot add node "330" because a node with that id is already in the Store.
The error was thrown emit@moz-extension://bbac5ce7-5760-41c7-8624-0d264d68a0c7/build/main.js:1:1141200
v/this._wallUnlisten<@moz-extension://bbac5ce7-5760-41c7-8624-0d264d68a0c7/build/main.js:1:1142807
bridgeListener@moz-extension://bbac5ce7-5760-41c7-8624-0d264d68a0c7/build/main.js:1:1552360

**Comment by GlennAtCallinetic** [comment]
I encountered the same issue because I had installed the React Developer Tools extension twice, likely from two different sources. Removing one of them resolved the issue for me.

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
