### ISSUE TITLE
[DevTools Bug] Cannot destructure property 'duration' of 'e[g]' as it is undefined.

### ISSUE THREAD

**Issue by ngannguyen438** [facebook/react#31121]
### Website or app

App

### Repro steps

Click view other component

### How often does this bug happen?

Often

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

6.0.0-d66fa02a30

### Error message (automated)

Cannot destructure property 'duration' of 'e[g]' as it is undefined.

### Error call stack (automated)

```text
at vp (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1444134)
    at vi (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:56396)
    at ts (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:76674)
    at gs (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:87585)
    at nc (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:132774)
    at rc (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:132702)
    at ec (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:132550)
    at Bu (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:129172)
    at Hc (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:142218)
    at Immediate.M [as _onImmediate] (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:193522)
```

### Error component stack (automated)

```text
at vp (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1442947)
    at div (<anonymous>)
    at fa (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1152427)
    at dp (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1442557)
    at div (<anonymous>)
    at mp (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1445963)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at cu (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1235700)
    at C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1453739
    at rc (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1251400)
    at C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1254056
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at nc (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1253890)
    at sv (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1324943)
    at Xd (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1317466)
    at ja (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1170090)
    at gi (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1184521)
    at Td (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1305602)
    at Zp (C:\Users\vanta\AppData\Local\npm-cache\_npx\8ea6ac5c50576a3b\node_modules\react-devtools-core\dist\standalone.js:2:1460269)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot destructure property 'duration' of 'e[g]' as it is undefined. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by MeerArsalanAli27** [comment]
The error is occurring due to an attempt to destructure a property called duration from an object e[g], which is undefined.

To resolve this issue, please ensure that the e[g] object is defined and contains the duration property. If the property is optional, consider using optional chaining (?.) to safely access the duration property, like this: e[g]?.duration.

If you're still facing issues, please provide more context or code snippets,
