### ISSUE TITLE
[DevTools Bug] Could not find node with id "18006" in commit tree

### ISSUE THREAD

**Issue by mohamedziadjabbad** [facebook/react#31310]
### Website or app

npx react-devtools

### Repro steps

clicking on the record button and stop in it produces this error

### How often does this bug happen?

Sometimes

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

6.0.1-c7c68ef842

### Error message (automated)

Could not find node with id "18006" in commit tree

### Error call stack (automated)

```text
at /Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1033341
    at Map.forEach (<anonymous>)
    at /Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1033290
    at Er.getRankedChartData (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1033791)
    at Nf (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1258069)
    at di (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:44095)
    at ts (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:64373)
    at gs (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:75284)
    at rc (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:120293)
    at Ju (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:120221)
```

### Error component stack (automated)

```text
at Nf (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1257826)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at ts (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1157861)
    at /Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1376165
    at Ks (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1173575)
    at /Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1176231
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at Ys (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1176065)
    at Zc (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1247244)
    at Lc (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1239735)
    at xt (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1079120)
    at ca (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1106654)
    at Ec (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1227871)
    at Y_ (/Users/macgr/.npm/_npx/8ea6ac5c50576a3b/node_modules/react-devtools-core/dist/standalone.js:2:1382695)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not find node with id  in commit tree in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by harveyducks** [comment]
I also have this issue, but I do not understand the cause.

**Comment by hoxyq** [comment]
We landed significant changes to this instrumentation in the last few updates, please open a new issue if this is still reproducible in versions 7+.
