### ISSUE TITLE
[DevTools Bug] Cannot remove node "2546" because no matching node was found in the Store.

### ISSUE THREAD

**Issue by merehan1111** [facebook/react#31436]
### Website or app

e-comerce

### Repro steps

login

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

6.0.1-c7c68ef842

### Error message (automated)

Cannot remove node "2546" because no matching node was found in the Store.

### Error call stack (automated)

```text
at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1173889
    at v.emit (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1140783)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1142390
    at bridgeListener (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1552529)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot remove node  because no matching node was found in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by cpholt** [comment]
This happens every time I try to profile with react-dev-tools.  Exact same stack.

**Comment by RohovDmytro** [comment]
For years it 'some node is missing'. Damn. Frustrating as hell.

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
