### ISSUE TITLE
Fail to run jsx compiler on Windows Vista Business SP1

### ISSUE THREAD

**Issue by bouncce** [facebook/react#316]
I have installed the react-tools with npm, but when I tried to run jsx, it gives me the following error:

```
C:\Users\myusername\AppData\Roaming\npm\node_modules\react-tools\bin>node jsx

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
```

Is it possible to fix this?

**Comment by thespacecadette** [comment]
"npm install -g jsxc" worked for me too!
