### ISSUE TITLE
Bug: Can't built chrome extension - yarn build-for-devtools fails

### ISSUE THREAD

**Issue by devluismeta** [facebook/react#31618]
I attempted to follow the instructions in the README for react-devtools-extensions, but I'm not able to build devtools, it fails on "build-for-devtools".

1. yarn install from the root repo (worked) (from the repo root)
2. followed by yarn build-for-devtools (fails) (from the repo root)

build-for-tools was successful up to "react-refresh-runtime.production.js", it fails with the core message:

  Error: Command failed: npm pack build/node_modules/react
  npm error Invalid property "node"

The log file had the following relevant content:

  12 verbose stack Error: Invalid property "node"
  12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install- checks/lib/dev-engines.js:100:13)
  12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
  12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
  12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
  12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)

(I include the full shell and log file below)

# Below is the full log file content

0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-art
8 verbose argv "pack" "build/node_modules/react-art"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-debug-tools
8 verbose argv "pack" "build/node_modules/react-debug-tools"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/jest-react
8 verbose argv "pack" "build/node_modules/jest-react"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-dom
8 verbose argv "pack" "build/node_modules/react-dom"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-is
8 verbose argv "pack" "build/node_modules/react-is"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-refresh
8 verbose argv "pack" "build/node_modules/react-refresh"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react-test-renderer
8 verbose argv "pack" "build/node_modules/react-test-renderer"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
0 verbose cli /usr/local/bin/node /Users/admin/.npm-global/bin/npm
1 info using npm@10.9.0
2 info using node@v22.11.0
3 silly config load:file:/Users/admin/.npm-global/lib/node_modules/npm/npmrc
4 silly config load:file:/Users/admin/local-projects/react/.npmrc
5 silly config load:file:/Users/admin/.npmrc
6 silly config load:file:/Users/admin/.npm-global/etc/npmrc
7 verbose title npm pack build/node_modules/react
8 verbose argv "pack" "build/node_modules/react"
9 verbose logfile logs-max:10 dir:/Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-
10 verbose logfile /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
11 silly logfile start cleaning logs, removing 1 files
12 verbose stack Error: Invalid property "node"
12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
12 verbose stack Error: Invalid property "node"
12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
12 verbose stack Error: Invalid property "node"
12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
12 verbose stack Error: Invalid property "node"
12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
13 error Invalid property "node"
13 error Invalid property "node"
13 error Invalid property "node"
13 error Invalid property "node"
12 silly logfile done cleaning log files
12 silly logfile done cleaning log files
12 silly logfile done cleaning log files
14 verbose cwd /Users/admin/local-projects/react
14 verbose cwd /Users/admin/local-projects/react
15 verbose os Darwin 24.1.0
15 verbose os Darwin 24.1.0
14 verbose cwd /Users/admin/local-projects/react
14 verbose cwd /Users/admin/local-projects/react
15 verbose os Darwin 24.1.0
15 verbose os Darwin 24.1.0
16 verbose node v22.11.0
17 verbose npm  v10.9.0
16 verbose node v22.11.0
12 verbose stack Error: Invalid property "node"
12 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
12 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
12 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
12 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
12 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
17 verbose npm  v10.9.0
18 verbose exit 1
16 verbose node v22.11.0
19 verbose code 1
16 verbose node v22.11.0
17 verbose npm  v10.9.0
13 error Invalid property "node"
18 verbose exit 1
17 verbose npm  v10.9.0
18 verbose exit 1
20 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
19 verbose code 1
19 verbose code 1
13 verbose stack Error: Invalid property "node"
13 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
13 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
13 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
13 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
18 verbose exit 1
14 error Invalid property "node"
19 verbose code 1
20 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
20 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
13 verbose stack Error: Invalid property "node"
13 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
13 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
13 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
13 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 error Invalid property "node"
20 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
13 verbose stack Error: Invalid property "node"
13 verbose stack     at checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/node_modules/npm-install-checks/lib/dev-engines.js:100:13)
13 verbose stack     at Pack.checkDevEngines (/Users/admin/.npm-global/lib/node_modules/npm/lib/base-cmd.js:153:22)
13 verbose stack     at async #exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:251:7)
13 verbose stack     at async Npm.exec (/Users/admin/.npm-global/lib/node_modules/npm/lib/npm.js:207:9)
13 verbose stack     at async module.exports (/Users/admin/.npm-global/lib/node_modules/npm/lib/cli/entry.js:74:5)
14 error Invalid property "node"
14 verbose cwd /Users/admin/local-projects/react
15 verbose os Darwin 24.1.0
15 verbose cwd /Users/admin/local-projects/react
15 verbose cwd /Users/admin/local-projects/react
16 verbose node v22.11.0
17 verbose npm  v10.9.0
16 verbose os Darwin 24.1.0
17 verbose node v22.11.0
18 verbose npm  v10.9.0
18 verbose exit 1
19 verbose code 1
16 verbose os Darwin 24.1.0
19 verbose exit 1
17 verbose node v22.11.0
20 verbose code 1
18 verbose npm  v10.9.0
20 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
19 verbose exit 1
21 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
20 verbose code 1
15 verbose cwd /Users/admin/local-projects/react
21 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log
16 verbose os Darwin 24.1.0
17 verbose node v22.11.0
18 verbose npm  v10.9.0
19 verbose exit 1
20 verbose code 1
21 error A complete log of this run can be found in: /Users/admin/.npm/_logs/2024-11-22T20_03_58_977Z-debug-0.log

[shell.log](https://github.com/user-attachments/files/17876136/shell.log)

 # My environment

I'm using an Intel mac.

$ node -v
v22.11.0

$ java -version
java version "23.0.1" 2024-10-15
Java(TM) SE Runtime Environment (build 23.0.1+11-39)
Java HotSpot(TM) 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)

$ git branch -v
* main e697386c10 [compiler] First cut at dep inference (#31386)

**Comment by aalmanasir** [comment]
Bug

**Comment by franky47** [comment]
I had the same issue using `npm@10.9.1`. The error comes from a check that was introduced in `npm-install-checks@7.1.0` (source PR https://github.com/npm/npm-install-checks/pull/116), and was integrated in `npm@10.9.0`. 

Reverting to `npm@10.8.3` solved it.

**Comment by dancok159** [comment]
https://github.com/facebook/react/issues/31618
