### ISSUE TITLE
[DevTools Bug] Cannot add node "1" because a node with that id is already in the Store.

### ISSUE THREAD

**Issue by Nasrallah1997** [facebook/react#31743]
### Website or app

Expo Go & Google Chrome

### Repro steps

Android Bundled 589ms node_modules\expo-router\entry.js (1 module)
 (NOBRIDGE) LOG  Bridgeless mode is enabled     
 INFO 
 💡 JavaScript logs will be removed from Metro in React Native 0.77! Please use React Native DevTools as your default tool. Tip: Type j in the terminal to open (requires Google Chrome or Microsoft Edge).
 (NOBRIDGE) WARN  Route "./Colors.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./TabBarIcon.tsx" is missing the required default export. Ensure a React component is exported as default. [Component Stack]
 (NOBRIDGE) WARN  Route "./useThemeColor.ts" is missing the required default export. Ensure a React component is exported as default. [Component Stack]

### How often does this bug happen?

Every time

### DevTools package (automated)

react-devtools-core

### DevTools version (automated)

5.2.0-1717ab0171

### Error message (automated)

Cannot add node "1" because a node with that id is already in the Store.

### Error call stack (automated)

```text
at http://10.251.14.176:8081/_expo/react-devtools/standalone.js:2:1011371
    at f.emit (http://10.251.14.176:8081/_expo/react-devtools/standalone.js:2:984358)
    at http://10.251.14.176:8081/_expo/react-devtools/standalone.js:2:985900
    at http://10.251.14.176:8081/_expo/react-devtools/standalone.js:2:1359186
    at Array.forEach (<anonymous>)
    at U_.e.onmessage (http://10.251.14.176:8081/_expo/react-devtools/standalone.js:2:1359169)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by VictorRutskin** [comment]
@Nasrallah1997  note that this issue is a duplicate, there is a whole thread here: 
https://github.com/facebook/react/issues/27185

**Comment by Pooja-Vr** [comment]
https://api.github.com/search/issues?q=Cannot add node  because a node with that id is already in the Store. in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react

**Comment by eps1lon** [comment]
We fixed some scenarios where this could occur in React DevTools 7.0. If this issue still persists, please open a new issue.
