### ISSUE TITLE
React 19 breaking with this.props.children

### ISSUE THREAD

**Issue by 2xOu7** [facebook/react#31832]
Hello,

Our code is now breaking when we upgrade to React 19. It seems related to this.props.children, and it works fine in React 18. I have attached the error and a screenshot of where the code is breaking.

[Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.]
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.

<img width="769" alt="Screenshot 2024-12-18 at 12 09 59 AM" src="https://github.com/user-attachments/assets/1b02542c-ef41-4b6d-90d9-64380c5ad609" />

**Comment by eps1lon** [comment]
Whatever is in `this.props.children` is likely JSX from another version of React. We often got these reports when people used 3rd party dependencies that inlined the JSX runtime in their build process when it should be an external.

I recommend removing as much code as possible from this Component tree until it no longer reproduces. That should help identifying the offending Component.

**Comment by micky0001** [comment]
check this might be useful for you 
render(): Element {
    const { microCopiesToRender, isPreviewMode } = this.state;

    // Validate `this.props.children`
    const validChildren = React.Children.map(this.props.children, (child) => {
        if (React.isValidElement(child)) {
            return child;
        }
        console.error("Invalid child found:", child);
        return null; // or handle invalid children gracefully
    });

    if (!microCopiesToRender) {
        return <>{validChildren}</>;
    }

    return (
        <MicrocopyContext.Provider
            value={{ copies: microCopiesToRender ?? [], isPreview: isPreviewMode }}
        >
            {validChildren}
        </MicrocopyContext.Provider>
    );
}

**Comment by 2xOu7** [comment]
Nothing's logging when I put the code above. It breaks on build without me even running the code. 

The only child of the class is a <p> element, so no third party dependencies. Like I mentioned, it works completely fine when I build my npm library with React 18, but no longer works with React 19, so I don't think it's on my end.

**Comment by 2xOu7** [comment]
Update: Even with no children, it breaks!

**Comment by piokasar** [comment]
I am also seeing this issue unfortunately.

**Comment by 2xOu7** [comment]
It sounds like this is a backwards compatibility issue - is there no intention to fix it?

**Comment by eps1lon** [comment]
> It sounds like this is a backwards compatibility issue - is there no intention to fix it?

It is highly likely you're using a library that inline the JSX runtime from a previous version.

I recommend removing code until it no longer reproduces. That should help identifying the offending library.

Without a reproduction, we can't help.

**Comment by piokasar** [comment]
I was able to reproduce it with the following stack trace:

```

[Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.]
Error occurred prerendering page "/". Read more: https://nextjs.org/docs/messages/prerender-error
Error: Objects are not valid as a React child (found: object with keys {$$typeof, type, key, ref, props, _owner}). If you meant to render a collection of children, use an array instead.
    at retryNode (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4917:13)
    at renderNodeDestructive (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4689:7)
    at renderElement (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4324:7)
    at retryNode (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4871:16)
    at renderNodeDestructive (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4689:7)
    at renderNode (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:5128:14)
    at renderChildrenArray (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:5019:7)
    at retryNode (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4885:9)
    at renderNodeDestructive (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4689:7)
    at renderElement (/Users/katherine/next-app-2/node_modules/react-dom/cjs/react-dom-server.edge.production.js:4417:9)
Export encountered an error on /, exiting the build.
 ⨯ Static worker exited with code: 1 and signal: null

```

**Comment by Skippyy96** [comment]
The

**Comment by Skippyy96** [comment]
The

**Comment by PixeledCode** [comment]
@2xOu7 were you able to resolve this issue? I am upgrading a component library to react 19 and seeing this error
