### ISSUE TITLE
[DevTools Bug] Could not find commit data for root "1"

### ISSUE THREAD

**Issue by anwarrturay** [facebook/react#31888]
### Website or app

http://localhost:5173/

### Repro steps

was trying to test the performance of my react application

### How often does this bug happen?

Only once

### DevTools package (automated)

react-devtools-extensions

### DevTools version (automated)

6.0.1-c7c68ef842

### Error message (automated)

Could not find commit data for root "1"

### Error call stack (automated)

```text
at me.getDataForRoot (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1167575)
    at SnapshotSelector_SnapshotSelector (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1528048)
    at renderWithHooks (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:52283)
    at updateFunctionComponent (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:81757)
    at beginWork (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:95976)
    at performUnitOfWork (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:154382)
    at workLoopSync (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:154250)
    at renderRootSync (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:153981)
    at performWorkOnRoot (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:149824)
    at performSyncWorkOnRoot (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:164385)
```

### Error component stack (automated)

```text
at SnapshotSelector_SnapshotSelector (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1527987)
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at SettingsModalContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1297652)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1536522
    at da (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1315454)
    at div (<anonymous>)
    at div (<anonymous>)
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1318165)
    at chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1318362
    at div (<anonymous>)
    at div (<anonymous>)
    at div (<anonymous>)
    at ThemeProvider (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1318165)
    at TimelineContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1395852)
    at ProfilerContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1387571)
    at TreeContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1209877)
    at SettingsContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1238028)
    at ModalDialogContextController (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1375269)
    at DevTools_DevTools (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/main.js:1:1544258)
```

### GitHub query string (automated)

```text
https://api.github.com/search/issues?q=Could not find commit data for root  in:title is:issue is:open is:public label:"Component: Developer Tools" repo:facebook/react
```

**Comment by bigspark363** [comment]
My Facebook account was hacked and disabled

**Comment by bigspark363** [comment]
![Uploading IMG_8286.png…]()
