### ISSUE TITLE
jsx_orphaned_brackets_transformer does not honor spread operator

### ISSUE THREAD

**Issue by akshayp** [facebook/react#3382]
If you run `jsx_orphaned_brackets_transformer` on the following example the transformer throws an exception

```js
var MyMessage = require('react-mymessage');

var HelloMessage = React.createClass({
    render: function() {
        var myPropObj = this.props.myPropObj;

        return <MyMessage {...myPropObj} />;
    }
});

module.exports = HelloMessage;
```

Exception:

```
[~] jsx_orphaned_brackets_transformer foo.jsx                                                                                                14:43:16

/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/run.js:116
      throw e;
            ^
Error: Parse Error: Line 7: Unexpected token { (/Users/akshayp/foo.jsx)
    at throwError (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2155:21)
    at throwUnexpected (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:2217:9)
    at parseXJSIdentifier (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5347:13)
    at /usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5823:38
    at parseXJSAttribute (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5407:16)
    at /usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5823:38
    at parseXJSOpeningElement (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5458:29)
    at /usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5823:38
    at parseXJSElement (/usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5477:26)
    at /usr/local/lib/node_modules/jsx_orphaned_brackets_transformer/node_modules/jstransform/node_modules/esprima-fb/esprima.js:5823:38
```

**Comment by syranide** [comment]
@akshayp Sorry about that, #3384, you can apply it by hand if you're in a hurry :)

**Comment by akshayp** [comment]
@syranide Thanks for the super quick turnaround!

**Comment by zpao** [comment]
1.0.1 of jsx_orphaned_brackets_transformer is published. Update and you should be good to go. Thanks for filing!
