### ISSUE TITLE
Trying to check whether a button click event calls a function in JSX

### ISSUE THREAD

**Issue by hai2anand** [facebook/react#3452]
```
Error Result of - Expected: 0 toBe: 1
        at new jasmine.ExpectationResult (\node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:115:32)
        at null.toBe (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1236:29)
        at Spec.<anonymous> (\__tests__\Login-Test.js:33:65)
        at jasmine.Block.execute (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:1065:17)
        at jasmine.Queue.next_ (I\node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2098:31)
        at null._onTimeout (node_modules\jest-cli\vendor\jasmine\jasmine-1.3.0.js:2088:18)
        at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)
```

----------------------------------------------------------------------------------------------------

```js
// Unit Test case for Login.jsx
jest.dontMock('../src/js/pages/Login.jsx');

describe('login', function() {
    it('should invoke the btnLoginClick click event.', function() {     
        var React = require('react/addons');
        var LoginControl = require('../src/js/pages/Login.jsx');
       
        var TestUtils = React.addons.TestUtils;

        // Render a checkbox with label in the document
        var LoginUtil = TestUtils.renderIntoDocument(<LoginControl/>);  
  

       LoginControl.handleLoginClick = jest.genMockFunction();
      
        var input = TestUtils.findRenderedDOMComponentWithTag(
            LoginUtil, 'button');
        TestUtils.Simulate.click(input );
        expect(LoginControl.handleLoginClick.mock.calls.length).toBe(1);
     
    });
});
```

---------------------------------------------------------------------
Login.jsx

```js
/** @jsx React.DOM */
'use strict';
var React = require('react');
var FluxibleMixin = require('fluxible').Mixin;

var LoginStore = require('../stores/LoginStore.js');
var LoginActions = require('../actions/LoginActions.js');

var Login = React.createClass({
    mixins: [FluxibleMixin],
    statics: {
        storeListeners: [LoginStore]
    },

    getStateFromStores: function () {
        return this.getStore(LoginStore).getUser();

    },

    getInitialState: function () {
      return {
          isAuthenticated:false
      };
    },

    onChange: function () {
      this.setState(this.getStateFromStores());
    },

    handleLoginClick: function(event) {
        this.state.isAuthenticated=true;
        this.executeAction(LoginActions.loginUser, {
          userName: this.refs.userNameInput.getDOMNode().value,
          password: this.refs.passwordInput.getDOMNode().value
          
        });
        event.preventDefault();
    },

    render: function() {
      return (
          <div className="container">
              <form className="form-signin">
                  <a id="tip" href="#" data-toggle="tooltip" data-placement="bottom" title="Hover!">Hover me</a>
                  <h2 className="form-signin-heading">Please sign in</h2>
                  <label>{ this.state.loginMessage }</label>
                  <label htmlFor="inputEmail" className="sr-only">No address</label>
                  <input ref="userNameInput" type="email" defaultValue={this.state.userName} id="inputEmail" className="form-control" data-toggle="tooltip" data-placement="bottom" title="Please enter a valid email address!" placeholder="Email Address" required autofocus />
                  <label htmlFor="inputPassword" className="sr-only">Password</label>
                  <input ref="passwordInput" type="password" id="inputPassword" className="form-control" placeholder="Password" required />
                  <div className="checkbox">
                      <label>
                          <input type="checkbox" value="remember-me" /> Remember me
                      </label>
                  </div>
                  <button ref="btnSubmit" className="btn btn-lg btn-primary btn-block" onClick={this.handleLoginClick}>Sign in</button>
              </form>
            </div>

      );
    }
});

module.exports = Login;
```

-------------------------------------------------------------------

**Comment by tarjei** [comment]
Look at this line:

       LoginControl.handleLoginClick = jest.genMockFunction();

Because LoginControl should be viewed as a class here - not an object. So, you are mocking a method on the class object not the instance.

**Comment by jimfb** [comment]
This issue is old and hasn't been active for a while.  It also appears to be a usage question rather than a bug in the React core.  We use github issues to track bugs in the React core, so I'm going to close it out to take it off our radar.  Feel free to continue the discussion on this thread.
