### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mountComponent' of undefined

### ISSUE THREAD

**Issue by tcurdt** [facebook/react#3466]
After upgrading to 0.13.1 I am getting `Uncaught TypeError: Cannot read property 'mountComponent' of undefined` which turns out to be a "not so great" way of telling me not to use `React.createFactory` in JSX.

    /** @jsx React.DOM */
    var React = require("react");
    // var App = React.createFactory(require("../react/App"));
    var App = require("../react/App");
    React.render(<App/>, document.body);

On the other hand on the server side - outside of JSX it seems to be required to use `React.createFactory`

    var React = require("react");
    // var App = React.createFactory(require("../react/App"));
    var App = require("../react/App");
    module.exports = function(app) {
      app.get("/", function(req, res) {
        res.render("index.swig", {
          reactOutput: React.renderToString(App({}))
        });
      });
    };

otherwise I get

    TypeError: Cannot read property '__reactAutoBindMap' of undefined
       at Constructor (/app/node_modules/react/lib/ReactClass.js:842:15)
       at /app/app/server/routes.js:9:41
       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
       at next (/app/node_modules/express/lib/router/route.js:110:13)
       at Route.dispatch (/app/node_modules/express/lib/router/route.js:91:3)
       at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:82:5)
       at /app/node_modules/express/lib/router/index.js:267:22
       at Function.proto.process_params (/app/node_modules/express/lib/router/index.js:321:12)
       at next (/app/node_modules/express/lib/router/index.js:261:10)
       at SendStream.error (/app/node_modules/express/node_modules/serve-static/index.js:107:7)

which is pretty confusing.

**Comment by gaearon** [comment]
Sorry about no reply.

I think at this point most React users have gone through 0.12 -> 0.13 migration. We are now releasing v15, and I don’t think spending time on adding warnings about migrating off 0.12 patterns is something we plan to do at this point. This is why I’m closing this issue.

If you see others ways to improve the onboarding experience for new users and warn about potential problems please feel free to send a pull request! Thanks.
