### ISSUE TITLE
Teardown TestUtils method

### ISSUE THREAD

**Issue by robcolburn** [facebook/react#3557]
I'm doing some unit-testing on a module, to be used in an isomorphic app process. So, I write-up `server-side.js` and `client-side.js` for Mocha to consume.  Individually, they each run pretty good - so far.  However, after starting to use TestUtils in `client-side`, `server-side` starts failing on account of:

```
Uncaught ReferenceError: document is not defined
 at getActiveElement (~p/node_modules/react/lib/getActiveElement.js:23:12)
 at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (~p/node_modules/react/lib/ReactInputSelection.js:40:23)
 at ReactReconcileTransaction.Mixin.initializeAll (~p/node_modules/react/lib/Transaction.js:168:30)
 at ReactReconcileTransaction.Mixin.perform (~p/node_modules/react/lib/Transaction.js:133:12)
 at ReactUpdatesFlushTransaction.Mixin.perform (~p/node_modules/react/lib/Transaction.js:134:20)
 at ReactUpdatesFlushTransaction.assign.perform (~p/node_modules/react/lib/ReactUpdates.js:95:38)
 at Object.flushBatchedUpdates (~p/node_modules/react/lib/ReactUpdates.js:175:19)
 at Object.wrapper [as flushBatchedUpdates] (~p/node_modules/react/lib/ReactPerf.js:70:21)
 at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (~p/node_modules/react/lib/Transaction.js:207:25)
 at ReactDefaultBatchingStrategyTransaction.Mixin.perform (~p/node_modules/react/lib/Transaction.js:148:16)
 at Object.ReactDefaultBatchingStrategy.batchedUpdates (~p/node_modules/react/lib/ReactDefaultBatchingStrategy.js:66:19)
 at Object.enqueueUpdate (~p/node_modules/react/lib/ReactUpdates.js:215:22)
 at enqueueUpdate (~p/node_modules/react/lib/ReactUpdateQueue.js:30:18)
 at Object.ReactUpdateQueue.enqueueSetState (~p/node_modules/react/lib/ReactUpdateQueue.js:208:5)
 at ReactComponent.setState (~p/node_modules/react/lib/ReactComponent.js:69:20)
 at cb (~p/node_modules/reflux/src/connect.js:17:85)
 at EventEmitter.eventHandler (~p/node_modules/reflux/src/PublisherMethods.js:40:22)
 at EventEmitter.emit (~p/node_modules/reflux/node_modules/eventemitter3/index.js:72:35)
 at Store.module.exports.trigger (~p/node_modules/reflux/src/PublisherMethods.js:110:26)
 at Store.Reflux.createStore.onLoadFailed (~p/test/fixtures/WikiApp.js:40:10)
 at Store.Reflux.createStore.onLoadCompleted (~p/test/fixtures/WikiApp.js:35:12)
 at EventEmitter.eventHandler (~p/node_modules/reflux/src/PublisherMethods.js:40:22)
 at EventEmitter.emit (~p/node_modules/reflux/node_modules/eventemitter3/index.js:72:35)
 at Function.module.exports.trigger (~p/node_modules/reflux/src/PublisherMethods.js:110:26)
 at null._onTimeout (~p/node_modules/reflux/src/PublisherMethods.js:120:24)
 at Timer.listOnTimeout (timers.js:110:15)
```

Apparently, this line has kicked React into client-mode.

``` js
var node = TestUtils.renderIntoDocument(element);
```

That's not too bad, but I need way to kick React out of client-mode, so I can add it to my teardown method (aka `after`).

**Comment by robcolburn** [comment]
Should mention that my `client-side` is using `jsdom` which I've already wired to Mocha
```js
  beforeEach(function() {
    global.document = require('jsdom').jsdom();
    global.window = global.document.defaultView;
  });
  afterEach(function() {
    delete global.document;
    delete global.window;
  });
```

**Comment by robcolburn** [comment]
And, this is for open-source, so I can just point directly to the code. :D
https://github.com/robcolburn/reflux-preload/blob/master/test/client-side.js#L32

**Comment by ryoia** [comment]
I'm using jsdom with mocha for unit testing, ran into the same problem.

**Comment by gaearon** [comment]
React doesn’t have a notion of current mode anymore so this shouldn’t be an issue.
If you still see this with React 16 please provide a reproducing project.
