### ISSUE TITLE
Error: Invariant Violation: dangerouslyRenderMarkup(…): Cannot render markup in a worker thread

### ISSUE THREAD

**Issue by MoonTahoe** [facebook/react#3863]
The Error
-------------
I've read the other issues that relate to this issue and I am requiring React after globally defining window and document...

```
1) Reduced Test Case  Tests that Fail when Component changes state and renders "before each" hook:
 Error: Invariant Violation: dangerouslyRenderMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use React.renderToString for server rendering.
  at Context.<anonymous> (test/Reduced-spec.js:47:32)
```

The Component : Reduced.js
----------------------------------------

```javascript
var React = require('react');

var Reduced = React.createClass({

  getInitialState() {
      console.log("start off with editing as false");
      return {editing: false};
  },

  edit() {
      console.log("Setting State to Edit");
      this.setState({editing: true});
  },

  render() {
      console.log("Rendering");
      return (
          <span onClick={this.edit}>
            {(this.state.editing) ? "Editing" : "Click To Edit"}
          </span>
      );
  }

});

module.exports = Reduced;
```

The Tests : 1-pass, 1-fail
----------------------------------

```javascript
    var React, TestUtils, jsdom, Reduced, expect;

    describe('Reduced Test Case', function () {

        before(function () {

            jsdom = require('jsdom');
            global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
            global.window = global.document.parentWindow;

            React = require('react/addons');
            TestUtils = React.addons.TestUtils;

            Reduced = require('./Reduced');

            expect = require('chai').expect;

            this.component = TestUtils.renderIntoDocument(
                <Reduced />
            );

            var root = TestUtils.findRenderedDOMComponentWithTag(this.component, 'span');
            this.el = root.getDOMNode();

        });

        describe("Tests Pass without simulate", function () {

            it("Root Element Reads 'Click To Edit'", function () {
                expect(this.el.innerHTML).to.equal('Click To Edit');
            });

        });

        describe("Tests that Fail when Component changes state and renders", function () {

            beforeEach(function () {

                //
                //  Simulate invokes edit, invokes set state, invokes render, then error occures
                //

                TestUtils.Simulate.click(this.el);

            });

            it("Root Element Reads 'Editing'", function () {
                expect(this.el.innerHTML).to.equal('Editing');
            });

        });

    });
```

The Results
-----------------

```
> mocha --compilers js:babel/register

Reduced Test Case - @current
  start off with editing as false
  Rendering

Tests Pass without simulate
  ✓ Root Element Reads 'Click To Edit'

Tests that Fail when Component changes state and renders
  Setting State to Edit
  Rendering 

  1) "before each" hook


1 passing (379ms)
1 failing

1) Reduced Test Case Tests that Fail when Component changes state and renders "before each" hook:
Error: Invariant Violation: dangerouslyRenderMarkup(...): Cannot render markup in a worker thread. Make sure `window` and `document` are available globally before requiring React when unit testing or use React.renderToString for server rendering.
at Context.<anonymous> (test/Reduced-spec.js:47:32)
```

Why does this happen?  Is there a way to fix it?

**Comment by syranide** [comment]
https://github.com/facebook/react/blob/master/src/vendor/core/ExecutionEnvironment.js#L39
https://github.com/facebook/react/blob/master/src/vendor/core/ExecutionEnvironment.js#L16-L20

Your window is most likely not properly set up, `document.parentWindow` does not seem standard so I would expect it's your `window` which is not correct.

**Comment by MoonTahoe** [comment]
I placed all of the tests from ExecutionEnvironment.js directly into the before hook just before I require React.  All of them are passing, I get true returned for canUseDOM, and every other test.  

```javascript
before(function () {

        jsdom = require('jsdom');
        global.document = jsdom.jsdom('<!doctype html><html><body></body></html>');
        global.window = global.document.parentWindow;

        var canUseDOM = !!(
            typeof window !== 'undefined' &&
            window.document &&
            window.document.createElement
        );

        var canUseEventListeners = canUseDOM && !!(window.addEventListener || window.attachEvent);
        var canUseViewport = canUseDOM && !!window.screen;
        var isInWorker =  !canUseDOM;

        console.log(canUseDOM);                      // true
        console.log(canUseEventListeners);           // true
        console.log(canUseViewport);                 // true
        console.log(isInWorker);                    // false
        
        React = require('react/addons');
        TestUtils = React.addons.TestUtils;

        Reduced = require('../../../react-reflux/parts/Reduced');

        expect = require('chai').expect;

        this.component = TestUtils.renderIntoDocument(
            <Reduced />
        );

        var root = TestUtils.findRenderedDOMComponentWithTag(this.component, 'span');
        this.el = root.getDOMNode();

    });
```

**Comment by syranide** [comment]
@MoonTahoe It's possible the environment needs to be set up before React is required then.

**Comment by MoonTahoe** [comment]
@syranide, THANKS!  I isolated the tests in a separate branch and found out that I was missing the global.navigator...  I added this to the code and it works!

```javascript
global.navigator = {
     userAgent: 'node.js'
};
```

**Comment by zpao** [comment]
:thumbsup: Glad you worked it out! The environment checks are a little bit fragile :(
