### ISSUE TITLE
ReferenceError: location is not defined

### ISSUE THREAD

**Issue by mridgway** [facebook/react#4020]
Building off of master I am getting the following error:

```js
ReferenceError: location is not defined
    at Object.checkPropTypes (./react/master/react-with-addons.js:3576:56)
    at Constructor.componentWillMount (./react/master/react-with-addons.js:8369:82)
    at ReactCompositeComponentWrapper.mountComponent (./react/master/react-with-addons.js:5827:24)
    at Object.mountComponent (./react/master/react-with-addons.js:13048:21)
    at ReactCompositeComponentWrapper.mountComponent (./react/master/react-with-addons.js:5839:95)
    at Object.mountComponent (./react/master/react-with-addons.js:13048:21)
    at ReactDOMComponent.mountChildren (./react/master/react-with-addons.js:11857:17)
    at ReactDOMComponent._createContentMarkup (./react/master/react-with-addons.js:6996:94)
    at ReactDOMComponent.mountComponent (./react/master/react-with-addons.js:6900:18)
    at Object.mountComponent (./react/master/react-with-addons.js:13048:21)
```

Looks like an uninitialized variable here: https://github.com/facebook/react/blob/4c3e9650ba6c9ea90956a08542d9fa9b5d72ee88/src/renderers/dom/client/wrappers/LinkedValueUtils.js#L108

**Comment by zpao** [comment]
Looks like @spicyj broke it with #3976
