### ISSUE TITLE
TypeError when running in NODE_ENV production

### ISSUE THREAD

**Issue by quicksnap** [facebook/react#4489]
Here is an example repo: https://github.com/quicksnap/wtfreact

I'm using babel-node to execute `index.js`. When I turn off `production`, it works fine. When in production, I get the error below. Am I missing something really obvious?

```
TypeError: Cannot set property 'props' of undefined
    at Object.defineProperty.set [as props] (/Users/dan/projects/express/node_modules/react/lib/ReactElement.js:52:24)
    at Object.ReactElement (/Users/dan/projects/express/node_modules/react/lib/ReactElement.js:136:14)
    at Object.ReactElement.createElement (/Users/dan/projects/express/node_modules/react/lib/ReactElement.js:193:10)
    at Object.ReactElementValidator.createElement (/Users/dan/projects/express/node_modules/react/lib/ReactElementValidator.js:396:46)
    at Object.<anonymous> (/Users/dan/projects/express/wtf.js:11:19)
    at Module._compile (module.js:456:26)
    at normalLoader (/Users/dan/.nvm/v0.10.38/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dan/.nvm/v0.10.38/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
```

**Comment by zpao** [comment]
The problem is that you are changing `process.env.NODE_ENV` at runtime. React does a lot of initialization at require time based on the value of `NODE_ENV`. So React starts up thinking its in dev mode, does some initialization in ReactElement for prop mutation tracking and warning messages, then you switch it to prod mode which leaves us in a not so great state. Some dev code gets skipped but since we did setup some things before, those are still running (Eg, the use of `this._store`).

So the best thing is to not change environment variables during run time. I generally think that's a good rule of thumb in general, but it's especially true for React in node. `NODE_ENV=production npm start` is fine and the recommended way to run a production app.

**Comment by quicksnap** [comment]
Ah, I see now--thanks!

The reason I am setting NODE_ENV after startup is that I'm trying to set environment variables in a cross-platform way. With `npm-run-script`, doing `NODE_ENV=production npm start` will not work on Windows, AFAIK.

Anyway, not your problem! =) Thanks again.

**Comment by zpao** [comment]
Ah, well as long as you set NODE_ENV before the first require of react I think you should be ok.
