### ISSUE TITLE
React.createElement(null, null) - should it not throw?

### ISSUE THREAD

**Issue by mik01aj** [facebook/react#4575]
When I do:

    React.createElement(undefined, null)

(this sometimes happens because of a bug in my application)

It just gives a warning:

    Warning: React.createElement: type should not be null or undefined. It should be a string (for DOM elements) or a ReactClass (for composite components).

And only when rendering, it fails with one more warning and an error:

```
Warning: Only functions or strings can be mounted as React components.
react.js:9259
Uncaught TypeError: Cannot read property 'toUpperCase' of undefined
    at autoGenerateWrapperClass (https://facebook.github.io/react/js/react.js:9259:18)
    at Object.getComponentClassForElement (https://facebook.github.io/react/js/react.js:13201:49)
    at ReactCompositeComponentMixin._processProps (https://facebook.github.io/react/js/react.js:6615:44)
    at ReactCompositeComponentMixin.mountComponent (https://facebook.github.io/react/js/react.js:6313:28)
    at wrapper [as mountComponent] (https://facebook.github.io/react/js/react.js:13427:21)
    at Object.ReactReconciler.mountComponent (https://facebook.github.io/react/js/react.js:14128:35)
    at Object.__REACT_INSPECTOR_RUNTIME__0_13_1.React.ReactReconciler.mountComponent (<anonymous>:106:41)
    at mountComponentIntoNode (https://facebook.github.io/react/js/react.js:12038:32)
    at ReactReconcileTransaction.Mixin.perform (https://facebook.github.io/react/js/react.js:16683:20)
    at batchedMountComponentIntoNode (https://facebook.github.io/react/js/react.js:12059:15)
```

This makes bugs harder to debug, because in some cases (e.g. server-side rendering) the warnings can get lost in a log and only the error is visible (saying 'Uncaught TypeError: Cannot read property 'toUpperCase' of undefined'). Why are these warnings not errors then? I suppose that when element type is null, there is not much use of such an element and it's better to throw a meaningful error early.

Also, if the error is thrown earlier, I will get the stacktrace of the function call that actually passed `null` to the constructor. Then I can debug it easier.

I like the fact that you give warnings about stuff, but I think that in some cases errors would be even more helpful.

**Comment by spicyj** [comment]
I understand where you're coming from. We've switched to console.error in the latest version so you get a full stack trace in the console, and you can put a breakpoint at the warning callsite to catch it in your debugger. (Or check "Pause on Caught Exceptions" and you should get stopped in the debugger.) We should document this better.

We don't throw for a subtle reason: we want to allow inlining elements at compile time so that your example would be (approximately) equivalent to `{type: null, props: null}`, which wouldn't throw. Since we want to have the observable behavior match identically between dev and prod in all cases, we don't want to ever throw in createElement. Sorry that this makes debugging a little harder.

**Comment by mik01aj** [comment]
Glad you switched to `console.error`. Thanks for the explanation.
