### ISSUE TITLE
`grunt test` broken

### ISSUE THREAD

**Issue by springuper** [facebook/react#4590]
`grunt test` command is broken after commit `2f07935`, the error message is

```
Running "jest" task
running jest (this may take a while)
Using Jest CLI v0.4.18
 FAIL  src/addons/__tests__/ReactFragment-test.js
TypeError: Cannot read property 'length' of undefined
  at maybeReadMore_ (_stream_readable.js:426:18)
  at /Users/shangchun/Repos/react2/react/node_modules/jest-cli/src/lib/FakeTimers.js:342:7
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)

 FAIL  src/addons/transitions/__tests__/ReactTransitionChildMapping-test.js
Error: Attempted to send a message to the worker before the response from the last message was received! Worker processes can only handle one m
essage at a time.
 FAIL  src/addons/link/__tests__/ReactLinkPropTypes-test.js
TypeError: Cannot read property 'length' of undefined
  at maybeReadMore_ (_stream_readable.js:426:18)
  at /Users/shangchun/Repos/react2/react/node_modules/jest-cli/src/lib/FakeTimers.js:342:7
  at doNTCallback0 (node.js:408:9)
  at process._tickCallback (node.js:337:13)
...
```

**Comment by sairion** [comment]
It is also reproducible from my development environment. `@8f419c956ef9d1fc133859f822364435016f002a` breaks, actually.

**Comment by jimfb** [comment]
@2f07935 AFIK, `grunt test` still works in latest.  Have you done an `npm install` recently?

**Comment by jaredly** [comment]
I've got grunt test breaking for me to on master. fresh node modules, I tried iojs, node 0.12, and node 0.10.
:(

**Comment by zpao** [comment]
This is a result of using iojs / node 0.12. We don't currently build with either. We use node 0.10 and npm 2.x. (1.x will have a different issue).
