### ISSUE TITLE
Reference error in render is swallowed, results in `Cannot read property '_currentElement' of null`

### ISSUE THREAD

**Issue by mxdubois** [facebook/react#4639]
Using `react@0.14.0-beta2`

Rendering the following should reproduce it:
```
import React from 'react';
class MyComponent extends React.Component {
  render() {
    const handleSubmit = R.tap(console.log.bind(console));
    return (<div>foo</div>);
  }
}
```

The import for `R` is missing, thus causing a `ReferenceError`, but React seems to swallow that error and instead reports: 
```
Unhandled promise rejection TypeError: Cannot read property '_currentElement' of null
    at ReactCompositeComponentMixin._updateRenderedComponent (http://127.0.0.1:8020/assets/portal-application.js:101424:53)
    at ReactCompositeComponentMixin._performComponentUpdate (http://127.0.0.1:8020/assets/portal-application.js:101409:11)
    at ReactCompositeComponentMixin.updateComponent (http://127.0.0.1:8020/assets/portal-application.js:101338:13)
    at ReactPerf.measure.wrapper [as updateComponent] (http://127.0.0.1:8020/assets/portal-application.js:10491:22)
    at ReactCompositeComponentMixin.receiveComponent (http://127.0.0.1:8020/assets/portal-application.js:101270:11)
    at Object.ReactReconciler.receiveComponent (http://127.0.0.1:8020/assets/portal-application.js:11792:23)
    at ReactCompositeComponentMixin._updateRenderedComponent (http://127.0.0.1:8020/assets/portal-application.js:101427:24)
    at ReactCompositeComponentMixin._performComponentUpdate (http://127.0.0.1:8020/assets/portal-application.js:101409:11)
    at ReactCompositeComponentMixin.updateComponent (http://127.0.0.1:8020/assets/portal-application.js:101338:13)
    at ReactPerf.measure.wrapper [as updateComponent] (http://127.0.0.1:8020/assets/portal-application.js:10491:22)
```

This was pretty frustrating to debug so I hope it's fixable!

**Comment by syranide** [comment]
Just to be sure. Try running the same code in another browser (or with break on exceptions enabled), there have been spurious problems with browsers themselves silently dropping some errors.

**Comment by jimfb** [comment]
I just tried it in a fiddle (http://jsfiddle.net/5861bszr/).  Tested in both chrome and firefox; we are not swallowing the reference error.  I don't think this is a bug in React, but I'm happy to re-open/re-investigate if we can get a repro in the fiddle.
