### ISSUE TITLE
createFragment warning when rendering a Date

### ISSUE THREAD

**Issue by glenjamin** [facebook/react#4840]
```
<p>{new Date()}</p>
```

Looks to be hitting the typeof object check.

Not sure if it should cast to string or toISOString or just error.

**Comment by zpao** [comment]
Yes, this is the case where you're rendering an Object with keys, which is what we are deprecating. You should just stringify that yourself.

In this case you don't want to actually use `createFragment` so I could see the warning being a bit misleading. But we can't do typechecks to special case Date (could be your own types, etc). Maybe we should add something like "or convert to a primitive" to the warning.

**Comment by glenjamin** [comment]
One of our engineers was stuck on this for ages, as the error examples all show very different scenarios.

Perhaps include obj.toString() in the warning if it isn't [object Object] or some similar heuristic?

Alternatively, what if the warning was for `instanceof Object` and everything else got coerced to a string?

**Comment by spicyj** [comment]
We can improve this error a little bit.

**Comment by zpao** [comment]
I doubt we're going to start coercing here (eg, why wouldn't `{toString: function() { return 'foo' } }` be allowed) and the `instanceof` check isn't good enough (`Object.create(null) instanceof Object === false`).

Another helpful step with debugging: turn on pausing on caught exceptions. We throw and catch an error when warning to help with specifically this case.

Having more information in the warning is probably the best thing.

**Comment by glenjamin** [comment]
This actually popped up as we were adding unit tests to a component so we had a full stack trace (we convert warnings to thrown exceptions)- one of the downsides of the separate declare/render phases is that the stack trace rarely points to the relevant line in render() with errors like this.

We figured things out by doing as you suggest - inspecting exactly what value had caused React to decide to trigger the warning.

I think this suggests that including some representation of the erroring value might be the best addition to the warning?

**Comment by johann-sonntagbauer** [comment]
Is this issue solved now? I am currently migrating to 0.14 and found some components fail silent when rendering a JS Date object. 

one example:
```
<p>something {this.props.entity.someDateField}</p>
```

following stack occurs, that the initial rendering failed:
```
TypeError: Cannot read property 'componentWillUnmount' of null
    at ReactCompositeComponentMixin.unmountComponent (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:6758:14)
    at Object.ReactReconciler.unmountComponent (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:5061:23)
    at Object.ReactChildReconciler.updateChildren (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:15497:26)
    at ReactDOMComponent.ReactMultiChild.Mixin._reconcilerUpdateChildren (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:15113:40)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:15248:32)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:15223:15)
    at ReactDOMComponent.Mixin._updateDOMChildren (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:12596:13)
    at ReactDOMComponent.Mixin.updateComponent (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:12428:11)
    at ReactDOMComponent.Mixin.receiveComponent (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:12373:11)
    at Object.ReactReconciler.receiveComponent (http://localhost:3000/78f735c2c3e6e23f512b.boot.js:5096:23)
```

**Comment by zpao** [comment]
Converting to a string is the solution, not a workaround. Trying to render objects that are not ReactElements is no longer supported.

I actually see this error when rendering `<div>hello {new Date()}</div>`:

> `Error: Invariant Violation: Objects are not valid as a React child (found: Tue Oct 13 2015 10:02:35 GMT-0700 (PDT)). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of Hello.`

**Comment by johann-sonntagbauer** [comment]
@zpao thx for your answer. Tried to reproduce the problem in an simpler environment and the output looks exactly like yours. So my problem is related to some error in my components. 
Thx for your feedback
