### ISSUE TITLE
react-dom example doesn't work

### ISSUE THREAD

**Issue by matthewmueller** [facebook/react#4863]
```js
var React = require('react');
var ReactDOMServer = require('react-dom/server');

class MyComponent extends React.Component {
  render() {
    return <div>Hello World</div>;
  }
}

ReactDOMServer.renderToString(<MyComponent />);

```

yields:

```
 ☁  react-dom : babel-node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'react-dom/server'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/matt/Playground/react-dom/index.js:2:22)
    at Module._compile (module.js:460:26)
    at normalLoader (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```

**Comment by conorhastings** [comment]
what version of react/react-dom are you running? If you just did a standard npm install instead explicitly installing release candidate it probably won't work 

http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html

`npm install --save react@0.14.0-rc1`
`npm install --save react-dom@0.14.0-rc1`

**Comment by matthewmueller** [comment]
yes, that was it. thanks!

**Comment by amysimmons** [comment]
This also worked for me - thanks!

**Comment by kirisky** [comment]
It helps a lot, thank you!

**Comment by Alvarocz** [comment]
Thank you! it also worked for me

**Comment by gaearon** [comment]
@Alvarocz 

You should not be using `0.14-rc` anymore. The current version is `15.2.0` (and `react-dom/server` exists there).
