### ISSUE TITLE
Invalid property access when rendering server-side with Babel's "optimisation.react.inlineElements" enabled.

### ISSUE THREAD

**Issue by novacrazy** [facebook/react#4902]
When trying to render a page server-side I get an error like this:

```javascript
TypeError: Cannot read property 'validated' of undefined
    at validateExplicitKey (~/example.com/react-build/packages/react/lib/ReactElementValidator.js:60:21)
    at validateChildKeys (~/example.com/react-build/packages/react/lib/ReactElementValidator.js:132:9)
    at Object.ReactElementValidator.createElement (~/example.com/react-build/packages/react/lib/ReactElementValidator.js:230:7)
    at Row.render (~/example.com/views/components/bootstrap3/layout/row.jsx:13:24)
    at ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext (~/example.com/react-build/packages/react/lib/ReactCompositeComponent.js:587:34)
    at ReactCompositeComponentMixin._renderValidatedComponent (~/example.com/react-build/packages/react/lib/ReactCompositeComponent.js:607:32)
    at wrapper [as _renderValidatedComponent] (~/example.com/react-build/packages/react/lib/ReactPerf.js:66:21)
    at ReactCompositeComponentMixin.mountComponent (~/example.com/react-build/packages/react/lib/ReactCompositeComponent.js:220:30)
    at wrapper [as mountComponent] (~/example.com/react-build/packages/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (~/example.com/react-build/packages/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (~/example.com/react-build/packages/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (~/example.com/react-build/packages/react/lib/ReactDOMComponent.js:552:32)
    at ReactDOMComponent.Mixin.mountComponent (~/example.com/react-build/packages/react/lib/ReactDOMComponent.js:446:29)
    at Object.ReactReconciler.mountComponent (~/example.com/react-build/packages/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentMixin.mountComponent (~/example.com/react-build/packages/react/lib/ReactCompositeComponent.js:225:34)
    at wrapper [as mountComponent] (~/example.com/react-build/packages/react/lib/ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (~/example.com/react-build/packages/react/lib/ReactReconciler.js:37:35)
    at ReactDOMComponent.ReactMultiChild.Mixin.mountChildren (~/example.com/react-build/packages/react/lib/ReactMultiChild.js:241:44)
    at ReactDOMComponent.Mixin._createContentMarkup (~/example.com/react-build/packages/react/lib/ReactDOMComponent.js:552:32)
    at ReactDOMComponent.Mixin.mountComponent (~/example.com/react-build/packages/react/lib/ReactDOMComponent.js:446:29)
    at Object.ReactReconciler.mountComponent (~/example.com/react-build/packages/react/lib/ReactReconciler.js:37:35)
    at ReactCompositeComponentMixin.mountComponent (~/example.com/react-build/packages/react/lib/ReactCompositeComponent.js:225:34)
```

When using the Babel (5.8.24) transformer `optimisation.react.inlineElements`, after manually fixing https://github.com/babel/babel/issues/2377

However, when using the same transformer on my client code it runs just fine in the browser for even my most complex components/pages. 

Here is a complete list of my Babel options (for the server):
```javascript
{
    filename:     filename,
    blacklist:    [
        'es3.memberExpressionLiterals',
        'es3.propertyLiterals',
        'es6.forOf',
        'es6.properties.shorthand',
        'es6.templateLiterals'
    ],
    optional:     [
        'strict',
        'runtime',
        'spec.undefinedToVoid',
        'validation.react',
        'minification.constantFolding',
        'minification.propertyLiterals',
        'utility.inlineEnvironmentVariables',
        'es7.exportExtensions',
        'es7.classProperties', //For React static properties
        'optimisation.react.inlineElements',
        'optimisation.react.constantElements',
        'es7.decorators'
    ],
    ast:          false,
    sourceMaps:   false,
    nonStandard:  true, //JSX and Flow
    compact:      false,
    comments:     false,
    retainLines:  true,
    modules:      "amd",
    loose:        "all",
    experimental: true
} 
```

which might help track it down. The fact it worked in the browser leads me to believe it is not a Babel issue, though.

Currently I'm using a build of React from the master branch as of about thirty minutes ago.

**Comment by zpao** [comment]
I think I've seen this when setting `process.env.NODE_ENV` at runtime. Are you by chance doing that?

**Comment by novacrazy** [comment]
Not that I'm aware of. PM2 might do that, though, but that should only be at the start of the process before any React files are even loaded.

**Comment by novacrazy** [comment]
After forcing `process.env.NODE_ENV` to a read-only state in my startup script, I can confirm it does not change.

```javascript
const NODE_ENV = process.env.NODE_ENV;

Object.defineProperty( process.env, 'NODE_ENV', {
    value:        NODE_ENV,
    configurable: false,
    enumerable:   true,
    writable:     false
} );
```

**Comment by zpao** [comment]
Ah, I was thinking of something else. In this case the `inlineElements` transform isn't compatible with the dev version of React (which you're running by default on the server but you can force it into prod mode with `NODE_ENV=production node app.js`).

I'm going to close this and point you to #3285 which also brought this issue up and we have slated to fix up before 0.14 goes final.

**Comment by novacrazy** [comment]
Ah, thank you very much. It does indeed work fine in production, yielding a nice 4-25ms (~10-15%) speedup on pages, depending upon complexity. Very nice.

**Comment by geekyme** [comment]
hey im getting the same problems too when i use the 2 new react optimisations 

```
'optimisation.react.inlineElements',
'optimisation.react.constantElements',
```

I also get things like the below even if I only compile with the above optimisations in production: 

```
Error: Invariant Violation: renderToString(): You must pass a valid ReactElement.
```
