### ISSUE TITLE
react-addons-test-utils invariant violation with body tag

### ISSUE THREAD

**Issue by zackify** [facebook/react#4948]
With the latest react 0.14rc, when trying to render a component with a body tag I get

```
Error: Invariant Violation: findComponentRoot(..., .1dqu0l59p1c): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.
      at invariant (/Users/zachsilveira/Web/legit-tests/node_modules/react/node_modules/fbjs/lib/invariant.js:39:15)
      at Object.ReactMount.findComponentRoot (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactMount.js:752:54)
      at Object.ReactMount.findReactNodeByID (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactMount.js:667:23)
      at Object.getNode (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactMount.js:162:32)
      at ReactDOMComponent.Mixin.getPublicInstance (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactDOMComponent.js:872:29)
      at findAllInRenderedTreeInternal (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactTestUtils.js:45:25)
      at findAllInRenderedTreeInternal (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactTestUtils.js:57:22)
      at Object.ReactTestUtils.findAllInRenderedTree (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactTestUtils.js:145:12)
      at Object.ReactTestUtils.scryRenderedDOMComponentsWithTag (/Users/zachsilveira/Web/legit-tests/node_modules/react/lib/ReactTestUtils.js:183:27)
      at Test.find (/Users/zachsilveira/Web/legit-tests/src/middleware/find.js:13:29)
      at Test.find (/Users/zachsilveira/Web/legit-tests/src/legit-tests.js:50:10)
      at Context.<anonymous> (/Users/zachsilveira/Web/legit-tests/tests/simulate.jsx:26:6)
      at callFn (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runnable.js:286:21)
      at Test.Runnable.run (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runnable.js:279:7)
      at Runner.runTest (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:421:10)
      at /Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:528:12
      at next (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:341:14)
      at /Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:351:7
      at next (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:283:14)
      at Immediate._onImmediate (/Users/zachsilveira/Web/legit-tests/node_modules/mocha/lib/runner.js:319:5)
      at processImmediate [as _immediateCallback] (timers.js:371:17)
```

I have a simple component:

``` js
render(){
    return <body>
      <div onClick={this.props.onClick}>{this.state.test}</div>
      <p className="box">found me!</p>
      <button
        type="button"
        onClick={this.props.onClick}>
        Click Me
      </button>
      <button
        type="button"
        onClick={this.props.onClick}>
        Click Me
      </button>
      <TinyComponent test="true"/>
    </body>
  }
```

Doing: 

```
var instance = TestUtils.renderIntoDocument(React.createElement(TestComponent, null));
var elements = TestUtils.scryRenderedDOMComponentsWithTag(instance, 'button');

console.log(elements);
```

Returns the error from above. If you replace the body tags with something else, everything works.

**Comment by zpao** [comment]
RenderIntoDocument creates a div and renders into that element. The DOM is almost certainly unhappy in that case and moves things around resulting in that error. Using body is tough since it's only valid as a child of documentElement and I think we actually warn when you try to render there. You can try doing that.

Fwiw, this issue should not be new in 0.14 and ultimately I don't think we can do much for you - you're fighting the DOM.

**Comment by zackify** [comment]
It was new in 0.14. I was actually making the component just for a tests
library I made and there were absolutely no problems with it in 0.13. This
issue doesn't matter to me, really just found it interesting and wasn't
even sure if it was worth creating an issue for.

**Comment by graue** [comment]
Should React warn when a component tries to render a `<body>` tag? There's no legit reason to do so, right?

Just saw a case where a component was rendering redundant `<body>` tags. It had worked in 0.13. In 0.14, it still rendered, but click handlers inside weren't firing.

**Comment by jimfb** [comment]
@graue Sometimes for SSR FPR, people want to render a body tag.  We generally discourage it, but it's a semi-common use case and is supported IIRC.

**Comment by graue** [comment]
Maybe we can warn when it's being rendered into a real DOM, then?

Anyway, I just realized this issue is about the test utils. My issue is not, so I filed #5484 instead.

**Comment by gaearon** [comment]
Going to close since I don’t think it’s super important, and primarily was a misunderstanding. If you disagree let me know.
