### ISSUE TITLE
Misleading error messages in presence of unnecessary `createFactory`

### ISSUE THREAD

**Issue by gasi** [facebook/react#5039]
When porting non-JSX React code, e.g. CoffeeScript, to JSX and forgetting to remove unnecessary `createFactory` calls, the following warnings / errors are issued which (seemingly) are unrelated to the root cause:

```
Warning: bound scrollValueMonitor(...): No `render` method found on the
returned component instance: you may have forgotten to define `render` in
your component or you may have accidentally tried to render an element
whose type is a function that isn't a React component.

Warning: Don't set the props property of the React element.
Instead, specify the correct value when initially creating the element.

TypeError: Can't add property context, object is not extensible
at ReactCompositeComponentMixin.mountComponent (react.js:6339:18)
    at wrapper [as mountComponent] (react.js:13427:21)
    at Object.ReactReconciler.mountComponent (react.js:14128:35)
    at mountComponentIntoNode (react.js:12038:32)
    at ReactReconcileTransaction.Mixin.perform (react.js:16683:20)
    at batchedMountComponentIntoNode (react.js:12059:15)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (react.js:16683:20)
    at Object.ReactDefaultBatchingStrategy.batchedUpdates (react.js:9199:19)
    at Object.batchedUpdates (react.js:14914:20)
    at Object.ReactMount._renderNewRootComponent (react.js:12194:18)
```

### Repro

https://jsbin.com/vetoqi/2/edit?html,js,console

### Source

Originally noted in https://github.com/oncletom/Imager.jsx/issues/12, but if you google

```
No `render` method found on the returned component instance
```
many other potential related issues show up.

**Comment by spicyj** [comment]
Yeah, we can probably add a warning for this.

**Comment by gasi** [comment]
:+1: Thanks, @spicyj. I think I understand why you warn on `render` method missing as a double factory probably doesn’t have it, but it can be a baffling when one runs into it, so I appreciate the help :sos:

**Comment by spicyj** [comment]
Another report of this being confusing internally:

![image](https://cloud.githubusercontent.com/assets/6820/12654746/668e67b0-c5aa-11e5-8a1c-674fd30eb208.png)

**Comment by gaearon** [comment]
We should just kill factories. #6169
