### ISSUE TITLE
renderToString on stateless function

### ISSUE THREAD

**Issue by uptownhr** [facebook/react#5228]
Is this possible? I'm currently getting a warning & error

```
Warning: Component(...): No `render` method found on the returned component instance: you may have forgotten to define `render` in your component or you may have accidentally tried to render an element whose type is a function that isn't a React component.
Warning: Don't set the props property of the React element. Instead, specify the correct value when initially creating the element.


TypeError: Can't add property context, object is not extensible
      at [object Object].ReactCompositeComponentMixin.mountComponent (/Users/uptown/Projects/Personal/blog/node_modules/react/lib/ReactCompositeComponent.js:153:18)
      at [object Object].wrapper [as mountComponent] (/Users/uptown/Projects/Personal/blog/node_modules/react/lib/ReactPerf.js:70:21)
      at /Users/uptown/Projects/Personal/blog/node_modules/react/lib/ReactServerRendering.js:42:27
      at ReactServerRenderingTransaction.Mixin.perform (/Users/uptown/Projects/Personal/blog/node_modules/react/lib/Transaction.js:134:20)
      at Object.renderToString (/Users/uptown/Projects/Personal/blog/node_modules/react/lib/ReactServerRendering.js:39:24)

```

```
let test = (props) => (
  <div>test</div>
)

react.renderToString(test())
``

**Comment by uptownhr** [comment]
sorry this is a non issue. I had createFactory going but it is not needed.
