### ISSUE TITLE
SyntaxError when I trying to compile main.js as described in tutorial

### ISSUE THREAD

**Issue by nikit-cpp** [facebook/react#5354]
I read http://facebook.github.io/react/docs/getting-started.html

What i did:
sudo npm install -g browserify
npm install --save react react-dom
npm install --save babelify
touch main.js
```
// main.js
var React = require('react');
var ReactDOM = require('react-dom');

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('example')
);
```

Next, I call
browserify -t babelify main.js -o bundle.js
And I got SyntaxError
```
[nik@fedora tut]$ browserify -t babelify main.js -o bundle.js
SyntaxError: /media/files596/Programming/Examples-Web/React/tut/main.js: Unexpected token (6:2)
  4 | 
  5 | ReactDOM.render(
> 6 |   <h1>Hello, world!</h1>,
    |   ^
  7 |   document.getElementById('example')
  8 | );
    at Parser.pp.raise (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/location.js:24:13)
    at Parser.pp.unexpected (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.parseExprAtom (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:507:12)
    at Parser.pp.parseExprSubscripts (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:260:19)
    at Parser.pp.parseMaybeUnary (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:240:19)
    at Parser.pp.parseExprOps (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:171:19)
    at Parser.pp.parseMaybeConditional (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:153:19)
    at Parser.pp.parseMaybeAssign (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:120:19)
    at Parser.pp.parseExprListItem (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:966:16)
    at Parser.pp.parseCallExpressionArguments (/media/files596/Programming/Examples-Web/React/tut/node_modules/babelify/node_modules/babel-core/node_modules/babylon/lib/parser/expression.js:336:20)
```

**Comment by bshy522** [comment]
![image](https://cloud.githubusercontent.com/assets/1124573/10867318/12bb3982-8096-11e5-9754-4cbbe503c536.png)

**Comment by nikit-cpp** [comment]
```
sudo npm install -g babel babel-preset-react

[nik@fedora tut]$ babel --presets react --watch src/ --out-dir lib/
The CLI has been moved into the package `babel-cli`.

$ npm install -g babel-cli

[nik@fedora tut]$ babel-cli --presets react --watch src/ --out-dir lib/
bash: babel-cli: command not found
[nik@fedora tut]$ sudo npm install -g babel-cli
npm WARN optional dep failed, continuing fsevents@1.0.2
npm ERR! Refusing to delete: /usr/bin/babel not in /usr/lib/node_modules/babel-cli
File exists: /usr/bin/babel
Move it away, and try again. 

npm ERR! System Linux 4.1.10-200.fc22.x86_64
npm ERR! command "/usr/bin/node" "/bin/npm" "install" "-g" "babel-cli"
npm ERR! cwd /media/files596/Programming/Examples-Web/React/tut
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! path /usr/bin/babel
npm ERR! code EEXIST
npm ERR! error rolling back Error: Refusing to delete: /usr/bin/babel not in /usr/lib/node_modules/babel-cli
npm ERR! error rolling back     at clobberFail (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:57:12)
npm ERR! error rolling back     at next (/usr/lib/node_modules/npm/lib/utils/gently-rm.js:43:14)
npm ERR! error rolling back     at /usr/lib/node_modules/npm/lib/utils/gently-rm.js:52:12
npm ERR! error rolling back     at Object.oncomplete (evalmachine.<anonymous>:108:15)
npm ERR! error rolling back  { [Error: Refusing to delete: /usr/bin/babel not in /usr/lib/node_modules/babel-cli] code: 'EEXIST', path: '/usr/bin/babel' }
npm ERR! not ok code 0
[nik@fedora tut]$ 
```

**Comment by bshy522** [comment]
you can see https://github.com/babel/babel/tree/master/packages/babel-cli/bin.

so
 ```sh
npm uninstall -g babel
npm install -g babel-cli babel-preset-react
babel --presets react --watch src/ --out-dir lib/
``

`babel` moved into `babel-core`.
`babel-cli` contain executable file `babel`.
`babel-cli` package depends on the `babel-core`

**Comment by nikit-cpp** [comment]
Thanks, I've already done that, but there was an error and I thought that I was doing something wrong.

sudo npm uninstall -g babel
sudo npm install -g babel-cli babel-preset-react

```
[nik@fedora tut]$ babel --presets react --watch src/ --out-dir lib/
ReferenceError: [BABEL] src/main.js: Unknown option: /media/files596/Programming/Examples-Web/React/tut/node_modules/react/react.js.Children
    at Logger.error (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/logger.js:43:11)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:244:18)
    at OptionManager.mergePresets (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:16)
    at OptionManager.mergeOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:269:12)
    at OptionManager.init (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/options/option-manager.js:395:10)
    at File.initOptions (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:191:75)
    at new File (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/file/index.js:122:22)
    at Pipeline.transform (/usr/lib/node_modules/babel-cli/node_modules/babel-core/lib/transformation/pipeline.js:42:16)
    at transform (/usr/lib/node_modules/babel-cli/lib/babel/util.js:53:22)
    at Object.compile (/usr/lib/node_modules/babel-cli/lib/babel/util.js:62:12)
```

**Comment by msmicker** [comment]
also experiencing the precise same issue

**Comment by bshy522** [comment]
@nikit-cpp maybe some wrong on `src/main.js`.  need to review the code in detail.
@msmicker could u pls show some detail？

**Comment by zpao** [comment]
Babel 6 came out and the docs need to be updated to reflect that. We'll finish getting those updated today.

Here's the minimal bits you need, assuming you have any es2015 code that needs to be transformed.

```
npm i -g babel-cli
npm i babel-preset-es2015 babel-preset-react
babel --presets es2015,react --watch src/ --out-dir lib/
```

For anybody having specific issues using babel, this is not the right place to file issues. More than likely that will be an issue you need to bring up against that project.

**Comment by anztrax** [comment]
thanks :+1: , this is helped man

**Comment by wpcarro** [comment]
@zpao: thanks for the help. This fixed a few of my issues. However, how can I shoehorn browserify into this equation? I have 2 require statements at the top of my `main.js` code that need to pass through browserify in order to resolve dependencies. It appears to me that the `browserify -t babelify --presets es2015,react main.js -o build/main.js` isn't working... any ideas?

**Comment by zpao** [comment]
@wpcarro no idea, that's what browserify is supposed to solve for you.

**Comment by GGAlanSmithee** [comment]
This is a shot in the dark since I don't knowbwhat errors you ae getting (if any) but try `browserify main.js -t [ babelify --presets [ es2015 react ]  ] -o build/main.js`

**Comment by wpcarro** [comment]
@zpao: I am just trying to follow Facebook's documentation. `$ browserify -t [ babelify --presets [ react ] ] main.js -o bundle.js` from https://facebook.github.io/react/docs/getting-started.html does not work; I didn't know if you had any insights on this. Thank you for the response nonetheless.

@GGAlanSmithee: it seems as if `browserify` throws an error when it encounters JS syntax errors. The flow I think has to begin with babel and then filter down through browserify. For future users, I wrote a simple shell script to quickly automate transpiling + browserifying

```
babel --presets es2015,react scripts/**/*.js --out-dir transpiled/
browserify transpiled/**/*.js --o build/bundle.js
```

**Comment by nikit-cpp** [comment]
I' ve installed https://github.com/babel/babelify
npm install --save-dev babelify
and following command began to work
browserify main.js -o bundle.js -t [ babelify --presets [ es2015 react ] ]

**Comment by nikit-cpp** [comment]
finally all commands in same place:
sudo npm install -g babel-cli
sudo npm install -g browserify
npm install react react-dom babelify babel-preset-es2015 babel-preset-react

browserify src/main.js -o bundle.js -t [ babelify --presets [ es2015 react ] ]

**Comment by xing-kenny** [comment]
E:\react\gt\demo4>babel -V
 6.2.0 (babel-core 6.2.1)

E:\react\gt\demo4>babel --presets es2015,react --watch src/ --out-dir build
 SyntaxError: src/random-message.jsx: Unexpected token (4:8)

    2 |   render: function() {
    3 |           return (
  > 4 |                   {this.props.message}
       |         ^
    5 |           )
    6 |   }
    7 | });

**Comment by allardhoeve** [comment]
Docs are still not up to date. Any news?
