### ISSUE TITLE
React TestUtils -- PhantomJS -- Error: Invariant Violation: A valid ReactComponent must be returned.

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#5435]
When I use the Chrome driver, everything works, but when I use PhantomJS, I get this error.

```
Error: Invariant Violation: UserVerification.render(): A valid ReactComponent must be returned. You may have returned undefined, an array or some other invalid object.
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:19177 <- node_modules/react/node_modules/fbjs/lib/invariant.js:46:0
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:6198 <- node_modules/react/lib/ReactCompositeComponent.js:614:0
	    at ReactCompositeComponent__renderValidatedComponent (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:12638 <- node_modules/react/lib/ReactPerf.js:67:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:5805 <- node_modules/react/lib/ReactCompositeComponent.js:221:0
	    at ReactCompositeComponent_mountComponent (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:12638 <- node_modules/react/lib/ReactPerf.js:67:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:13268 <- node_modules/react/lib/ReactReconciler.js:37:0
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:5810 <- node_modules/react/lib/ReactCompositeComponent.js:226:0
	    at ReactCompositeComponent_mountComponent (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:12638 <- node_modules/react/lib/ReactPerf.js:67:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:13268 <- node_modules/react/lib/ReactReconciler.js:37:0
	    at mountComponentIntoNode (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:11136 <- node_modules/react/lib/ReactMount.js:267:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:16410 <- node_modules/react/lib/Transaction.js:137:0
	    at batchedMountComponentIntoNode (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:11152 <- node_modules/react/lib/ReactMount.js:283:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:16410 <- node_modules/react/lib/Transaction.js:137:0
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:8713 <- node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:0
	    at batchedUpdates (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:14477 <- node_modules/react/lib/ReactUpdates.js:95:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:11346 <- node_modules/react/lib/ReactMount.js:477:0
	    at ReactMount__renderNewRootComponent (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:12638 <- node_modules/react/lib/ReactPerf.js:67:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:11420 <- node_modules/react/lib/ReactMount.js:551:0
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:11440 <- node_modules/react/lib/ReactMount.js:571:0
	    at React_render (/var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:12638 <- node_modules/react/lib/ReactPerf.js:67:0)
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:13724 <- node_modules/react/lib/ReactTestUtils.js:77:0
	    at /var/folders/m7/3gdk200j7knfsm3p72_yhx_40000gn/T/92c71dfb3245879cfe13bd64ebe2dae8.browserify:19885 <- component.js:46:24

```

Here's my test:

```js
let showError, clearError, onComplete, uv, renderer;
  
  beforeEach(function() {
    showError = jasmine.createSpy('showError')
    clearError = jasmine.createSpy('clearError')
    onComplete = jasmine.createSpy('onComplete')
    
    uv = TestUtils.renderIntoDocument(
      <UserVerification showError={showError} 
                        clearError={clearError} 
                        onComplete={onComplete} />
    )
    
    spyOn(api, 'initiateVerification').and.callFake(() => new Promise(()=>{}))
    spyOn(window, 'fetch').and.callFake(() => new Promise(()=>{}))
  })  
  
  it("initiateVerification(type)", function() {
    TestUtils.Simulate.change(
      TestUtils.findRenderedDOMComponentWithTag(uv, 'select'),
      {target: {value: 'license'}}
    )
    expect(api.initiateVerification).toHaveBeenCalledWith('license')
  })
```

**Comment by jimfb** [comment]
Yeah, we dropped support for phantomJS a while ago.

See: https://github.com/facebook/react/pull/4393
> phantomJS (old, not a real browser, even with shims...
