### ISSUE TITLE
TestUtil.renderIntoDocument issue with refs

### ISSUE THREAD

**Issue by ccorcos** [facebook/react#5453]
I'm quite unsure where this error is coming from.

```
Error: Invariant Violation: addComponentAsRefTo(...): Only a ReactOwner can have refs. You might be adding a ref to a component that was not created inside a component's `render` method, or you have multiple copies of React loaded (details: https://fb.me/react-refs-must-have-owner).
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:26176 <- node_modules/react/node_modules/fbjs/lib/invariant.js:46:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:19543 <- node_modules/react/lib/ReactOwner.js:68:0
    at attachRef (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:20361 <- node_modules/react/lib/ReactRef.js:23:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:20380 <- node_modules/react/lib/ReactRef.js:42:0
    at attachRefs (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:20251 <- node_modules/react/lib/ReactReconciler.js:21:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:8011 <- node_modules/react/lib/CallbackQueue.js:66:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:20159 <- node_modules/react/lib/ReactReconcileTransaction.js:81:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:23475 <- node_modules/react/lib/Transaction.js:203:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:23422 <- node_modules/react/lib/Transaction.js:150:0
    at batchedMountComponentIntoNode (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:18151 <- node_modules/react/lib/ReactMount.js:283:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:23409 <- node_modules/react/lib/Transaction.js:137:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:15712 <- node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:0
    at batchedUpdates (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:21476 <- node_modules/react/lib/ReactUpdates.js:95:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:18345 <- node_modules/react/lib/ReactMount.js:477:0
    at ReactMount__renderNewRootComponent (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:19637 <- node_modules/react/lib/ReactPerf.js:67:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:18419 <- node_modules/react/lib/ReactMount.js:551:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:18439 <- node_modules/react/lib/ReactMount.js:571:0
    at React_render (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:19637 <- node_modules/react/lib/ReactPerf.js:67:0)
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:20723 <- node_modules/react/lib/ReactTestUtils.js:77:0
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:33989 <- /Users/jankarlorodriguez-rivera/Projects/web-ux/user-portal/test/spec/ui/dollar-input.coffee:11:16
    at /var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:33991 <- /Users/jankarlorodriguez-rivera/Projects/web-ux/user-portal/test/spec/ui/dollar-input.coffee:6:31
    at newRequire (/var/folders/br/b9kks4y50qvfl_1cr22jj1_c0000gn/T/7fc1a283a49574bce1059aa1c5f740be.browserify:75 <- /Users/jankarlorodriguez-rivera/Projects/web-ux/node_modules/proxyquireify/lib/prelude.js:75:0)
    at /Users/jankarlorodriguez-rivera/Projects/web-ux/user-portal/test/spec/ui/dollar-input.coffee:1
```

I'm using coffeescript because the other tests are written in coffeescript but (1) I tried it with JSX and the same error and (2) it should matter anyways.

Do here's my component, and it has a ref:

```jsx
React.createClass({
  displayName: 'DollarInput',
  // ...
  render: function() {
    return (
      <input
        ref="input"
        onChange={this.onChange}
        onKeyDown={this.onKeyDown}
        onBlur={this.onBlur}
        value={this.state.amount}
        className={this.props.className}
        id={this.props.id}
        autoComplete="off"/>
    )
  }
});
```

And here's my test -- using jasmine, karma, and phantomjs.

```coffee
TestUtils = require('react-addons-test-utils')
DollarInput = React.createFactory(require('user-portal/src/scripts/ui/dollar-input'))

describe "React dollar input", ->
  dollarInput = TestUtils.renderIntoDocument(DollarInput())
```

Any ideas where that error comes from?

Some trouble shooting:

- It says maybe I may have two instances of react being loaded. Well, I'm using bower and adding the proper files in my karma configuration:

```js
files: [
  'bower_components/react/react.js',
  'bower_components/react/react-dom.js',
  // ...
  'test/*.coffee'
]
```

I don't believe `require('react-addons-test-utils')` includes another version of React. And I wouldnt imagine Karma is loading react more than once either...

- I don't believe I'm adding a ref outside the component's render function either. But when I remove the ref, then I dont get this error -- but the component wont work properly...

```jsx
React.createClass({
  displayName: 'DollarInput',
  // ...
  render: function() {
    return (
      <input
        onChange={this.onChange}
        onKeyDown={this.onKeyDown}
        onBlur={this.onBlur}
        value={this.state.amount}
        className={this.props.className}
        id={this.props.id}
        autoComplete="off"/>
    )
  }
});
```

**Comment by jimfb** [comment]
You have a lot of code here.  It might be helpful to try to simplify your example before asking about it.  Also, if you haven't already, don't forget to check out https://fb.me/react-refs-must-have-owner

This is a usage question, rather than a bug in the React core. Usage questions are better answered on sites like StackOverflow, as we try to use github issues for tracking bugs in the React core. For this reason, I'm going to close out this issue, but feel free to continue the conversation here or move it to StackOverflow.
