### ISSUE TITLE
I have a react-native bundle server. When process multi request , got Errors at Create ReactPackager step.

### ISSUE THREAD

**Issue by kahoku** [facebook/react#5566]
stdout：bundle: Created ReactPackager

stderr：uncaught error Error: Error: Unable to find file with path: null
    at Fastfs.readFile (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/fastfs.js:97:13)
    at Module._read (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/Module.js:85:36)
    at /Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/Module.js:71:12
    at Cache.get (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/Cache/index.js:68:36)
    at Module.getDependencies (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/Module.js:70:24)
    at collect (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:108:20)
    at /Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/DependencyResolver/DependencyGraph/ResolutionRequest.js:145:14
    at tryCallOne (/Users/star/Work/reactnative/node_modules/react-native/node_modules/promise/lib/core.js:37:12)
    at /Users/star/Work/reactnative/node_modules/react-native/node_modules/promise/lib/core.js:103:15
    at flush (/Users/star/Work/reactnative/node_modules/react-native/node_modules/promise/node_modules/asap/raw.js:50:29)
See logs /var/folders/kh/xrfg_8hs0psd8w1czfh4vcy40000gn/T/react-packager.log
    at SocketClient._handleMessage (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:131:23)
    at BunserBuf.<anonymous> (/Users/star/Work/reactnative/node_modules/react-native/packager/react-packager/src/SocketInterface/SocketClient.js:52:42)
    at emitOne (events.js:77:13)
    at BunserBuf.emit (events.js:169:7)
    at BunserBuf.process (/Users/star/Work/reactnative/node_modules/react-native/node_modules/bser/index.js:289:10)
    at /Users/star/Work/reactnative/node_modules/react-native/node_modules/bser/index.js:244:12
    at doNTCallback0 (node.js:407:9)
    at process._tickCallback (node.js:336:13)

This's why? how to slove it

**Comment by zpao** [comment]
Please file React Native issues in their repo: https://github.com/facebook/react-native

**Comment by kahoku** [comment]
ok, sorry for my fault

**Comment by DeveloperCaladan** [comment]
nnnnnn.
