### ISSUE TITLE
can't use variable containing html to set inner contents of tag. 

### ISSUE THREAD

**Issue by DavidAwad** [facebook/react#5743]
So I'm getting an error from babel when trying to use the DangerouslySet inner html for a div. 
I'm using a gulpfile to watch my jsx files. 

gulpfile:

```
const gulp = require('gulp');
const react = require('gulp-babel');
const babel = require('gulp-babel');

/* Path object for convenience */
var paths = {
  JSX: ['static/jsx/*.jsx'],
  JS:  ['static/js']
};

gulp.task('transform', () => {
    return gulp.src(paths.JSX)
        .pipe(babel({
            presets: ['react']
        }))
        .pipe(gulp.dest('static/js'));
});
gulp.task('watch', function(){
  gulp.watch(paths.JSX, ['transform']);
});
gulp.task('default', ['watch']);

```
So the problem is when I try to use the `__html:` in my code. It complains the tokens were unexpected.  
`local_events` is an array that I'm mapping over to return list elements for each item in the list. 
`item.description` is a string containing html <p> tags. 

`item.description`: " <p> this is a paragraph that's not being interpreted as html but instead being rendered as literal text content which isn't what I was hoping</p>    "

```js
    return (
        <ul>
            {local_events.map(function(item) {
                console.log(item)
                return <li key={(item.time * Math.random())}> <div dangerouslySetInnerHTML={__html:item.description}/> <hr/> </li>
            })}
        </ul>
    )
```

Is this a React problem? Or is it Babel's linter? Stack trace is below. 

```
[20:30:56] Starting 'transform'...

events.js:141
      throw er; // Unhandled 'error' event
      ^
SyntaxError: /Users/david/Desktop/meetup-project/static/jsx/Parent.jsx: Unexpected token (75:98)
  73 |             {local_events.map(function(item) {
  74 |                 console.log(item)
> 75 |                 return <li key={(item.time * Math.random())}> <div dangerouslySetInnerHTML={__html:item.description}/> <hr/> </li>
     |                                                                                                   ^
  76 |             })}
  77 |         </ul>
  78 |     )
    at Parser.pp.raise (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/parser/location.js:22:13)
    at Parser.pp.unexpected (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/parser/util.js:91:8)
    at Parser.pp.expect (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/parser/util.js:85:33)
    at Parser.pp.jsxParseExpressionContainer (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:293:8)
    at Parser.pp.jsxParseAttributeValue (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:256:19)
    at Parser.pp.jsxParseAttribute (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:308:58)
    at Parser.pp.jsxParseOpeningElementAt (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:319:31)
    at Parser.pp.jsxParseElementAt (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:341:29)
    at Parser.pp.jsxParseElementAt (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:354:30)
    at Parser.pp.jsxParseElement (/Users/david/Desktop/meetup-project/node_modules/babylon/lib/plugins/jsx/index.js:390:15)
```

**Comment by DavidAwad** [comment]
based on [this](https://facebook.github.io/react/tips/dangerously-set-inner-html.html) page.

**Comment by DavidAwad** [comment]
Solved it! I still think it should work differently, or have a more clear explanation that you can't set an html attribute with a JSON object directly. 

```js
    return (
        <ul>
            {local_events.map(function(item) {
                function createMarkup(item) { return {__html: item.description}; }
                return <Child key={(item.time * Math.random())}> <div dangerouslySetInnerHTML={createMarkup(item)}/> <hr/> </li>
            })}
        </ul>
    )
```

**Comment by yangshun** [comment]
On a side note, you shouldn't use random keys: https://github.com/facebook/react/issues/1342#issuecomment-39230939

**Comment by trusktr** [comment]
> On a side note, you shouldn't use random keys: #1342 (comment)

The random key prevents React from doing any meaningful performance improvement.
