### ISSUE TITLE
Shallow rendering broken with 0.14.5

### ISSUE THREAD

**Issue by jithin1987** [facebook/react#5786]
After upgrading to 0.14.5 I find few test cases failing with 
```
 ReferenceError: document is not defined
      at getActiveElement (node_modules/react/node_modules/fbjs/lib/getActiveElement.js:25:12)
      at ReactReconcileTransaction.ReactInputSelection.getSelectionInformation (node_modules/react/lib/ReactInputSelection.js:38:23)
      at ReactReconcileTransaction.Mixin.initializeAll (node_modules/react/lib/Transaction.js:168:75)
      at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:135:12)
      at ReactUpdatesFlushTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
      at ReactUpdatesFlushTransaction.assign.perform (node_modules/react/lib/ReactUpdates.js:86:38)
      at Object.flushBatchedUpdates (node_modules/react/lib/ReactUpdates.js:147:19)
      at Object.wrapper [as flushBatchedUpdates] (node_modules/react/lib/ReactPerf.js:66:21)
      at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (node_modules/react/lib/Transaction.js:202:25)
      at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:149:16)
```

On looking at `node_modules/react/node_modules/fbjs/lib/getActiveElement.js` I see that it just reads from document object. So I just defined `document` globally which fixed the issue.

`global.document = {};` fixes the issue. But this was not a problem with `react-0.14.4`.
However same test case passes when running individually (as against running a bunch of test cases) even if `global.document` is not defined.

**Comment by zpao** [comment]
Known issue at the moment. Sorry about that. See #5779. 0.14.4 does have the issue with the browser builds but not the npm build due to the way things are packaged so we'll have to ship 0.14.6 most likely.
