### ISSUE TITLE
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

### ISSUE THREAD

**Issue by guileen** [facebook/react#5927]
I have a simple React component, but it fail to instant React Component.

Exmaple.js
```js
import React, {Component} from 'react'
import * as ExampleActions from '../actions/ExampleActions'
import styles from '../../css/app.css'

class Example extends Component {
  render() {
    const {title, dispatch} = this.props
    const actions = bindActionCreators(ExampleActions, dispatch)
    return (
        <div>
          <h1 className={styles.text}>Welcome {title}!</h1>
          <button onClick={e => actions.changeTitle('' + Date.now())}>
            Update Title
          </button>
        </div>
    )
  }
}
```

ExampleTest.js
```js
jest.dontMock('../Example')
import React from 'react'
import ReactDOM from 'react-dom'
import {renderIntoDocument, Simulate, findRenderedDOMComponentWithTag} from 'react-addons-test-utils'

const Example = require('../Example')

describe('Example', () => {
  it('rendering', () => {
    var example = renderIntoDocument(
        <Example title="hello"/>
    )
  })
})
```

jest output.
```
Using Jest CLI v0.8.2, jasmine1
Running 1 test suite...Warning: React.createElement: type should not be null, undefined, boolean, or number. It should be a string (for DOM elements) or a ReactClass (for composite components).
 FAIL  js/components/__tests__/ExampleTest.js (0.611s)
● Example › it rendering
  - Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
        at invariant (node_modules/fbjs/lib/invariant.js:39:15)
        at instantiateReactComponent [as _instantiateReactComponent] (node_modules/react/lib/instantiateReactComponent.js:64:134)
        at ReactCompositeComponentMixin.mountComponent (node_modules/react/lib/ReactCompositeComponent.js:223:36)
        at wrapper [as mountComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactReconciler.mountComponent (node_modules/react/lib/ReactReconciler.js:37:35)
        at mountComponentIntoNode (node_modules/react/lib/ReactMount.js:266:32)
        at ReactReconcileTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at batchedMountComponentIntoNode (node_modules/react/lib/ReactMount.js:282:15)
        at ReactDefaultBatchingStrategyTransaction.Mixin.perform (node_modules/react/lib/Transaction.js:136:20)
        at Object.ReactDefaultBatchingStrategy.batchedUpdates (node_modules/react/lib/ReactDefaultBatchingStrategy.js:62:19)
        at Object.batchedUpdates (node_modules/react/lib/ReactUpdates.js:94:20)
        at Object.ReactMount._renderNewRootComponent (node_modules/react/lib/ReactMount.js:476:18)
        at Object.wrapper [as _renderNewRootComponent] (node_modules/react/lib/ReactPerf.js:66:21)
        at Object.ReactMount._renderSubtreeIntoContainer (node_modules/react/lib/ReactMount.js:550:32)
        at Object.ReactMount.render (node_modules/react/lib/ReactMount.js:570:23)
        at Object.wrapper [as render] (node_modules/react/lib/ReactPerf.js:66:21)
        at ReactTestUtils.renderIntoDocument (node_modules/react/lib/ReactTestUtils.js:76:21)
        at Spec.eval (js/components/__tests__/ExampleTest.js:10:64)
```

```
npm 3.3.12
node v5.2.0
"react": "^0.14.6",
"react-dom": "^0.14.6",
"react-addons-test-utils": "^0.14.6",
"react-transform-catch-errors": "^1.0.1",
"react-transform-hmr": "^1.0.1",
"jest-cli": "^0.8.2",
```

**Comment by jimfb** [comment]
This is almost certainly a usage error.  You are probably passing in a null (or other non-component value) somewhere.  Most likely your `Example` component, based on your code snippet, is not being required properly.

If you believe this is a bug in React, please create a simple jsfiddle that demonstrates the problem and we can re-investigate.  My fiddle: http://jsfiddle.net/1eqfp1vp/
