### ISSUE TITLE
Getting started docs are ambiguous

### ISSUE THREAD

**Issue by regularfry** [facebook/react#6025]
Working through `react/docs/docs/getting-started.md` as a user new to `npm` would, I run into the following:

1.
```
$ npm install --save react react-dom babel-preset-react
$ webpack
```

This doesn't work, webpack throws an error.  What's the correct webpack invocation here?

2.
```
If you are using ES2015, you will want to also use the babel-preset-es2015 package.
```

How will I know?

3.
```
Note: by default, React will be in development mode, which is slower, and not advised for production. To use React in production mode, set the environment variable NODE_ENV to production (using envify or webpack's DefinePlugin). For example:

new webpack.DefinePlugin({
  "process.env": {
```

Where does this content go?  What's the filename?

**Comment by regularfry** [comment]
4.
```
$ browserify -t [ babelify --presets [ react ] ] main.js -o bundle.js
```
This doesn't work - as written, this error pops out:
```
SyntaxError: /Users/ayo07/tmp/react/main.js: Unexpected token (5:2)
  3 |
  4 | ReactDOM.render(
> 5 |   <h1>Hello, world!</h1>,
    |   ^
  6 |   document.getElementById('example')
  7 | );
    at Parser.pp.raise (/Users/ayo07/tmp/react/node_modules/babylon/index.js:1425:13)
    at Parser.pp.unexpected (/Users/ayo07/tmp/react/node_modules/babylon/index.js:2907:8)
    at Parser.pp.parseExprAtom (/Users/ayo07/tmp/react/node_modules/babylon/index.js:754:12)
    at Parser.pp.parseExprSubscripts (/Users/ayo07/tmp/react/node_modules/babylon/index.js:509:19)
    at Parser.pp.parseMaybeUnary (/Users/ayo07/tmp/react/node_modules/babylon/index.js:489:19)
    at Parser.pp.parseExprOps (/Users/ayo07/tmp/react/node_modules/babylon/index.js:420:19)
    at Parser.pp.parseMaybeConditional (/Users/ayo07/tmp/react/node_modules/babylon/index.js:402:19)
    at Parser.pp.parseMaybeAssign (/Users/ayo07/tmp/react/node_modules/babylon/index.js:365:19)
    at Parser.pp.parseExprListItem (/Users/ayo07/tmp/react/node_modules/babylon/index.js:1232:16)
    at Parser.pp.parseCallExpressionArguments (/Users/ayo07/tmp/react/node_modules/babylon/index.js:585:20)
```
so the guide's missing a .jsx -> .js step.

**Comment by jimfb** [comment]
Yeah, I agree.  NPM is a super complex piece of software.  If you're not familiar with NPM (I was not when I first got started), it's an uphill battle.  Just installing NPM itself is hard.

 > so the guide's missing a .jsx -> .js step.

Anyway, the react-presets for babel is what does that conversion, so it's all there.  It's just that npm is hard if you've never used it before.  That's why I kind of wish that we made the non-npm instructions more prominent for new users (perhaps by reversing the order of the two sets of instructions).  Anyway, if you scroll down on the getting-started page, you'll find the non-npm instructions, and those are much easier to follow if you're just checking out React for the first time.

**Comment by regularfry** [comment]
Wouldn't it be better to *only* have the non-npm instructions, rather than having instructions which don't work as written?

**Comment by ryneeverett** [comment]
> Wouldn't it be better to only have the non-npm instructions, rather than having instructions which don't work as written?

Yes.

**Comment by ryneeverett** [comment]
Looks like fixing webpack docs is being tracked in #5685.

**Comment by regularfry** [comment]
:+1:

**Comment by dspjm** [comment]
I don't think I can trust this library if even the getting started part is wrong and doesn't work.
Such a poor quality.
