### ISSUE TITLE
Unable to use transpiled ES6 classes as components in React 15.0.1

### ISSUE THREAD

**Issue by danpantry** [facebook/react#6468]
The following code snippet:

```
'use strict'
import React from 'react'
import {render} from 'react-dom'
import jsdom from 'jsdom'

class KendoScheduler {
  componentDidMount() {
    console.log(this.refs.container)
  }

  render() {
    return <div ref='container' className='kendo-container' />
  }
}

jsdom.env('<html><body><div id="container"></div></body></html>', function (err, window) {
  const el = window.document.getElementById('container')
  // set up some globals as React uses them
  global.window = window
  global.document = window.document
  render(<KendoScheduler />, el)
})
```

When run with `react@15.0.1` will emit the following error:

```
TypeError: Cannot call a class as a function
    at _classCallCheck (kendoScheduler.js:4:1)
    at KendoScheduler (kendoScheduler.js:6:7)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactCompositeComponent.js:170:18)
    at [object Object].wrapper [as mountComponent] (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactReconciler.js:39:35)
    at [object Object].ReactCompositeComponentMixin.performInitialMount (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactCompositeComponent.js:290:34)
    at [object Object].ReactCompositeComponentMixin.mountComponent (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactCompositeComponent.js:237:21)
    at [object Object].wrapper [as mountComponent] (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactPerf.js:66:21)
    at Object.ReactReconciler.mountComponent (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactReconciler.js:39:35)
    at mountComponentIntoNode (C:\Users\Dan\projects\@danpantry\node_modules\react\lib\ReactMount.js:103:32)
```

The *same code* run with `react@0.14.8` work perfectly.

Post-compiled code looks like this:
```
'use strict';

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

var _react = require('react');

var _react2 = _interopRequireDefault(_react);

var _reactDom = require('react-dom');

var _jsdom = require('jsdom');

var _jsdom2 = _interopRequireDefault(_jsdom);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var KendoScheduler = function () {
  function KendoScheduler() {
    _classCallCheck(this, KendoScheduler);
  }

  _createClass(KendoScheduler, [{
    key: 'componentDidMount',
    value: function componentDidMount() {
      console.log(this.refs.container);
    }
  }, {
    key: 'render',
    value: function render() {
      return _react2.default.createElement('div', { ref: 'container', className: 'kendo-container' });
    }
  }]);

  return KendoScheduler;
}();

_jsdom2.default.env('<html><body><div id="container"></div></body></html>', function (err, window) {
  var el = window.document.getElementById('container');
  // set up some globals as React uses them
  global.window = window;
  global.document = window.document;
  (0, _reactDom.render)(_react2.default.createElement(
    'h1',
    null,
    'Test'
  ), el);
});
```

Version info:

```
babel-preset-es2015@6.6.0
babel-preset-react@6.5.0
jsdom@8.3.0
react@0.14.8
react-dom@0.14.8
```

Let me know if any more information is required.

**Comment by danpantry** [comment]
I'm an idiot and didn't expect `React.Component`.
