### ISSUE TITLE
Error using nashorn and java 8

### ISSUE THREAD

**Issue by rashmimadanshukla** [facebook/react#6505]
I lately upgraded my code from java 7 to java 8... And i am getting the following error. Can anyone help?
Exception in thread "main" java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.ArrayStoreException: jdk.nashorn.internal.runtime.Undefined
    at jdk.nashorn.internal.runtime.arrays.ObjectArrayData.setEmpty(ObjectArrayData.java:168)
    at jdk.nashorn.internal.runtime.arrays.ObjectArrayData.delete(ObjectArrayData.java:240)
    at jdk.nashorn.internal.runtime.ScriptObject.delete(ScriptObject.java:3599)
    at jdk.nashorn.internal.objects.NativeArray.shift(NativeArray.java:1161)
    at jdk.nashorn.internal.scripts.Script$13$\^eval\_.:program(<eval>:32)
    at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:623)
    at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
    at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:446)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:403)
    at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:399)
    at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:150)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:249)
    at uglify.UglifyJS.run(UglifyJS.java:75)
    at uglify.UglifyJS.exec(UglifyJS.java:50)
    at uglify.UglifyJS.main(UglifyJS.java:16)

**Comment by jimfb** [comment]
There is not much info to go on here.  This looks to me like the error is occurring in UglifyJS (not React).

@rashmimadanshukla If you can provide a simplified example that demonstrates the issue, we can investigate further.

**Comment by glennreyes** [comment]
It looks like that the UglifyJS Plugin isn't well supported within the Nashorn engine. There might be some differences between the Nashorn and V8.

**Comment by jimfb** [comment]
Ping @rashmimadanshukla

**Comment by jimfb** [comment]
Closing due to no response from OP.  We can re-investigate if/when we can get a repro.
