### ISSUE TITLE
Pass default parameter values in function

### ISSUE THREAD

**Issue by nilaybrahmbhatt** [facebook/react#7441]
I got this error after updating react-native and react

i think this is right syntex  but i dont know why this error is coming

```
this.list = function(table, callback, wheredata = [],selection = '',extra = '') {
                                                  ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/apcrat/Documents/redux/delfoo_React/api/model/catalog/cuisine_route.js:7:12)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

**Comment by gaearon** [comment]
Sorry, unfortunately there is not enough information to help you here. Can you ask this on StackOverflow instead?

We use the issue tracker for bugs in React. Since you get a syntax error, it has no relation to React (a JavaScript library).

Perhaps you could try reporting this on React Native repo (if this is related to React Native build pipeline) but you would need to provide a full example reproducing this for someone to help you.

Cheers!
