### ISSUE TITLE
ReactTestRenderer:  Invariant Violation: getNodeFromInstance: Invalid argument.

### ISSUE THREAD

**Issue by rhalff** [facebook/react#8324]
I'm following the example at https://facebook.github.io/jest/docs/tutorial-react.html#content in order to use snapshots with jest.

I run into a bug within `react-test-renderer`, it seems to fail whenever findDOMNode is used on a component instance.

Minimal code to replicate the bug:
```js
import React, { Component } from 'react'
import { findDOMNode } from 'react-dom'
import renderer from 'react-test-renderer'

class MyComp extends Component {
  componentDidMount() {
    findDOMNode(this)
  }
  render() {
    return <i />
  }
}

renderer.create(<MyComp />);
```

The Error:
```js
 Invariant Violation: getNodeFromInstance: Invalid argument.
      
      at invariant (node_modules/fbjs/lib/invariant.js:38:15)
      at Object.getNodeFromInstance (node_modules/react-dom/lib/ReactDOMComponentTree.js:155:77)
      at findDOMNode (node_modules/react-dom/lib/findDOMNode.js:49:41)
      at MyComp.componentDidMount (my.test.js:7:59)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:265:25
      at measureLifeCyclePerf (node_modules/react-test-renderer/lib/ReactCompositeComponent.js:75:12)
      at node_modules/react-test-renderer/lib/ReactCompositeComponent.js:264:11
      at CallbackQueue.notifyAll (node_modules/react-test-renderer/lib/CallbackQueue.js:76:22)
      at ReactTestReconcileTransaction.close (node_modules/react-test-renderer/lib/ReactTestReconcileTransaction.js:36:26)
      at ReactTestReconcileTransaction.closeAll (node_modules/react-test-renderer/lib/Transaction.js:206:25)
      at ReactTestReconcileTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:153:16)
      at batchedMountComponentIntoNode (node_modules/react-test-renderer/lib/ReactTestMount.js:69:27)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-test-renderer/lib/Transaction.js:140:20)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-test-renderer/lib/ReactUpdates.js:97:27)
      at Object.render (node_modules/react-test-renderer/lib/ReactTestMount.js:125:18)
      at Object.<anonymous> (my.test.js:14:55)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

React versions:
 * react: 15.4.0
 * react-dom: 15.4.0
 * react-test-renderer: 15.4.0

**Comment by rhalff** [comment]
Nevermind, just found it's not supported: https://github.com/facebook/react/issues/7371

**Comment by gaearon** [comment]
Yea sorry, refs can work but `findDOMNode()` can't (we tried).

**Comment by SchubertD** [comment]
I also have a problem.... 
When send a function in a prop to a child component... The production code works, however the test doesn't work same error. :(

**Comment by gaearon** [comment]
If you mean you're using `findDOMNode()` in test renderer, it won't work. Please see https://github.com/facebook/react/issues/7371 for reasons why.

**Comment by joshua703** [comment]
I came upon this issue after upgrading from Enzyme 2 to Enzyme 3. If anyone experiences this when [upgrading Enzyme](http://airbnb.io/enzyme/docs/guides/migration-from-2-to-3.html), it can be fixed by disabling testing of the lifecycle methods:

```js
configure({
  adapter: new Adapter(),
  disableLifecycleMethods: true,
})
```
