### ISSUE TITLE
npm install Microtime problem

### ISSUE THREAD

**Issue by max-mykhailenko** [facebook/react#8435]
BUG

If I want to install react-dom@15.4.1 in my docker ubuntu environment I got an error.

```
> microtime@2.0.0 install /var/www/node_modules/microtime
> node-gyp rebuild

gyp info it worked if it ends with ok
gyp info using node-gyp@3.3.1
gyp info using node@6.3.0 | linux | x64
gyp http GET https://nodejs.org/download/release/v6.3.0/node-v6.3.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.3.0/node-v6.3.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.3.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.3.0/SHASUMS256.txt
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/var/www/node_modules/microtime/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/6.3.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/6.3.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=/var/www/node_modules/microtime',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/var/www/node_modules/microtime/build'
make: Warning: File 'microtime.target.mk' has modification time 199926 s in the future
  CXX(target) Release/obj.target/microtime/src/microtime.o
In file included from ../src/microtime.cc:9:0:
../../nan/nan.h:590:20: error: variable or field 'AddGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:590:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:591:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:596:20: error: variable or field 'RemoveGCEpilogueCallback' declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:596:7: error: 'GCEpilogueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:601:20: error: variable or field 'AddGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:601:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:602:18: error: expected primary-expression before 'gc_type_filter'
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:607:20: error: variable or field 'RemoveGCPrologueCallback' declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:607:7: error: 'GCPrologueCallback' is not a member of 'v8::Isolate'
       v8::Isolate::GCPrologueCallback callback) {
       ^
microtime.target.mk:88: recipe for target 'Release/obj.target/microtime/src/microtime.o' failed
make: *** [Release/obj.target/microtime/src/microtime.o] Error 1
make: Leaving directory '/var/www/node_modules/microtime/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Linux 4.4.30-moby
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/node_modules/microtime
gyp ERR! node -v v6.3.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm info lifecycle microtime@2.0.0~install: Failed to exec install script
npm WARN install:microtime@2.0.0 microtime@2.0.0 install: `node-gyp rebuild`
npm WARN install:microtime@2.0.0 Exit status 1
npm info lifecycle react-dom@15.4.1~install: react-dom@15.4.1
npm info lifecycle react-dom@15.4.1~postinstall: react-dom@15.4.1
- asap@2.0.5 node_modules/react-dom/node_modules/asap
- core-js@1.2.7 node_modules/react-dom/node_modules/core-js
- promise@7.1.1 node_modules/react-dom/node_modules/promise
- whatwg-fetch@0.9.0 node_modules/react-dom/node_modules/whatwg-fetch
- fbjs@0.6.1 node_modules/react-dom/node_modules/fbjs
- react@0.14.8 node_modules/react-dom/node_modules/react
Holdshort@3.0.0 /var/www
```

Possible solution — bump microtime to 2.1.2

**Comment by gaearon** [comment]
I don't think this is related to `react-dom`.
When I run `npm i react react-dom` I don't get `microtime` in there:

```
npm i react react-dom
(node:23100) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/gaearon/p/waaaat
├─┬ react@15.4.1 
│ ├─┬ fbjs@0.8.6 
│ │ ├── core-js@1.2.7 
│ │ ├─┬ isomorphic-fetch@2.2.1 
│ │ │ ├─┬ node-fetch@1.6.3 
│ │ │ │ ├─┬ encoding@0.1.12 
│ │ │ │ │ └── iconv-lite@0.4.15 
│ │ │ │ └── is-stream@1.1.0 
│ │ │ └── whatwg-fetch@2.0.1 
│ │ ├─┬ promise@7.1.1 
│ │ │ └── asap@2.0.5 
│ │ └── ua-parser-js@0.7.12 
│ ├─┬ loose-envify@1.3.0 
│ │ └── js-tokens@2.0.0 
│ └── object-assign@4.1.0 
└── react-dom@15.4.1 
```

So it's likely some other dependency is bringing it in.
