### ISSUE TITLE
Can't Render Meta tags on Server side

### ISSUE THREAD

**Issue by rbaindourov** [facebook/react#8501]
**Do you want to request a *feature* or report a *bug*?**
I am reporting a bug.

**What is the current behavior?**

I am trying to iterate over an array of objects that represent meta tags but I am getting an error.

```javascript
import React from 'react';

let Metas = React.createClass({
  propTypes: {
    metas: React.PropTypes.array
  },

  render: function() {
    return (
        <meta charset="UTF-8">
        {
          this.props.metas.map(function(meta) {
            return <meta name={meta.name} content={meta.content}>
          })
        }
      );
    }
});

module.exports = Metas;
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

This is a server side rendering issue with Express.

SyntaxError: /Users/robert/domain-watchdog/views/metas.jsx: Unterminated JSX contents (13:65)
  11 |         {
  12 |           this.props.metas.map(function(meta) {
> 13 |             return <meta name={meta.name} content={meta.content}>
     |                                                                  ^
  14 |           })
  15 |         }
  16 |       );
    at Parser.pp$5.raise (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp$8.jsxReadToken (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:6039:12)
    at Parser.readToken (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:6412:21)
    at Parser.nextToken (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:684:19)
    at Parser.next (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:609:10)
    at Parser.eat (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:616:12)
    at Parser.pp.expect (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:1615:15)
    at Parser.pp$8.jsxParseOpeningElementAt (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:6314:8)
    at Parser.pp$8.jsxParseElementAt (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:6333:29)
    at Parser.pp$8.jsxParseElement (/Users/robert/domain-watchdog/node_modules/babylon/lib/index.js:6388:15)

**What is the expected behavior?**
For the React Parser to work correctly over meta tags on the server side. 

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

I've never tried this before, but it seems there are lots of libraries like react-helmet that use the rewind api to solve for this.

I think that's not right. I should be able to render Meta tags without having to jump through hoops. 

"express-react-views": "^0.10.2",
  "react": "15.3.0",
   "react-addons-create-fragment": "15.3.0",
    "react-addons-css-transition-group": "15.3.0",
    "react-addons-linked-state-mixin": "15.3.0",
    "react-addons-shallow-compare": "15.3.0",
    "react-addons-update": "15.3.0",
    "react-click-outside": "2.1.0",
    "react-day-picker": "2.4.1",
    "react-dom": "15.3.0",
    "react-masonry-component": "4.2.2",
    "react-pure-render": "1.0.2",
    "react-redux": "4.4.5",
    "react-tap-event-plugin": "1.0.0",
    "react-virtualized": "7.9.1",
    "redux": "3.0.4",
    "redux-thunk": "1.0.0",

**Comment by dkrichards86** [comment]
Have you tried it with closed meta tags?  JSX requires a closing tag.

**Comment by rbaindourov** [comment]
Sorry, I forgot that you need closing tags such as div.
My overall approach is incorrect. I am breaking down the head section too much.
