### ISSUE TITLE
React 15.4.1  missing files.

### ISSUE THREAD

**Issue by EasonWang01** [facebook/react#8588]
```
module.js:471
    throw err;
    ^

Error: Cannot find module 'react/lib/ReactDOMServer'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/node_modules/react-dom/server.js:3:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/etc/nginx/sites-available/React-router-Redux-isomorphic-Boilerplate/src/dist/server.js:23:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

**Comment by EasonWang01** [comment]
I found the problem is that there is no ReactDOMServer.js in React/lib when I install react in the linux ubuntu enviroment, node version v6.9.1.

**Comment by EasonWang01** [comment]
only got this in react/lib

```
KeyEscapeUtils.js                     ReactPropTypeLocationNames.js
LinkedStateMixin.js                   ReactPropTypeLocations.js
PooledClass.js                        ReactPropTypes.js
React.js                              ReactPropTypesSecret.js
ReactAddonsDOMDependencies.js         ReactPureComponent.js
ReactAddonsDOMDependenciesUMDShim.js  ReactStateSetters.js
ReactCSSTransitionGroup.js            ReactTransitionChildMapping.js
ReactCSSTransitionGroupChild.js       ReactTransitionEvents.js
ReactChildren.js                      ReactTransitionGroup.js
ReactClass.js                         ReactUMDEntry.js
ReactComponent.js                     ReactUMDShim.js
ReactComponentTreeDevtool.js          ReactVersion.js
ReactComponentTreeHook.js             ReactWithAddons.js
ReactComponentTreeHookUMDShim.js      ReactWithAddonsUMDEntry.js
ReactComponentWithPureRenderMixin.js  canDefineProperty.js
ReactCurrentOwner.js                  checkReactTypeSpec.js
ReactCurrentOwnerUMDShim.js           deprecated.js
ReactDOMFactories.js                  flattenChildren.js                getIteratorFn.js
ReactElement.js                       getNextDebugID.js
ReactElementSymbol.js                 onlyChild.js
ReactElementType.js                   reactProdInvariant.js
ReactElementValidator.js              shallowCompare.js
ReactFragment.js                      sliceChildren.js
ReactLink.js                          traverseAllChildren.js
ReactNoopUpdateQueue.js               update.js
```

**Comment by EasonWang01** [comment]
why it will miss all those files?

```
ReactDOMServer.js
ReactDefaultInjection.js
ReactServerRendering.js
ReactVersion.js
```

**Comment by Kovensky** [comment]
That is because they have been deprecated since React 0.14 and were removed in 15.4.

Change the import to `react-dom/server` instead.

**Comment by gaearon** [comment]
Anything inside `/lib` are private implementation details that can change in any version. Please never use them directly. The public API is documented, and you never need to import something from `/lib`.

If you see React itself trying to import this and failing it is likely you have incompatible versions of `react` and `react-dom` installed. Make sure they're both 15.4.1 and the error will go away.

I hope this helps!

**Comment by EasonWang01** [comment]
I was using `import {renderToString} from 'react-dom/server';`

not import anything directly.

**Comment by gaearon** [comment]
Please see the second paragraph of my reply. From your other issue I can see that the versions are not matching. This is not supported.

**Comment by EasonWang01** [comment]
thanks

**Comment by EasonWang01** [comment]
```
    "react": "^15.4.1",
    "react-dom": "^15.4.1",
```

but after upgrade, it will cause this
`Error: Cannot find module 'react/lib/EventPluginHub'`

**Comment by gaearon** [comment]
Some modules like `react-tap-event-plugin` relied on React internal APIs and you need to update them. We don't officially recommend relying on private APIs because they will keep changing.

By the way, you don't need `sudo` when you run `npm install`. This can create problems later.

**Comment by EasonWang01** [comment]
(ﾟдﾟ)  what problem might cause later when using sudo.

**Comment by gaearon** [comment]
>what problem might cause later when using sudo.

You may get wrong permissions on files.

**Comment by EasonWang01** [comment]
thanks,I found this article and realize it.
https://pawelgrzybek.com/fix-priviliges-and-never-again-use-sudo-with-npm/
