### ISSUE TITLE
ReactClassEquivalence tests fail on Node v7.3.0

### ISSUE THREAD

**Issue by churchie317** [facebook/react#8715]
As the title says, `ReactClassEquivalence > tests the same thing for es6 classes and CoffeeScript` fails when run on Node v7.3.0.

I can confirm that the tests pass on v6.9.3, v7.0.0, v7.1.0, and v7.2.0.

I've included the output of the failing tests below:

```
● ReactClassEquivalence › tests the same thing for es6 classes and CoffeeScript

    No spec results found in the output
      
      at compareResults (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:72:11)
      at Object.<anonymous> (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:21:5)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  ● ReactClassEquivalence › tests the same thing for es6 classes and TypeScript

    No spec results found in the output
      
      at compareResults (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:72:11)
      at Object.<anonymous> (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:27:5)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

Summary of all failing tests
 FAIL  src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js (11.302s)
  ● ReactClassEquivalence › tests the same thing for es6 classes and CoffeeScript

    No spec results found in the output
      
      at compareResults (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:72:11)
      at Object.<anonymous> (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:21:5)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)

  ● ReactClassEquivalence › tests the same thing for es6 classes and TypeScript

    No spec results found in the output
      
      at compareResults (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:72:11)
      at Object.<anonymous> (src/isomorphic/modern/class/__tests__/ReactClassEquivalence-test.js:27:5)
      at handle (node_modules/worker-farm/lib/child/index.js:41:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:47:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:191:7)
      at process.nextTick (internal/child_process.js:752:12)
      at _combinedTickCallback (internal/process/next_tick.js:67:7)
      at process._tickCallback (internal/process/next_tick.js:98:9)
```

@bvaughn and I briefly discussed the problem in #8667 where he confirmed the failing behavior.

**Comment by gaearon** [comment]
Thanks for filing the issue.
Do you want to dig into why this happens?

**Comment by churchie317** [comment]
Sure thing!

**Comment by gaearon** [comment]
Thank you!

**Comment by zakarhino** [comment]
Looks like updating to jest 18.1.0 fixes this issue. It's related to an issue you and several others reported, @gaearon, https://github.com/facebook/jest/issues/2166

The fix:
https://github.com/facebook/jest/pull/2464/files
