### ISSUE TITLE
Make Circle run properly on 15-stable branch

### ISSUE THREAD

**Issue by spicyj** [facebook/react#8744]
We're missing the .circle.yml config on our 15-stable branch. It would be great to copy it over and whatever other files need to be copied to make CI pass. Anyone should be able to test by sending a PR to 15-stable (unlike normal PRs which go to master) with the changes and seeing if Circle will pass. It might be as simple as just copying .circle.yml and scripts/circleci.

**Comment by gaearon** [comment]
Fingers crossed for https://github.com/facebook/react/issues/8745!

**Comment by jjcross** [comment]
I was able to get CircleCI passing by copying circle.yml and scripts/circleci and making a few other tweaks.  There also seemed to be some linting errors according to [this build](https://circleci.com/gh/facebook/react/774) so I fixed those.

One concern I had was adding `jest-cli` to devDependencies, but it was the only way I could fix this error:
```
Error: Cannot find module '/home/ubuntu/react/node_modules/jest-cli'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getJest (/home/ubuntu/react/node_modules/jest/node_modules/jest-cli/build/cli/getJest.js:24:12)
    at Object.run (/home/ubuntu/react/node_modules/jest/node_modules/jest-cli/build/cli/index.js:40:3)
    at Object.<anonymous> (/home/ubuntu/react/node_modules/jest/node_modules/jest-cli/bin/jest.js:16:25)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
It seems that somehow `fs.existsSync` is returning true but `require` isn't able to find the module [in jest-cli](https://github.com/facebook/jest/blob/master/packages/jest-cli/src/cli/getJest.js#L24).  If anyone knows more about what is happening there that would be a huge help!

**Comment by rolfea** [comment]
it looks like this got resolved, right?

**Comment by gaearon** [comment]
Yup!
