### ISSUE TITLE
ReactTestUtils: event dispatched before workInProgress stateNode is set

### ISSUE THREAD

**Issue by aweary** [facebook/react#9504]
With the following, using the latest alpha (10) and `jsdom` 9.12.0:

```js
const ReactTestUtils = require('react-dom/test-utils')

const Foo = () => (
  React.createElement(
    'div',
    null,
    React.createElement('img', { src: 'foo.jpg'})
  )
)

ReactTestUtils.renderIntoDocument(
  React.createElement(Foo)
)
```

The following error is thrown:

```
TypeError: Cannot read property 'nodeName' of null
    at shouldUseChangeEvent (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:6310:22)
    at Object.extractEvents (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:6495:9)
    at Object.extractEvents (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:715:46)
    at Object.handleTopLevel [as _handleTopLevel] (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:772:35)
    at handleTopLevelImpl (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:7051:24)
    at batchedUpdates (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:14806:14)
    at performFiberBatchedUpdates (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:6161:10)
    at stackBatchedUpdates (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:6152:10)
    at batchedUpdates (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.js:6166:10)
    at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (/Users/brandondail/projects/react-tester/node_modules/react-dom/cjs/react-dom.development.
js:6179:12)
```

The issue is that [`completeWork` calls `finalizeInitialChildren`](https://github.com/facebook/react/blob/b1768b5a48d1f82e4ef4150e0036c5f846d3758a/src/renderers/shared/fiber/ReactFiberCompleteWork.js#L275-L279) before it [sets the `stateNode`](https://github.com/facebook/react/blob/b1768b5a48d1f82e4ef4150e0036c5f846d3758a/src/renderers/shared/fiber/ReactFiberCompleteWork.js#L285) on the `workInProgress`.

 `finalizeInitialChildren` eventually calls `setValueForProperty` for the image tag, which sets the `src` property, and causes jsdom to trigger an event. The top level event listener then [grabs that instance](https://github.com/facebook/react/blob/4c292facc9fa176cd0a8a094b38fc1800650325f/src/renderers/dom/shared/ReactEventListener.js#L178), which has no `stateNode` which eventually triggers the error.

`ReactTestUtils` is likely to be used frequently with jsdom so I think it's important to support. Is this something that can be addressed in Fiber?

**Comment by gaearon** [comment]
Can you send a fix for this?

**Comment by aweary** [comment]
@gaearon I'll give it a shot 👍

**Comment by aweary** [comment]
I can no longer reproduce this issue with the latest releases.
