### ISSUE TITLE
Error boundaries in renderToString: "TypeError: Cannot read property 'listeners' of null" in renderToString

### ISSUE THREAD

**Issue by StevenLangbroek** [facebook/react#9674]
**Do you want to request a *feature* or report a *bug*?**

Report a Bug

**What is the current behavior?**

We're seeing errors in Kibana, across our userbase, when rendering in NodeJS:

```
TypeError: Cannot read property 'listeners' of null
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:960:43)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/84v837e9/).**

Because this happens in React internals, and we haven't been able to reproduce the issue, I'm struggling to create a minimal repro. I've searched for this issue, but have only been able to find gaearon/react-hot-loader#466, which wasn't exactly helpful as we don't use React Hot Loader... Can someone maybe explain to me what type of behavior would cause this? Based on that I can dig a bit further.

**What is the expected behavior?**

No error.

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?**

**Packages**
React: 15.4.2
React-DOM: 15.4.2

*update*: could have coincided with 15.4.1 -> 15.4.2 upgrade.

**Server**
Node: 5.x

**Comment by danez** [comment]
This happens for use when a component implements `unstable_handleError()` and one of its subcomponents throws an error. And only when doing `renderToString()`.

So to update the above description:
Expected should be the real error message.

Here is also the non truncated stacktrace:

```
TypeError: Cannot read property 'listeners' of null
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:960:43)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at Object.ReactChildReconciler.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactChildReconciler.js:146:25)
    at ReactDOMComponent.ReactMultiChild.Mixin.unmountChildren ([PATH_OMITTED]/node_modules/react-dom/lib/ReactMultiChild.js:373:28)
    at ReactDOMComponent.Mixin.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactDOMComponent.js:980:10)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at Object.ReactReconciler.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:79:22)
    at ReactCompositeComponent.unmountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:418:23)
    at ReactCompositeComponent.performInitialMountWithErrorHandling ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:327:31)
    at ReactCompositeComponent.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:256:21)
    at Object.ReactReconciler.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponent.performInitialMount ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponent.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at ReactCompositeComponent.performInitialMount ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:371:34)
    at ReactCompositeComponent.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactCompositeComponent.js:258:21)
    at Object.ReactReconciler.mountComponent ([PATH_OMITTED]/node_modules/react-dom/lib/ReactReconciler.js:46:35)
    at [PATH_OMITTED]/node_modules/react-dom/lib/ReactServerRendering.js:45:36
    at ReactServerRenderingTransaction.TransactionImpl.perform ([PATH_OMITTED]/node_modules/react-dom/lib/Transaction.js:140:20)
    at renderToStringImpl ([PATH_OMITTED]/node_modules/react-dom/lib/ReactServerRendering.js:43:24)
    at Object.renderToString ([PATH_OMITTED]/node_modules/react-dom/lib/ReactServerRendering.js:73:10)
```

**Comment by gaearon** [comment]
Error boundaries are currently not supported for server rendering.

As for the initial error report, there's nothing we can do without seeing an example that reproduces this. This code doesn't exist on master anymore so the bug report is most likely outdated. If you can reproduce this with React 16 betas that will come out soon, please let us know.
